from pathlib import Path

idx=Path('index.html');s=idx.read_text();marker='<script src="./field-position.js"></script>'
block='''<script src="./field-orientation.js"></script>\n<script src="./cloud-conflict.js"></script>\n<script src="./game-lifecycle.js"></script>\n<script src="./voice-workflow.js"></script>\n<script src="./edit-play-model.js"></script>'''
if block not in s:
    if s.count(marker)!=1: raise SystemExit(f'index field-position marker count={s.count(marker)}')
    s=s.replace(marker,marker+'\n'+block,1);idx.write_text(s)
p=Path('field-position.js');f=p.read_text()
if 'SidelineFieldOrientation' not in f: raise SystemExit('quarter-aware field source missing')
a=Path('app.js');x=a.read_text()
# Defensive editor source migration: eliminate dependence on the service-worker runtime transform.
if 'id="editDefPD"' not in x:
    old='''  if(p.type==="Defense"&&p.defCredits){let html=`<div class="muted">Defense • ${esc(p.sub)}</div><label>Defender credits</label>`;html+=S.roster.map(r=>{const cur=Number(p.defCredits[r.id]||0);return `<div class="def-credit-row"><div class="def-credit-player"><span>#${r.jersey}</span> ${esc(r.name)}</div><button type="button" class="credit-btn edit-def-credit ${cur===0.5?"active":""}" data-id="${r.id}" data-v="0.5">0.5</button><button type="button" class="credit-btn edit-def-credit ${cur===1?"active":""}" data-id="${r.id}" data-v="1">1.0</button></div>`;}).join("");$("#editFields").innerHTML=html;$("#editPlayCard").classList.remove("hidden");const temp={...p.defCredits};$$(".edit-def-credit").forEach(b=>b.addEventListener("click",()=>{const pid=b.dataset.id,v=Number(b.dataset.v);if(Number(temp[pid])===v){delete temp[pid];b.classList.remove("active")}else{temp[pid]=v;document.querySelectorAll(`.edit-def-credit[data-id="${pid}"]`).forEach(x=>x.classList.remove("active"));b.classList.add("active")}$("#editPlayCard").dataset.defCredits=JSON.stringify(temp);}));$("#editPlayCard").dataset.defCredits=JSON.stringify(temp);$("#editPlayCard").scrollIntoView({behavior:"smooth",block:"center"});return;}'''
    new='''  if(p.type==="Defense"&&p.defCredits){
    const opt=(sel,blank="None")=>`<option value="">${blank}</option>`+playerOptions(sel);
    let html=`<div class="muted">Defense • ${esc(p.sub)}</div><label>Defender credits</label>`;
    html+=S.roster.map(r=>{const cur=Number(p.defCredits[r.id]||0);return `<div class="def-credit-row"><div class="def-credit-player"><span>#${r.jersey}</span> ${esc(r.name)}</div><button type="button" class="credit-btn edit-def-credit ${cur===0.5?"active":""}" data-id="${r.id}" data-v="0.5">0.5</button><button type="button" class="credit-btn edit-def-credit ${cur===1?"active":""}" data-id="${r.id}" data-v="1">1.0</button></div>`}).join("");
    html+=`<label>Tackle classification</label><select id="editDefKind"><option value="Tackle" ${p.tackleKind==="Tackle"?"selected":""}>Tackle</option><option value="TFL" ${p.tackleKind==="TFL"?"selected":""}>TFL</option><option value="Sack" ${p.sub==="Sack"?"selected":""}>Sack</option></select><label>Pass defended</label><select id="editDefPD">${opt(p.passDefendedPlayerId)}</select><label>Interception</label><select id="editDefINT">${opt(p.interceptionPlayerId)}</select><label>Forced fumble</label><select id="editDefFF">${opt(p.forcedFumblePlayerId)}</select><label>Fumble recovery</label><select id="editDefFR">${opt(p.fumbleRecoveryPlayerId)}</select><label>Return yards</label><input id="editDefReturn" inputmode="numeric" value="${Number(p.returnYards||0)}"><label>Defensive touchdown</label><select id="editDefTD">${opt(p.defensiveTouchdownPlayerId)}</select><label>Play yards</label><input id="editDefYards" inputmode="numeric" value="${Number(p.yards||0)}">`;
    $("#editFields").innerHTML=html;$("#editPlayCard").classList.remove("hidden");const temp={...p.defCredits};$$(".edit-def-credit").forEach(b=>b.addEventListener("click",()=>{const pid=b.dataset.id,v=Number(b.dataset.v);if(Number(temp[pid])===v){delete temp[pid];b.classList.remove("active")}else{temp[pid]=v;document.querySelectorAll(`.edit-def-credit[data-id="${pid}"]`).forEach(x=>x.classList.remove("active"));b.classList.add("active")}$("#editPlayCard").dataset.defCredits=JSON.stringify(temp)}));$("#editPlayCard").dataset.defCredits=JSON.stringify(temp);$("#editPlayCard").scrollIntoView({behavior:"smooth",block:"center"});return;
  }'''
    if x.count(old)!=1: raise SystemExit(f'defense editor source block count={x.count(old)}')
    x=x.replace(old,new,1)
    oldsave='''  if(p.type==="Defense"&&p.defCredits){const credits=JSON.parse($("#editPlayCard").dataset.defCredits||"{}");if(!Object.keys(credits).length)return toast("Select at least one defender");p.defCredits=credits;p.cloudEditedAt=Date.now();rebuildGameState(g);g.ourScore=displayedOurScore(g);persist();$("#editPlayCard").classList.add("hidden");S.editingPlayId=null;renderLiveGame();toast("Play updated");return;}'''
    newsave='''  if(p.type==="Defense"&&p.defCredits){const credits=JSON.parse($("#editPlayCard").dataset.defCredits||"{}");p.defCredits=credits;const kind=$("#editDefKind")?.value||p.tackleKind||"Tackle";p.tackleKind=kind==="Sack"?"TFL":kind;if(kind==="Sack")p.sub="Sack";else if(p.sub==="Sack")p.sub=kind;p.passDefendedPlayerId=$("#editDefPD")?.value||null;p.interceptionPlayerId=$("#editDefINT")?.value||null;p.forcedFumblePlayerId=$("#editDefFF")?.value||null;p.fumbleRecoveryPlayerId=$("#editDefFR")?.value||null;p.defensiveTouchdownPlayerId=$("#editDefTD")?.value||null;const ry=parseInt($("#editDefReturn")?.value||"0",10),y=parseInt($("#editDefYards")?.value||"0",10);if(Number.isNaN(ry)||Number.isNaN(y))return toast("Enter valid yards");p.returnYards=ry;p.yards=y;p.cloudEditedAt=Date.now();rebuildGameState(g);g.ourScore=displayedOurScore(g);persist();$("#editPlayCard").classList.add("hidden");S.editingPlayId=null;renderLiveGame();toast("Play updated");return;}'''
    if x.count(oldsave)!=1: raise SystemExit(f'defense editor save block count={x.count(oldsave)}')
    x=x.replace(oldsave,newsave,1)
required=['renderVoiceMissingFollowup(result,transcript)','id="editPenaltyType"','id="editPuntResult"','id="editTryReceiver"','id="editDefPD"','id="editDefINT"','id="editDefFF"','id="editDefFR"','id="editDefTD"','Newer cloud edit detected — refresh before overwriting','team_voice_corrections','viewer_events']
missing=[m for m in required if m not in x]
if missing: raise SystemExit('app integration marker missing: '+', '.join(missing))
a.write_text(x)
# Runtime SW patch remains temporarily for backwards compatibility, but app.js is now authoritative for defense editing.
sw=Path('service-worker.js');w=sw.read_text();needle="'./field-position.js'";assets="'./field-orientation.js','./cloud-conflict.js','./game-lifecycle.js','./voice-workflow.js','./edit-play-model.js'"
if assets not in w:
    if w.count(needle)!=1: raise SystemExit(f'SW field-position asset count={w.count(needle)}')
    w=w.replace(needle,needle+','+assets,1);sw.write_text(w)
print('Gridiron red integrations verified safely')