(function(){
  const URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co',KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';let sb=null,user=null;
  async function context(){if(!window.supabase?.createClient)throw new Error('Cloud service unavailable');if(!sb)sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const r=await sb.auth.getSession();user=r.data?.session?.user||null;if(!user)throw new Error('Sign in first');return {sb,user}}
  async function teams(){const c=await context(),q=await c.sb.from('teams').select('id,name,team_identifier,grade,created_at').eq('owner_user_id',c.user.id).order('created_at',{ascending:true});if(q.error)throw q.error;return q.data||[]}
  async function accountHasUsedTrial(c){const owned=await c.sb.from('teams').select('id').eq('owner_user_id',c.user.id);if(owned.error)throw owned.error;const ids=(owned.data||[]).map(t=>t.id);if(!ids.length)return false;const ent=await c.sb.from('team_entitlements').select('team_id,trial_used,trial_started_at').in('team_id',ids);if(ent.error)throw ent.error;return (ent.data||[]).some(e=>e.trial_used===true||!!e.trial_started_at)}
  function activeId(){try{return JSON.parse(localStorage.getItem('sidelineStatsData')||'{}')?.cloud?.teamId||''}catch(_){return ''}}
  function switchTo(teamId){window.SidelineTeamStorage?.archiveCurrent?.();localStorage.setItem('sidelineStatsLastTeam:'+user.id,teamId);window.SidelineTeamStorage?.clearWorkingCopy?.();location.reload()}
  async function open(){const m=document.getElementById('teamManagerModal'),list=document.getElementById('teamManagerList'),btn=document.getElementById('createNewTeamBtn'),note=document.getElementById('newTeamTrialNote');m.classList.remove('hidden');list.innerHTML='<div class="muted">Loading teams...</div>';try{const c=await context(),rows=await teams(),current=activeId(),used=await accountHasUsedTrial(c);m.dataset.trialUsed=used?'1':'0';btn.textContent=used?'Create Team & Choose Plan':'Create Team & Start Trial';note.textContent=used?'Your account has already used its one free trial. This team will require its own paid team-season plan.':'Your account is eligible for one 7-day free trial.';list.innerHTML='';for(const team of rows){const b=document.createElement('button');b.className='btn ghost';b.type='button';const active=current===team.id;b.textContent=(active?'✓ ':'')+team.name+(team.team_identifier?' • '+team.team_identifier:'');b.disabled=active;b.onclick=()=>switchTo(team.id);list.appendChild(b)}if(!rows.length)list.innerHTML='<div class="muted">No teams yet.</div>'}catch(e){list.textContent=e?.message||'Could not load teams'}}
  async function create(){const name=document.getElementById('newTeamName').value.trim(),identifier=document.getElementById('newTeamIdentifier').value.trim(),grade=document.getElementById('newTeamGrade').value.trim(),msg=document.getElementById('newTeamMessage'),btn=document.getElementById('createNewTeamBtn'),m=document.getElementById('teamManagerModal');if(!name){msg.textContent='Enter a team name.';return}btn.disabled=true;btn.textContent='Creating...';msg.textContent='';try{const c=await context(),used=m.dataset.trialUsed==='1'||await accountHasUsedTrial(c);window.SidelineTeamStorage?.archiveCurrent?.();const r=await c.sb.rpc('create_gridiron_team',{p_name:name,p_grade:grade||'',p_organization:'',p_primary:'#177b46',p_accent:'#f0b33b'});if(r.error)throw r.error;const row=Array.isArray(r.data)?r.data[0]:r.data,id=row?.team_id;if(!id)throw new Error('Team created but no team id was returned.');if(identifier){const u=await c.sb.from('teams').update({team_identifier:identifier}).eq('id',id);if(u.error)throw u.error}if(!used){const trial=await c.sb.rpc('start_gridiron_team_trial',{p_team_id:id});if(trial.error)throw trial.error}localStorage.setItem('sidelineStatsLastTeam:'+c.user.id,id);window.SidelineTeamStorage?.clearWorkingCopy?.();if(used)localStorage.setItem('sidelineStatsChoosePlanAfterLoad:'+id,'1');location.reload()}catch(e){console.error('Add team failed',e);msg.textContent=e?.message||'Could not create team'}finally{btn.disabled=false;btn.textContent=m.dataset.trialUsed==='1'?'Create Team & Choose Plan':'Create Team & Start Trial'}}
  function init(){const old=document.getElementById('switchTeamBtn');if(!old||document.getElementById('teamManagerModal'))return;const m=document.createElement('div');m.id='teamManagerModal';m.className='modal-backdrop hidden';m.innerHTML='<div class="modal-card account-modal-card"><button id="teamManagerClose" class="modal-close" aria-label="Close">×</button><div class="muted">YOUR ACCOUNT</div><h2>Your Teams</h2><div id="teamManagerList" style="display:grid;gap:8px;margin:14px 0"></div><button class="btn" id="addTeamBtn" type="button">+ Add New Team</button><div id="addTeamPane" class="hidden" style="margin-top:14px"><label>Team name</label><input id="newTeamName" autocomplete="off" placeholder="Denver Broncos"><label>Team identifier <span class="muted">(optional)</span></label><input id="newTeamIdentifier" autocomplete="off" placeholder="Orange • Team 2"><label>Grade or level</label><input id="newTeamGrade" autocomplete="off" placeholder="5th Grade"><div id="newTeamTrialNote" class="inline-note" style="margin-top:10px"></div><div class="modal-actions"><button class="btn" id="createNewTeamBtn" type="button">Create Team</button><button class="btn ghost" id="cancelNewTeamBtn" type="button">Cancel</button></div><div id="newTeamMessage" class="muted" style="margin-top:8px"></div></div></div>';document.body.appendChild(m);const close=()=>m.classList.add('hidden');document.getElementById('teamManagerClose').onclick=close;m.onclick=e=>{if(e.target===m)close()};old.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open()},true);document.getElementById('addTeamBtn').onclick=()=>document.getElementById('addTeamPane').classList.remove('hidden');document.getElementById('cancelNewTeamBtn').onclick=()=>document.getElementById('addTeamPane').classList.add('hidden');document.getElementById('createNewTeamBtn').onclick=create}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
