(()=>{
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const token=new URLSearchParams(location.search).get('teamInvite')||'';
let viewer=null,profiles=[],actionPhoto=null,headshot=null,lastBlob=null,lastName='player-card.png';
let actionCrop={scale:1,x:0,y:0},headCrop={scale:1,x:0,y:0};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function inject(){
 const style=document.createElement('style');style.textContent=`
 .pc-launch{border:0;background:var(--p);color:var(--p-ink);border-radius:10px;padding:10px 12px;font-weight:900;cursor:pointer}.pc-modal{position:fixed;inset:0;background:#0009;z-index:9999;display:flex;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.pc-modal.hidden{display:none}.pc-panel{width:min(780px,100%);background:#fff;color:#17202a;border-radius:18px;padding:16px;box-shadow:0 20px 60px #0006}.pc-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.pc-head h2{margin:0;font-size:22px}.pc-close{border:0;background:#eceff1;border-radius:999px;width:36px;height:36px;font-size:20px;font-weight:900}.pc-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.pc-field{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:800}.pc-field select,.pc-field input{padding:10px;border:1px solid #d6d9dc;border-radius:10px;background:#fff;font:inherit}.pc-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pc-actions button{border:0;border-radius:10px;padding:11px 14px;font-weight:900}.pc-primary{background:var(--p);color:var(--p-ink)}.pc-secondary{background:var(--a);color:var(--a-ink)}.pc-canvas-wrap{background:#242424;border-radius:14px;padding:10px;overflow:auto}.pc-stage{position:relative;width:min(100%,360px);margin:auto}.pc-stage canvas{display:block;width:100%;height:auto;border-radius:10px;box-shadow:0 4px 18px #0005}.pc-touch{position:absolute;touch-action:none;user-select:none;cursor:grab;border:1px dashed transparent}.pc-touch:active{cursor:grabbing}.pc-touch:hover{border-color:#ffffff88}.pc-touch span{position:absolute;left:50%;bottom:7px;transform:translateX(-50%);background:#111c;color:#fff;border-radius:999px;padding:4px 7px;font-size:8px;font-weight:900;white-space:nowrap;pointer-events:none}.pc-touch-action{left:7.3%;top:2.2%;width:82.2%;height:45.8%}.pc-touch-head{left:9.1%;top:53.6%;width:28.7%;height:12.3%}.pc-reset-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.pc-reset-row button{border:0;background:#eceff1;color:#17202a;border-radius:8px;padding:7px 9px;font-weight:850;font-size:11px}.pc-note{font-size:12px;color:#6f767d;line-height:1.4}@media(max-width:620px){.pc-grid{grid-template-columns:1fr}.pc-panel{padding:12px}.pc-actions button{flex:1 1 45%}}`;
 document.head.appendChild(style);
 const toolbar=$('.toolbar');if(!toolbar)return;
 const btn=document.createElement('button');btn.className='pc-launch';btn.id='playerCardBtn';btn.textContent='Create Player Card';toolbar.appendChild(btn);
 const modal=document.createElement('div');modal.id='playerCardModal';modal.className='pc-modal hidden';modal.innerHTML=`<div class="pc-panel"><div class="pc-head"><div><h2>Player Card</h2><div class="pc-note">Choose any game or season-to-date totals, then share one vintage front + back card.</div></div><button class="pc-close" id="pcClose">×</button></div><div class="pc-grid"><label class="pc-field">Player<select id="pcPlayer"></select></label><label class="pc-field">Stats to share<select id="pcScope"></select></label><label class="pc-field">Positions<input id="pcPosition" placeholder="QB • DE"></label><label class="pc-field">Action photo<input id="pcPhoto" type="file" accept="image/*"></label><label class="pc-field">Headshot<input id="pcHeadshot" type="file" accept="image/*"></label></div><div class="pc-note" style="margin-top:10px"><b>Crop photos directly on the card:</b> drag to reposition and pinch to zoom. The action photo and headshot crop independently.</div><div class="pc-reset-row"><button id="pcResetAction" type="button">Reset action crop</button><button id="pcResetHead" type="button">Reset headshot crop</button></div><div class="pc-actions"><button class="pc-primary" id="pcBuild">Build Card</button><button class="pc-secondary" id="pcShare" disabled>Share</button><button id="pcSave" disabled>Save Image</button></div><div class="pc-canvas-wrap"><div class="pc-stage"><canvas id="pcCanvas" width="1080" height="2520"></canvas><div class="pc-touch pc-touch-action" id="pcActionTouch"><span>Drag • pinch</span></div><div class="pc-touch pc-touch-head" id="pcHeadTouch"><span>Drag • pinch</span></div></div></div></div>`;document.body.appendChild(modal);
 btn.onclick=async()=>{modal.classList.remove('hidden');await loadData();populate();await useProfile();build()};$('#pcClose').onclick=()=>modal.classList.add('hidden');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});
 $('#pcPhoto').onchange=async e=>{actionPhoto=e.target.files?.[0]?await fileImage(e.target.files[0]):actionPhoto;actionCrop={scale:1,x:0,y:0};build()};$('#pcHeadshot').onchange=async e=>{headshot=e.target.files?.[0]?await fileImage(e.target.files[0]):headshot;headCrop={scale:1,x:0,y:0};build()};
 $('#pcPlayer').onchange=async()=>{await useProfile();build()};$('#pcScope').onchange=build;$('#pcPosition').oninput=debounce(build,180);$('#pcBuild').onclick=build;$('#pcShare').onclick=share;$('#pcSave').onclick=save;
 $('#pcResetAction').onclick=()=>{actionCrop={scale:1,x:0,y:0};build()};$('#pcResetHead').onclick=()=>{headCrop={scale:1,x:0,y:0};build()};
 bindGesture($('#pcActionTouch'),()=>actionCrop,v=>actionCrop=v);bindGesture($('#pcHeadTouch'),()=>headCrop,v=>headCrop=v);
}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
function bindGesture(el,getCrop,setCrop){const pts=new Map();let last=null,pinch=null;const dist=()=>{const a=[...pts.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)};const center=()=>{const a=[...pts.values()];return a.length<2?null:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}};el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1)last={x:e.clientX,y:e.clientY};else if(pts.size===2)pinch={distance:dist(),scale:Number(getCrop().scale||1),center:center()};});el.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId))return;e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=el.getBoundingClientRect(),c={...getCrop()};if(pts.size>=2&&pinch){const d=dist(),ctr=center();if(pinch.distance>0)c.scale=clamp(pinch.scale*(d/pinch.distance),1,4);if(ctr&&pinch.center){c.x=clamp(Number(c.x||0)+(ctr.x-pinch.center.x)/(Math.max(1,r.width)*.32),-2,2);c.y=clamp(Number(c.y||0)+(ctr.y-pinch.center.y)/(Math.max(1,r.height)*.32),-2,2);pinch.center=ctr}setCrop(c);build();return}if(pts.size===1&&last){c.x=clamp(Number(c.x||0)+(e.clientX-last.x)/(Math.max(1,r.width)*.32),-2,2);c.y=clamp(Number(c.y||0)+(e.clientY-last.y)/(Math.max(1,r.height)*.32),-2,2);last={x:e.clientX,y:e.clientY};setCrop(c);build()}});const end=e=>{pts.delete(e.pointerId);if(pts.size===1){const p=[...pts.values()][0];last={x:p.x,y:p.y};pinch=null}else if(!pts.size){last=null;pinch=null}};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('wheel',e=>{e.preventDefault();const c={...getCrop()};c.scale=clamp(Number(c.scale||1)*(e.deltaY<0?1.08:.92),1,4);setCrop(c);build()},{passive:false})}
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json()}
async function loadData(){if(viewer)return;viewer=await rpc('get_public_team_viewer',{p_token:token});try{profiles=await rpc('get_public_player_card_profiles',{p_token:token})}catch(e){profiles=[];console.warn('Player card profiles unavailable',e)}}
function sortedPlayers(){return [...(viewer?.players||[])].sort((a,b)=>Number(a.jersey||999)-Number(b.jersey||999)||String(a.name).localeCompare(String(b.name)))}
function profileFor(id){return profiles.find(p=>String(p.id)===String(id))||null}
function gameOptions(){return [...(viewer?.games||[])].sort((a,b)=>Number(b.week_number||0)-Number(a.week_number||0))}
function populate(){const ps=sortedPlayers(),sel=$('#pcPlayer'),prior=sel.value;sel.innerHTML=ps.map(p=>`<option value="${esc(p.id)}">#${esc(p.jersey||'?')} ${esc(p.name||'Player')}</option>`).join('');if(ps.some(p=>String(p.id)===prior))sel.value=prior;const current=$('#gameSelect')?.value,scope=$('#pcScope'),priorScope=scope.value;scope.innerHTML=`<option value="season">Season to date</option>`+gameOptions().map(g=>`<option value="game:${g.id}">Week ${g.week_number||'?'} • ${esc(g.opponent_name||'Opponent')} • ${String(g.status||'').toUpperCase()}</option>`).join('');if(priorScope&&[...scope.options].some(o=>o.value===priorScope))scope.value=priorScope;else if(current&&[...scope.options].some(o=>o.value===`game:${current}`))scope.value=`game:${current}`;else if(gameOptions()[0])scope.value=`game:${gameOptions()[0].id}`}
async function useProfile(){const p=profileFor($('#pcPlayer').value);actionPhoto=p?.action_photo_data?await loadImage(p.action_photo_data):null;headshot=p?.headshot_data?await loadImage(p.headshot_data):(actionPhoto||null);actionCrop={scale:1,x:0,y:0,...(p?.action_photo_crop||{})};headCrop={scale:1,x:0,y:0,...(p?.headshot_crop||{})};$('#pcPosition').value=[p?.primary_position,p?.secondary_position].filter(Boolean).join(' • ')}
function loadImage(src){return new Promise(res=>{if(!src)return res(null);const i=new Image();i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=()=>res(null);i.src=src})}
function fileImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>loadImage(r.result).then(res);r.onerror=rej;r.readAsDataURL(file)})}
function raw(p){return p?.event_data?.raw||p?.event_data||{}}
function has(r,x){return Array.isArray(r.extras)&&r.extras.includes(x)}
function selectedGames(){const v=$('#pcScope').value;if(v==='season')return gameOptions();const id=v.split(':')[1];return gameOptions().filter(g=>String(g.id)===id)}
function selectedPlays(){const ids=new Set(selectedGames().map(g=>g.id));return (viewer?.plays||[]).filter(p=>ids.has(p.game_id))}
function calcStats(playerId){let att=0,cmp=0,passY=0,passTd=0,int=0,rush=0,rushY=0,rushTd=0,tgt=0,rec=0,recY=0,recTd=0,tkl=0,tfl=0,sacks=0,defInt=0;for(const p of selectedPlays()){const r=raw(p),type=String(r.type||p.play_type||''),yards=Number(r.yards??p.yards??0),sub=String(r.sub||p.subtype||'');if(type==='Pass'){if(String(r.player)===String(playerId)){att++;if(sub==='Complete'){cmp++;passY+=yards;if(has(r,'TD'))passTd++}if(sub==='Intercepted')int++}if(String(r.player2)===String(playerId)){tgt++;if(sub==='Complete'){rec++;recY+=yards;if(has(r,'TD'))recTd++}}}if(type==='Rush'&&String(r.player)===String(playerId)){rush++;rushY+=yards;if(has(r,'TD'))rushTd++}if(type==='Defense'){const val=Number((r.defCredits||{})[playerId]||0);if(val){tkl+=val;if(r.tackleKind==='TFL')tfl+=val;if(r.tackleKind==='Sack')sacks+=val}if(String(r.interceptionPlayerId)===String(playerId))defInt++}}const groups=[];if(att)groups.push({title:'PASSING',metrics:[['CMP/ATT',`${cmp}/${att}`],['YDS',passY],['TD',passTd],['INT',int]]});if(rush)groups.push({title:'RUSHING',metrics:[['CAR',rush],['YDS',rushY],['AVG',rush?(rushY/rush).toFixed(1):'0.0'],['TD',rushTd]]});if(tgt||rec)groups.push({title:'RECEIVING',metrics:[['TGT',tgt],['REC',rec],['YDS',recY],['TD',recTd]]});if(tkl||tfl||sacks||defInt)groups.push({title:'DEFENSE',metrics:[['TKL',Number.isInteger(tkl)?tkl:tkl.toFixed(1)],['TFL',Number.isInteger(tfl)?tfl:tfl.toFixed(1)],['SACK',Number.isInteger(sacks)?sacks:sacks.toFixed(1)],['INT',defInt]]});return groups}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function cover(ctx,img,x,y,w,h,crop){if(!img)return;const base=Math.max(w/img.width,h/img.height),scale=base*Number(crop?.scale||1),dw=img.width*scale,dh=img.height*scale,dx=(w-dw)/2+Number(crop?.x||0)*w*.32,dy=(h-dh)/2+Number(crop?.y||0)*h*.32;ctx.drawImage(img,x+dx,y+dy,dw,dh)}
function fit(ctx,text,max,base,min=20){let size=base;while(size>min){ctx.font=`900 ${size}px Arial Black,Impact,sans-serif`;if(ctx.measureText(text).width<=max)break;size-=2}return size}
function slant(ctx,x,y,w,h,fill,cut=38){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.lineTo(x+w-cut,y+h);ctx.lineTo(x,y+h);ctx.closePath();ctx.fillStyle=fill;ctx.fill()}
function seed(i){const x=Math.sin(i*927.17)*43758.5453;return x-Math.floor(x)}
function distress(ctx,x,y,w,h,dark,light){ctx.save();rounded(ctx,x,y,w,h,28);ctx.clip();for(let i=0;i<240;i++){ctx.globalAlpha=.035+seed(i+9)*.05;ctx.fillStyle=i%3?dark:light;ctx.beginPath();ctx.arc(x+seed(i)*w,y+seed(i+311)*h,.5+seed(i+711)*2.5,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.globalAlpha=1}
function paw(ctx,x,y,s,fill){ctx.save();ctx.fillStyle=fill;ctx.beginPath();ctx.ellipse(x,y+s*.18,s*.34,s*.27,0,0,Math.PI*2);ctx.fill();[[-.3,-.12],[-.1,-.28],[.14,-.28],[.34,-.08]].forEach(([dx,dy],i)=>{ctx.beginPath();ctx.ellipse(x+dx*s,y+dy*s,s*.13,s*.17,(i-1.5)*.16,0,Math.PI*2);ctx.fill()});ctx.restore()}
function badge(ctx,x,y,w,h,orange,ink,cream,text){ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(-.15);ctx.fillStyle=cream;ctx.strokeStyle=ink;ctx.lineWidth=7;ctx.beginPath();ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=ink;ctx.textAlign='center';ctx.font='900 21px Arial Black,Impact,sans-serif';ctx.fillText(text==='SEASON'?'SEASON':'WEEK',0,-8);ctx.font='900 47px Arial Black,Impact,sans-serif';ctx.fillText(text==='SEASON'?'STD':text,0,40);ctx.restore();ctx.textAlign='left'}
function drawStatGroups(ctx,groups,x,y,w,ink,orange,cream){if(!groups.length){ctx.fillStyle=ink;ctx.font='900 26px Arial Black,Impact,sans-serif';ctx.fillText('NO PLAYER STATS',x,y+36);return y+55}const gap=16;let cy=y;groups.forEach(g=>{ctx.fillStyle=ink;ctx.fillRect(x,cy,w,38);ctx.fillStyle='#fff';ctx.font='900 19px Arial Black,Impact,sans-serif';ctx.fillText(g.title,x+12,cy+27);cy+=38;const cellW=w/g.metrics.length;ctx.fillStyle=cream;ctx.fillRect(x,cy,w,76);ctx.strokeStyle=ink;ctx.lineWidth=2;ctx.strokeRect(x,cy,w,76);g.metrics.forEach(([k,v],i)=>{if(i){ctx.beginPath();ctx.moveTo(x+i*cellW,cy);ctx.lineTo(x+i*cellW,cy+76);ctx.stroke()}ctx.textAlign='center';ctx.fillStyle=orange;ctx.font='900 15px Arial Black,Impact,sans-serif';ctx.fillText(String(k),x+i*cellW+cellW/2,cy+23);ctx.fillStyle=ink;ctx.font='900 24px Arial Black,Impact,sans-serif';ctx.fillText(String(v),x+i*cellW+cellW/2,cy+58)});ctx.textAlign='left';cy+=76+gap});return cy}
async function build(){const canvas=$('#pcCanvas');if(!canvas||!viewer)return;const ctx=canvas.getContext('2d'),W=1080,H=2520,X=40,CW=1000,CH=1200,FY=30,BY=1290,orange='#f15a2a',ink='#111111',cream='#f2ead8';const p=sortedPlayers().find(x=>String(x.id)===$('#pcPlayer').value)||sortedPlayers()[0];if(!p)return;const name=String(p.name||'PLAYER').toUpperCase(),num=String(p.jersey||'—'),positions=($('#pcPosition').value.trim()||'PLAYER').toUpperCase(),team=String(viewer.team?.name||'TEAM').toUpperCase(),games=selectedGames(),season=$('#pcScope').value==='season',g=games[0],week=season?'SEASON':String(g?.week_number||'—'),opp=season?'SEASON TO DATE':String(g?.opponent_name||'OPPONENT').toUpperCase(),ourScore=season?'':Number(g?.team_score||0),oppScore=season?'':Number(g?.opponent_score||0),groups=calcStats(p.id);
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#282828';ctx.fillRect(0,0,W,H);
 ctx.save();rounded(ctx,X,FY,CW,CH,32);ctx.clip();ctx.fillStyle=cream;ctx.fillRect(X,FY,CW,CH);ctx.fillStyle=orange;ctx.fillRect(X+24,FY+24,CW-48,13);const px=X+68,py=FY+55,pw=CW-112,ph=CH-124;ctx.fillStyle='#ccc4b4';ctx.fillRect(px,py,pw,ph);if(actionPhoto)cover(ctx,actionPhoto,px,py,pw,ph,actionCrop);slant(ctx,X+24,FY+40,355,118,ink,55);ctx.fillStyle='#fff';ctx.font=`italic 900 ${fit(ctx,name,270,66,38)}px Arial Black,Impact,sans-serif`;ctx.fillText(name,X+55,FY+118);ctx.fillStyle=orange;ctx.beginPath();ctx.moveTo(X+340,FY+40);ctx.lineTo(X+380,FY+40);ctx.lineTo(X+326,FY+158);ctx.lineTo(X+292,FY+158);ctx.closePath();ctx.fill();slant(ctx,X+25,FY+310,245,150,orange,35);ctx.fillStyle=ink;ctx.font='900 76px Arial Black,Impact,sans-serif';ctx.fillText(`#${num}`,X+47,FY+409);slant(ctx,X+25,FY+476,245,88,ink,34);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,positions,180,36,21)}px Arial Black,Impact,sans-serif`;ctx.fillText(positions,X+47,FY+533);badge(ctx,X+744,FY+50,210,126,orange,ink,cream,week);ctx.save();ctx.translate(X+920,FY+515);ctx.rotate(-.56);for(let i=0;i<4;i++){ctx.fillStyle=i%2?ink:orange;ctx.fillRect(0,i*48,58,28)}ctx.restore();paw(ctx,X+105,FY+1090,88,ink);slant(ctx,X+210,FY+1081,690,93,ink,-35);ctx.fillStyle='#fff';ctx.font=`italic 900 ${fit(ctx,team,590,47,26)}px Arial Black,Impact,sans-serif`;ctx.fillText(team,X+255,FY+1144);ctx.fillStyle=orange;ctx.fillRect(X+235,FY+1160,610,9);distress(ctx,X,FY,CW,CH,ink,cream);ctx.restore();ctx.strokeStyle='#b8ab95';ctx.lineWidth=5;rounded(ctx,X,FY,CW,CH,32);ctx.stroke();
 ctx.save();rounded(ctx,X,BY,CW,CH,32);ctx.clip();ctx.fillStyle=cream;ctx.fillRect(X,BY,CW,CH);ctx.fillStyle=ink;ctx.fillRect(X+24,BY+24,CW-48,12);const hx=X+58,hy=BY+55,hw=310,hh=310;ctx.fillStyle=ink;ctx.fillRect(hx-7,hy-7,hw+14,hh+14);if(headshot)cover(ctx,headshot,hx,hy,hw,hh,headCrop);else if(actionPhoto)cover(ctx,actionPhoto,hx,hy,hw,hh,headCrop);const rx=X+400,rw=570;ctx.fillStyle=orange;ctx.fillRect(rx,hy,rw,112);ctx.fillStyle=ink;ctx.font=`900 ${fit(ctx,name,360,73,40)}px Arial Black,Impact,sans-serif`;ctx.fillText(name,rx+18,hy+81);ctx.font='900 57px Arial Black,Impact,sans-serif';ctx.fillText(`#${num}`,X+862,hy+80);ctx.fillStyle=ink;ctx.fillRect(rx,hy+120,rw,64);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,positions,500,35,22)}px Arial Black,Impact,sans-serif`;ctx.fillText(positions,rx+18,hy+165);ctx.fillStyle=orange;ctx.fillRect(rx,hy+194,rw,64);ctx.fillStyle=ink;ctx.font=`900 ${fit(ctx,team,500,33,20)}px Arial Black,Impact,sans-serif`;ctx.fillText(team,rx+18,hy+238);
 const sy=BY+395;if(season){ctx.fillStyle=orange;ctx.fillRect(X+58,sy,CW-116,58);ctx.fillStyle=ink;ctx.font='900 30px Arial Black,Impact,sans-serif';ctx.fillText('SEASON TO DATE',X+78,sy+40);ctx.textAlign='right';const finals=games.filter(q=>q.status==='final'),wins=finals.filter(q=>Number(q.team_score)>Number(q.opponent_score)).length,losses=finals.filter(q=>Number(q.team_score)<Number(q.opponent_score)).length;ctx.fillText(`${finals.length} GAMES • ${wins}-${losses}`,X+948,sy+40);ctx.textAlign='left'}else{ctx.fillStyle=orange;ctx.fillRect(X+58,sy,CW-116,58);ctx.fillStyle=ink;ctx.font='900 31px Arial Black,Impact,sans-serif';ctx.fillText(team,X+78,sy+40);ctx.textAlign='right';ctx.fillText(String(ourScore),X+948,sy+40);ctx.textAlign='left';ctx.fillStyle=ink;ctx.fillRect(X+58,sy+62,CW-116,58);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,opp,700,30,20)}px Arial Black,Impact,sans-serif`;ctx.fillText(opp,X+78,sy+102);ctx.textAlign='right';ctx.fillText(String(oppScore),X+948,sy+102);ctx.textAlign='left'}
 const statsBottom=drawStatGroups(ctx,groups,X+80,BY+545,CW-160,ink,orange,cream);const by=Math.min(BY+1030,Math.max(BY+930,statsBottom+12));ctx.fillStyle=ink;ctx.font='900 29px Arial Black,Impact,sans-serif';ctx.fillText('BLEACHER',X+75,by+25);ctx.font='900 41px Arial Black,Impact,sans-serif';ctx.fillText('STATS',X+112,by+66);ctx.fillStyle=orange;ctx.fillRect(X+110,by+76,202,28);ctx.fillStyle=ink;ctx.font='900 14px Arial Black,Impact,sans-serif';ctx.fillText('GRIDIRON EDITION',X+128,by+96);ctx.font='900 16px Arial Black,Impact,sans-serif';ctx.fillText(season?'PLAYER CARD • SEASON':'PLAYER CARD • WEEK '+week,X+420,by+26);ctx.fillStyle=orange;ctx.fillRect(X+420,by+39,230,7);ctx.fillStyle=ink;ctx.font='italic 700 24px "Comic Sans MS","Marker Felt",cursive';ctx.fillText('SOME KIDS',X+420,by+84);ctx.fillText('PLAY THE GAME.',X+420,by+112);ctx.fillText('SOME DADS',X+420,by+140);ctx.fillText('KEEP THE STATS.',X+420,by+168);paw(ctx,X+880,by+80,80,orange);ctx.textAlign='center';ctx.font='900 16px Arial Black,Impact,sans-serif';ctx.fillText(team,X+880,by+180);ctx.textAlign='left';distress(ctx,X,BY,CW,CH,ink,cream);ctx.restore();ctx.strokeStyle='#b8ab95';ctx.lineWidth=5;rounded(ctx,X,BY,CW,CH,32);ctx.stroke();
 await new Promise(r=>canvas.toBlob(b=>{lastBlob=b;lastName=`${String(p.name||'player').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${season?'season':`week-${week}`}-card.png`;r()},'image/png',.96));$('#pcShare').disabled=!lastBlob;$('#pcSave').disabled=!lastBlob}
async function share(){if(!lastBlob)return;const f=new File([lastBlob],lastName,{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f]});return}}catch(e){if(e?.name==='AbortError')return}save()}
function save(){if(!lastBlob)return;const u=URL.createObjectURL(lastBlob),a=document.createElement('a');a.href=u;a.download=lastName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
