(()=>{
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const TEMPLATE='./assets/player-cards/gridiron/front-template-master.png';
const token=new URLSearchParams(location.search).get('teamInvite')||'';
let viewer=null,profiles=[],templateImg=null,actionPhoto=null,headshot=null,lastBlob=null,lastName='player-card.png';
let actionCrop={scale:1,x:0,y:0},headCrop={scale:1,x:0,y:0};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadImage(src){return new Promise(res=>{if(!src)return res(null);const i=new Image();i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=()=>res(null);i.src=src})}
function fileImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>loadImage(r.result).then(res);r.onerror=rej;r.readAsDataURL(file)})}
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadData(){if(!viewer)viewer=await rpc('get_public_team_viewer',{p_token:token});if(!profiles.length){try{profiles=await rpc('get_public_player_card_profiles',{p_token:token})}catch(_){profiles=[]}}if(!templateImg)templateImg=await loadImage(TEMPLATE+'?release=4.6.19')}
function sortedPlayers(){return [...(viewer?.players||[])].sort((a,b)=>Number(a.jersey||999)-Number(b.jersey||999)||String(a.name||'').localeCompare(String(b.name||'')))}
function games(){return [...(viewer?.games||[])].sort((a,b)=>Number(b.week_number||0)-Number(a.week_number||0))}
function profileFor(id){return profiles.find(p=>String(p.id)===String(id))||null}
function selectedGames(){const v=$('#pcScope').value;if(v==='season')return games();const id=v.split(':')[1];return games().filter(g=>String(g.id)===id)}
function raw(p){return p?.event_data?.raw||p?.event_data||{}}
function has(r,x){return Array.isArray(r.extras)&&r.extras.includes(x)}
function selectedPlays(){const ids=new Set(selectedGames().map(g=>g.id));return (viewer?.plays||[]).filter(p=>ids.has(p.game_id))}
function calcStats(playerId){let att=0,cmp=0,passY=0,passTd=0,rush=0,rushY=0,rushTd=0,tkl=0,tfl=0,sacks=0,defInt=0;for(const p of selectedPlays()){const r=raw(p),type=String(r.type||p.play_type||''),yards=Number(r.yards??p.yards??0),sub=String(r.sub||p.subtype||'');if(type==='Pass'&&String(r.player)===String(playerId)){att++;if(sub==='Complete'){cmp++;passY+=yards;if(has(r,'TD'))passTd++}}if(type==='Rush'&&String(r.player)===String(playerId)){rush++;rushY+=yards;if(has(r,'TD'))rushTd++}if(type==='Defense'){const v=Number((r.defCredits||{})[playerId]||0);if(v){tkl+=v;if(r.tackleKind==='TFL')tfl+=v;if(r.tackleKind==='Sack')sacks+=v}if(String(r.interceptionPlayerId)===String(playerId))defInt++}}const rows=[];if(att)rows.push(['PASSING',`${cmp}/${att}`],['PASS YDS',passY],['PASS TD',passTd]);if(rush)rows.push(['RUSHES',rush],['RUSH YDS',rushY],['RUSH TD',rushTd]);if(tfl)rows.push(['TFL',fmt(tfl)]);if(sacks)rows.push(['SACKS',fmt(sacks)]);if(defInt)rows.push(['INT',defInt]);if(tkl&&!tfl&&!sacks)rows.push(['TACKLES',fmt(tkl)]);const totalY=passY+rushY,totalTd=passTd+rushTd;if(totalY)rows.push(['TOTAL YDS',totalY]);if(totalTd)rows.push(['TOTAL TD',totalTd]);return rows.slice(0,10)}
function fmt(v){return Number.isInteger(v)?v:v.toFixed(1)}
function cover(ctx,img,x,y,w,h,crop){if(!img)return;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const base=Math.max(w/img.width,h/img.height),scale=base*Number(crop?.scale||1),dw=img.width*scale,dh=img.height*scale,dx=(w-dw)/2+Number(crop?.x||0)*w*.32,dy=(h-dh)/2+Number(crop?.y||0)*h*.32;ctx.drawImage(img,x+dx,y+dy,dw,dh);ctx.restore()}
function fit(ctx,text,max,base,min=18){let size=base;while(size>min){ctx.font=`900 ${size}px Arial Black,Impact,sans-serif`;if(ctx.measureText(text).width<=max)break;size-=2}return size}
function inject(){
 const style=document.createElement('style');style.textContent=`.pc-launch{border:0;background:var(--p);color:var(--p-ink);border-radius:10px;padding:10px 12px;font-weight:900;cursor:pointer}.pc-modal{position:fixed;inset:0;background:#0009;z-index:9999;display:flex;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.pc-modal.hidden{display:none}.pc-panel{width:min(780px,100%);background:#fff;color:#17202a;border-radius:18px;padding:16px}.pc-head{display:flex;justify-content:space-between;align-items:center}.pc-close{border:0;border-radius:50%;width:36px;height:36px;font-size:20px;font-weight:900}.pc-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.pc-field{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:800}.pc-field select,.pc-field input{padding:10px;border:1px solid #d6d9dc;border-radius:10px;background:#fff}.pc-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pc-actions button{border:0;border-radius:10px;padding:11px 14px;font-weight:900}.pc-primary{background:var(--p);color:var(--p-ink)}.pc-secondary{background:var(--a);color:var(--a-ink)}.pc-canvas-wrap{background:#222;border-radius:14px;padding:10px;overflow:auto}.pc-stage{position:relative;width:min(100%,360px);margin:auto}.pc-stage canvas{display:block;width:100%;height:auto;border-radius:10px}.pc-note{font-size:12px;color:#6f767d}.pc-reset-row{display:flex;gap:8px;margin-top:8px}.pc-reset-row button{border:0;border-radius:8px;padding:7px 9px;font-weight:800}@media(max-width:620px){.pc-grid{grid-template-columns:1fr}.pc-actions button{flex:1 1 45%}}`;
 document.head.appendChild(style);const toolbar=$('.toolbar');if(!toolbar)return;const btn=document.createElement('button');btn.className='pc-launch';btn.textContent='Create Player Card';toolbar.appendChild(btn);const modal=document.createElement('div');modal.className='pc-modal hidden';modal.innerHTML=`<div class="pc-panel"><div class="pc-head"><div><h2 style="margin:0">Player Card</h2><div class="pc-note">Uses the approved Gridiron master template.</div></div><button id="pcClose" class="pc-close">×</button></div><div class="pc-grid"><label class="pc-field">Player<select id="pcPlayer"></select></label><label class="pc-field">Stats to share<select id="pcScope"></select></label><label class="pc-field">Positions<input id="pcPosition" placeholder="QB • DE"></label><label class="pc-field">Action photo<input id="pcPhoto" type="file" accept="image/*"></label><label class="pc-field">Headshot<input id="pcHeadshot" type="file" accept="image/*"></label></div><div class="pc-reset-row"><button id="pcResetAction">Reset action crop</button><button id="pcResetHead">Reset headshot crop</button></div><div class="pc-actions"><button id="pcBuild" class="pc-primary">Build Card</button><button id="pcShare" class="pc-secondary" disabled>Share</button><button id="pcSave" disabled>Save Image</button></div><div class="pc-canvas-wrap"><div class="pc-stage"><canvas id="pcCanvas" width="1080" height="2520"></canvas></div></div></div>`;document.body.appendChild(modal);
 btn.onclick=async()=>{modal.classList.remove('hidden');await loadData();populate();await useProfile();build()};$('#pcClose').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};$('#pcPhoto').onchange=async e=>{actionPhoto=e.target.files?.[0]?await fileImage(e.target.files[0]):actionPhoto;actionCrop={scale:1,x:0,y:0};build()};$('#pcHeadshot').onchange=async e=>{headshot=e.target.files?.[0]?await fileImage(e.target.files[0]):headshot;headCrop={scale:1,x:0,y:0};build()};$('#pcPlayer').onchange=async()=>{await useProfile();build()};$('#pcScope').onchange=build;$('#pcPosition').oninput=build;$('#pcBuild').onclick=build;$('#pcShare').onclick=share;$('#pcSave').onclick=save;$('#pcResetAction').onclick=()=>{actionCrop={scale:1,x:0,y:0};build()};$('#pcResetHead').onclick=()=>{headCrop={scale:1,x:0,y:0};build()};
}
function populate(){const ps=sortedPlayers(),sel=$('#pcPlayer');sel.innerHTML=ps.map(p=>`<option value="${esc(p.id)}">#${esc(p.jersey||'?')} ${esc(p.name||'Player')}</option>`).join('');const current=$('#gameSelect')?.value,scope=$('#pcScope');scope.innerHTML=`<option value="season">Season to date</option>`+games().map(g=>`<option value="game:${g.id}">Week ${g.week_number||'?'} • ${esc(g.opponent_name||'Opponent')}</option>`).join('');if(current&&[...scope.options].some(o=>o.value===`game:${current}`))scope.value=`game:${current}`}
async function useProfile(){const p=profileFor($('#pcPlayer').value);actionPhoto=p?.action_photo_data?await loadImage(p.action_photo_data):null;headshot=p?.headshot_data?await loadImage(p.headshot_data):(actionPhoto||null);actionCrop={scale:1,x:0,y:0,...(p?.action_photo_crop||{})};headCrop={scale:1,x:0,y:0,...(p?.headshot_crop||{})};$('#pcPosition').value=[p?.primary_position,p?.secondary_position].filter(Boolean).join(' • ')}
async function build(){const canvas=$('#pcCanvas');if(!canvas||!viewer)return;const ctx=canvas.getContext('2d'),W=1080,H=2520,X=40,FY=30,BY=1290,CW=1000,CH=1200;const p=sortedPlayers().find(x=>String(x.id)===$('#pcPlayer').value)||sortedPlayers()[0];if(!p)return;const season=$('#pcScope').value==='season',g=selectedGames()[0],week=season?'SEASON':String(g?.week_number||'—'),team=String(viewer.team?.name||'TEAM').toUpperCase(),opp=season?'SEASON TO DATE':String(g?.opponent_name||'OPPONENT').toUpperCase(),rows=calcStats(p.id),positions=($('#pcPosition').value.trim()||'PLAYER').toUpperCase();ctx.clearRect(0,0,W,H);ctx.fillStyle='#242424';ctx.fillRect(0,0,W,H);
 // FRONT: the approved GitHub PNG is now the actual visual template.
 ctx.save();ctx.beginPath();ctx.roundRect(X,FY,CW,CH,28);ctx.clip();ctx.fillStyle='#d7d0c4';ctx.fillRect(X,FY,CW,CH);if(actionPhoto)cover(ctx,actionPhoto,X,FY,CW,CH,actionCrop);if(templateImg)ctx.drawImage(templateImg,X,FY,CW,CH);ctx.restore();
 // BACK: dynamic player/game information remains generated from live stats.
 ctx.save();ctx.beginPath();ctx.roundRect(X,BY,CW,CH,28);ctx.clip();ctx.fillStyle='#f2ead8';ctx.fillRect(X,BY,CW,CH);ctx.fillStyle='#f15a2a';ctx.fillRect(X+24,BY+24,CW-48,12);const hx=X+58,hy=BY+62,hw=300,hh=300;ctx.fillStyle='#111';ctx.fillRect(hx-7,hy-7,hw+14,hh+14);if(headshot)cover(ctx,headshot,hx,hy,hw,hh,headCrop);else if(actionPhoto)cover(ctx,actionPhoto,hx,hy,hw,hh,headCrop);ctx.fillStyle='#f15a2a';ctx.fillRect(X+390,hy,590,112);ctx.fillStyle='#111';ctx.font=`900 ${fit(ctx,String(p.name||'PLAYER').toUpperCase(),360,72,40)}px Arial Black,Impact,sans-serif`;ctx.fillText(String(p.name||'PLAYER').toUpperCase(),X+410,hy+80);ctx.textAlign='right';ctx.font='900 60px Arial Black,Impact,sans-serif';ctx.fillText(`#${p.jersey||'—'}`,X+958,hy+80);ctx.textAlign='left';ctx.fillStyle='#111';ctx.fillRect(X+390,hy+122,590,64);ctx.fillStyle='#fff';ctx.font='900 34px Arial Black,Impact,sans-serif';ctx.fillText(positions,X+410,hy+166);ctx.fillStyle='#f15a2a';ctx.fillRect(X+390,hy+196,590,64);ctx.fillStyle='#111';ctx.font=`900 ${fit(ctx,team,520,34,22)}px Arial Black,Impact,sans-serif`;ctx.fillText(team,X+410,hy+240);const sy=BY+395;ctx.fillStyle='#f15a2a';ctx.fillRect(X+58,sy,CW-116,58);ctx.fillStyle='#111';ctx.font='900 30px Arial Black,Impact,sans-serif';ctx.fillText(team,X+78,sy+40);if(!season){ctx.textAlign='right';ctx.fillText(String(Number(g?.team_score||0)),X+945,sy+40);ctx.textAlign='left';ctx.fillStyle='#111';ctx.fillRect(X+58,sy+62,CW-116,58);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,opp,700,29,20)}px Arial Black,Impact,sans-serif`;ctx.fillText(opp,X+78,sy+101);ctx.textAlign='right';ctx.fillText(String(Number(g?.opponent_score||0)),X+945,sy+101);ctx.textAlign='left'}const tx=X+86,ty=BY+535,tw=CW-172,rh=46,shown=rows.length?rows:[['PLAYER STATS','—']];ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.strokeRect(tx,ty,tw,rh*shown.length);shown.forEach(([k,v],i)=>{const yy=ty+i*rh;if(i){ctx.beginPath();ctx.moveTo(tx,yy);ctx.lineTo(tx+tw,yy);ctx.stroke()}ctx.fillStyle='#111';ctx.font='900 22px Arial Black,Impact,sans-serif';ctx.fillText(String(k),tx+18,yy+32);ctx.textAlign='right';ctx.font='900 24px Arial Black,Impact,sans-serif';ctx.fillText(String(v),tx+tw-18,yy+32);ctx.textAlign='left'});ctx.fillStyle='#111';ctx.font='900 34px Arial Black,Impact,sans-serif';ctx.fillText('BLEACHER BUTT STATS',X+72,BY+1058);ctx.fillStyle='#f15a2a';ctx.fillRect(X+72,BY+1073,300,30);ctx.fillStyle='#111';ctx.font='900 14px Arial Black,Impact,sans-serif';ctx.fillText('GRIDIRON EDITION',X+92,BY+1095);ctx.font='italic 700 22px "Comic Sans MS","Marker Felt",cursive';ctx.fillText('SOME KIDS PLAY THE GAME.',X+430,BY+1050);ctx.fillText('SOME DADS KEEP THE STATS.',X+430,BY+1080);ctx.font='900 16px Arial Black,Impact,sans-serif';ctx.fillText(season?'PLAYER CARD • SEASON':'PLAYER CARD • WEEK '+week,X+430,BY+1120);ctx.restore();
 await new Promise(r=>canvas.toBlob(b=>{lastBlob=b;lastName=`${String(p.name||'player').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${season?'season':`week-${week}`}-card.png`;r()},'image/png',.96));$('#pcShare').disabled=!lastBlob;$('#pcSave').disabled=!lastBlob}
async function share(){if(!lastBlob)return;const f=new File([lastBlob],lastName,{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f]});return}}catch(e){if(e?.name==='AbortError')return}save()}function save(){if(!lastBlob)return;const u=URL.createObjectURL(lastBlob),a=document.createElement('a');a.href=u;a.download=lastName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();