(()=>{
const DATA_KEY='sidelineStatsData';
const PROFILE_KEY='sidelinePlayerCardProfiles';
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const SUPABASE_KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const $=s=>document.querySelector(s);
let activeId=null,draft=null;
function state(){try{return JSON.parse(localStorage.getItem(DATA_KEY)||'{}')}catch(_){return {}}}
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch(_){return {}}}
function saveProfiles(v){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(v));return true}catch(_){alert('This device is out of storage for player photos. Try a smaller photo.');return false}}
function playerById(id){return (state().roster||[]).find(p=>String(p.id)===String(id))||null}
function defaultProfile(p){return {primaryPosition:'',secondaryPosition:'',actionPhotoData:null,headshotData:null,actionCrop:{scale:1,x:0,y:0},headshotCrop:{scale:1,x:0,y:0},updatedAt:null}}
function getProfile(id){const p=playerById(id);return {...defaultProfile(p),...(profiles()[id]||{})}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addStyles(){const st=document.createElement('style');st.textContent=`
.pp-meta{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:5px}.pp-tag{font-size:11px;font-weight:900;padding:3px 7px;border-radius:999px;background:color-mix(in srgb,var(--p) 13%,white);border:1px solid color-mix(in srgb,var(--p) 30%,#ddd)}.pp-edit{border:0;border-radius:8px;padding:6px 9px;font-size:11px;font-weight:900;background:var(--p);color:var(--nav-text);cursor:pointer}.pp-modal{position:fixed;inset:0;background:#000a;z-index:12000;display:flex;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.pp-modal.hidden{display:none}.pp-card{width:min(680px,100%);background:#fff;border-radius:18px;padding:16px;color:#17202a}.pp-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.pp-head h2{margin:0}.pp-close{border:0;border-radius:50%;width:36px;height:36px;font-size:20px;font-weight:900}.pp-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pp-field{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:850}.pp-field input,.pp-field select{padding:10px;border:1px solid #d7dade;border-radius:10px}.pp-photo{margin-top:12px;border:1px solid #ddd;border-radius:14px;padding:12px}.pp-preview{width:100%;height:260px;background:#e8e4dc;border-radius:12px;overflow:hidden;position:relative;margin-top:8px}.pp-preview img{position:absolute;left:50%;top:50%;width:100%;height:100%;object-fit:cover;transform-origin:center}.pp-controls{display:grid;grid-template-columns:70px 1fr 42px;gap:8px;align-items:center;margin-top:8px;font-size:11px;font-weight:800}.pp-actions{display:flex;gap:8px;margin-top:14px}.pp-actions button{flex:1;border:0;border-radius:10px;padding:11px;font-weight:900}.pp-save{background:var(--p);color:var(--nav-text)}.pp-copy{background:#17202a;color:#fff}.pp-note{font-size:11px;color:#687078;margin-top:6px;line-height:1.4}@media(max-width:600px){.pp-grid{grid-template-columns:1fr}.pp-preview{height:220px}}
`;document.head.appendChild(st)}
function ensureModal(){if($('#playerProfileModal'))return;const m=document.createElement('div');m.id='playerProfileModal';m.className='pp-modal hidden';m.innerHTML=`<div class="pp-card"><div class="pp-head"><div><h2 id="ppTitle">Player Card Profile</h2><div class="pp-note">Set default positions and photos parents can use instantly.</div></div><button class="pp-close" id="ppClose">×</button></div><div class="pp-grid" style="margin-top:12px"><label class="pp-field">Primary position<input id="ppPrimary" maxlength="12" placeholder="QB"></label><label class="pp-field">Secondary position <span style="font-weight:500">(optional)</span><input id="ppSecondary" maxlength="12" placeholder="DE"></label></div><section class="pp-photo"><strong>Action photo</strong><input id="ppActionFile" type="file" accept="image/*" style="display:block;margin-top:7px"><div class="pp-preview" id="ppActionPreview"></div><div class="pp-controls"><span>Zoom</span><input id="ppActionScale" type="range" min="1" max="3" step="0.01"><span id="ppActionScaleVal"></span><span>Left / Right</span><input id="ppActionX" type="range" min="-1" max="1" step="0.01"><span></span><span>Up / Down</span><input id="ppActionY" type="range" min="-1" max="1" step="0.01"><span></span></div></section><section class="pp-photo"><strong>Headshot</strong><div class="pp-note">Use a separate headshot, or tap “Use action photo” and crop it differently.</div><input id="ppHeadFile" type="file" accept="image/*" style="display:block;margin-top:7px"><button class="pp-copy" id="ppUseAction" type="button" style="border:0;border-radius:8px;padding:7px 9px;margin-top:7px;font-weight:850">Use action photo</button><div class="pp-preview" id="ppHeadPreview"></div><div class="pp-controls"><span>Zoom</span><input id="ppHeadScale" type="range" min="1" max="3" step="0.01"><span id="ppHeadScaleVal"></span><span>Left / Right</span><input id="ppHeadX" type="range" min="-1" max="1" step="0.01"><span></span><span>Up / Down</span><input id="ppHeadY" type="range" min="-1" max="1" step="0.01"><span></span></div></section><div class="pp-actions"><button class="pp-save" id="ppSave">Save Player Profile</button></div></div>`;document.body.appendChild(m);
 $('#ppClose').onclick=()=>m.classList.add('hidden');m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')});$('#ppSave').onclick=save;
 $('#ppUseAction').onclick=()=>{if(draft?.actionPhotoData){draft.headshotData=draft.actionPhotoData;draft.headshotCrop={scale:1,x:0,y:0};syncControls();renderPreviews()}};
 bindPhoto('#ppActionFile','actionPhotoData');bindPhoto('#ppHeadFile','headshotData');
 [['#ppActionScale','actionCrop','scale'],['#ppActionX','actionCrop','x'],['#ppActionY','actionCrop','y'],['#ppHeadScale','headshotCrop','scale'],['#ppHeadX','headshotCrop','x'],['#ppHeadY','headshotCrop','y']].forEach(([sel,obj,key])=>$(sel).addEventListener('input',e=>{draft[obj][key]=Number(e.target.value);renderPreviews();syncLabels()}));
}
function bindPhoto(sel,key){$(sel).addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;draft[key]=await compress(f);const crop=key==='actionPhotoData'?'actionCrop':'headshotCrop';draft[crop]={scale:1,x:0,y:0};syncControls();renderPreviews()})}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1400,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.84))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function transform(c){const scale=Number(c?.scale||1),x=Number(c?.x||0)*35,y=Number(c?.y||0)*35;return `translate(calc(-50% + ${x}%),calc(-50% + ${y}%)) scale(${scale})`}
function preview(el,data,crop){el.innerHTML=data?`<img src="${data}" alt="Photo preview">`:'<div style="display:grid;place-items:center;height:100%;color:#777;font-weight:800">No photo yet</div>';const img=el.querySelector('img');if(img)img.style.transform=transform(crop)}
function renderPreviews(){preview($('#ppActionPreview'),draft.actionPhotoData,draft.actionCrop);preview($('#ppHeadPreview'),draft.headshotData,draft.headshotCrop)}
function syncLabels(){$('#ppActionScaleVal').textContent=`${Number(draft.actionCrop.scale).toFixed(1)}×`;$('#ppHeadScaleVal').textContent=`${Number(draft.headshotCrop.scale).toFixed(1)}×`}
function syncControls(){[['#ppActionScale',draft.actionCrop.scale],['#ppActionX',draft.actionCrop.x],['#ppActionY',draft.actionCrop.y],['#ppHeadScale',draft.headshotCrop.scale],['#ppHeadX',draft.headshotCrop.x],['#ppHeadY',draft.headshotCrop.y]].forEach(([s,v])=>$(s).value=v??0);syncLabels()}
function open(id){const p=playerById(id);if(!p)return;activeId=id;draft=JSON.parse(JSON.stringify(getProfile(id)));$('#ppTitle').textContent=`#${p.jersey} ${p.name}`;$('#ppPrimary').value=draft.primaryPosition||'';$('#ppSecondary').value=draft.secondaryPosition||'';syncControls();renderPreviews();$('#playerProfileModal').classList.remove('hidden')}
async function save(){if(!activeId)return;draft.primaryPosition=$('#ppPrimary').value.trim().toUpperCase();draft.secondaryPosition=$('#ppSecondary').value.trim().toUpperCase();draft.updatedAt=new Date().toISOString();const all=profiles();all[activeId]=draft;if(!saveProfiles(all))return;await syncCloud(activeId,draft);$('#playerProfileModal').classList.add('hidden');enhanceRoster();}
async function syncCloud(localId,p){try{const s=state(),cloudId=s.cloud?.playerIds?.[localId];if(!cloudId||!window.supabase?.createClient)return;const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session}}=await sb.auth.getSession();if(!session)return;const {error}=await sb.from('players').update({primary_position:p.primaryPosition||null,secondary_position:p.secondaryPosition||null,action_photo_data:p.actionPhotoData||null,headshot_data:p.headshotData||null,action_photo_crop:p.actionCrop||{scale:1,x:0,y:0},headshot_crop:p.headshotCrop||{scale:1,x:0,y:0}}).eq('id',cloudId);if(error)throw error}catch(e){console.warn('Player card profile cloud sync skipped',e);alert('Saved on this device. Cloud profile sync will retry after the database update is available.') }}
function enhanceRoster(){const s=state(),list=$('#rosterList');if(!list||!(s.roster||[]).length)return;const rows=[...list.querySelectorAll('.player')],sorted=[...(s.roster||[])].sort((a,b)=>Number(a.jersey)-Number(b.jersey));rows.forEach((row,i)=>{const p=sorted[i];if(!p)return;row.dataset.playerId=p.id;let meta=row.querySelector('.pp-meta');if(!meta){meta=document.createElement('div');meta.className='pp-meta';row.firstElementChild?.appendChild(meta)}const prof=getProfile(p.id),positions=[prof.primaryPosition,prof.secondaryPosition].filter(Boolean).join(' • ');meta.innerHTML=`${positions?`<span class="pp-tag">${esc(positions)}</span>`:''}${prof.actionPhotoData?'<span class="pp-tag">📷 Action</span>':''}${prof.headshotData?'<span class="pp-tag">🙂 Headshot</span>':''}<button class="pp-edit" type="button">Card Profile</button>`;meta.querySelector('.pp-edit').onclick=e=>{e.stopPropagation();open(p.id)}})}
function watch(){const list=$('#rosterList');if(!list)return;new MutationObserver(()=>setTimeout(enhanceRoster,0)).observe(list,{childList:true,subtree:true});enhanceRoster()}
function init(){addStyles();ensureModal();watch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
