(()=>{
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const token=new URLSearchParams(location.search).get('teamInvite')||'';
let viewer=null,profiles=[],actionPhoto=null,headshot=null,lastBlob=null,lastName='player-card.png';
let actionCrop={scale:1,x:0,y:0},headCrop={scale:1,x:0,y:0};
const $=s=>document.querySelector(s),clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function inject(){
 const style=document.createElement('style');style.textContent=`.pc-launch{border:0;background:var(--p);color:var(--p-ink);border-radius:10px;padding:10px 12px;font-weight:900;cursor:pointer}.pc-modal{position:fixed;inset:0;background:#0009;z-index:9999;display:flex;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.pc-modal.hidden{display:none}.pc-panel{width:min(780px,100%);background:#fff;color:#17202a;border-radius:18px;padding:16px;box-shadow:0 20px 60px #0006}.pc-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.pc-head h2{margin:0;font-size:22px}.pc-close{border:0;background:#eceff1;border-radius:999px;width:36px;height:36px;font-size:20px;font-weight:900}.pc-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.pc-field{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:800}.pc-field select,.pc-field input{padding:10px;border:1px solid #d6d9dc;border-radius:10px;background:#fff;font:inherit}.pc-actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pc-actions button{border:0;border-radius:10px;padding:11px 14px;font-weight:900}.pc-primary{background:var(--p);color:var(--p-ink)}.pc-secondary{background:var(--a);color:var(--a-ink)}.pc-canvas-wrap{background:#242424;border-radius:14px;padding:10px;overflow:auto}.pc-stage{position:relative;width:min(100%,360px);margin:auto}.pc-stage canvas{display:block;width:100%;height:auto;border-radius:10px;box-shadow:0 4px 18px #0005}.pc-touch{position:absolute;touch-action:none;user-select:none;cursor:grab}.pc-touch-action{left:7.3%;top:2.2%;width:82.2%;height:45.8%}.pc-touch-head{left:9.1%;top:53.7%;width:28.7%;height:12.3%}.pc-reset-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.pc-reset-row button{border:0;background:#eceff1;color:#17202a;border-radius:8px;padding:7px 9px;font-weight:850;font-size:11px}.pc-note{font-size:12px;color:#6f767d;line-height:1.4}@media(max-width:620px){.pc-grid{grid-template-columns:1fr}.pc-panel{padding:12px}.pc-actions button{flex:1 1 45%}}`;
 document.head.appendChild(style);const toolbar=$('.toolbar');if(!toolbar)return;const btn=document.createElement('button');btn.className='pc-launch';btn.textContent='Create Player Card';toolbar.appendChild(btn);
 const modal=document.createElement('div');modal.className='pc-modal hidden';modal.innerHTML=`<div class="pc-panel"><div class="pc-head"><div><h2>Player Card</h2><div class="pc-note">Front + back styled to match the approved vintage card.</div></div><button class="pc-close" id="pcClose">×</button></div><div class="pc-grid"><label class="pc-field">Player<select id="pcPlayer"></select></label><label class="pc-field">Stats to share<select id="pcScope"></select></label><label class="pc-field">Positions<input id="pcPosition" placeholder="QB • DE"></label><label class="pc-field">Action photo<input id="pcPhoto" type="file" accept="image/*"></label><label class="pc-field">Headshot<input id="pcHeadshot" type="file" accept="image/*"></label></div><div class="pc-note" style="margin-top:10px"><b>Crop photos on the card:</b> drag to reposition and pinch to zoom.</div><div class="pc-reset-row"><button id="pcResetAction">Reset action crop</button><button id="pcResetHead">Reset headshot crop</button></div><div class="pc-actions"><button class="pc-primary" id="pcBuild">Build Card</button><button class="pc-secondary" id="pcShare" disabled>Share</button><button id="pcSave" disabled>Save Image</button></div><div class="pc-canvas-wrap"><div class="pc-stage"><canvas id="pcCanvas" width="1080" height="2520"></canvas><div class="pc-touch pc-touch-action" id="pcActionTouch"></div><div class="pc-touch pc-touch-head" id="pcHeadTouch"></div></div></div></div>`;document.body.appendChild(modal);
 btn.onclick=async()=>{modal.classList.remove('hidden');await loadData();populate();await useProfile();build()};$('#pcClose').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
 $('#pcPhoto').onchange=async e=>{actionPhoto=e.target.files?.[0]?await fileImage(e.target.files[0]):actionPhoto;actionCrop={scale:1,x:0,y:0};build()};$('#pcHeadshot').onchange=async e=>{headshot=e.target.files?.[0]?await fileImage(e.target.files[0]):headshot;headCrop={scale:1,x:0,y:0};build()};$('#pcPlayer').onchange=async()=>{await useProfile();build()};$('#pcScope').onchange=build;$('#pcPosition').oninput=build;$('#pcBuild').onclick=build;$('#pcShare').onclick=share;$('#pcSave').onclick=save;$('#pcResetAction').onclick=()=>{actionCrop={scale:1,x:0,y:0};build()};$('#pcResetHead').onclick=()=>{headCrop={scale:1,x:0,y:0};build()};bindGesture($('#pcActionTouch'),()=>actionCrop,v=>actionCrop=v);bindGesture($('#pcHeadTouch'),()=>headCrop,v=>headCrop=v);
}
function bindGesture(el,getCrop,setCrop){const pts=new Map();let last=null,pinch=null;const dist=()=>{const a=[...pts.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)};el.onpointerdown=e=>{e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});el.setPointerCapture?.(e.pointerId);last={x:e.clientX,y:e.clientY};if(pts.size===2)pinch={d:dist(),s:getCrop().scale||1}};el.onpointermove=e=>{if(!pts.has(e.pointerId))return;const r=el.getBoundingClientRect(),c={...getCrop()},prev=pts.get(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size>=2&&pinch){c.scale=clamp(pinch.s*(dist()/Math.max(1,pinch.d)),1,4)}else{c.x=clamp((c.x||0)+(e.clientX-prev.x)/(r.width*.32),-2.5,2.5);c.y=clamp((c.y||0)+(e.clientY-prev.y)/(r.height*.32),-2.5,2.5)}setCrop(c);build()};const end=e=>{pts.delete(e.pointerId);pinch=null;last=null};el.onpointerup=end;el.onpointercancel=end}
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadData(){if(viewer)return;viewer=await rpc('get_public_team_viewer',{p_token:token});try{profiles=await rpc('get_public_player_card_profiles',{p_token:token})}catch(_){profiles=[]}}
function sortedPlayers(){return [...(viewer?.players||[])].sort((a,b)=>Number(a.jersey||999)-Number(b.jersey||999)||String(a.name).localeCompare(String(b.name)))}
function profileFor(id){return profiles.find(p=>String(p.id)===String(id))||null}function gameOptions(){return [...(viewer?.games||[])].sort((a,b)=>Number(b.week_number||0)-Number(a.week_number||0))}
function populate(){const ps=sortedPlayers(),sel=$('#pcPlayer'),prior=sel.value;sel.innerHTML=ps.map(p=>`<option value="${esc(p.id)}">#${esc(p.jersey||'?')} ${esc(p.name||'Player')}</option>`).join('');if(ps.some(p=>String(p.id)===prior))sel.value=prior;const current=$('#gameSelect')?.value,scope=$('#pcScope');scope.innerHTML=`<option value="season">Season to date</option>`+gameOptions().map(g=>`<option value="game:${g.id}">Week ${g.week_number||'?'} • ${esc(g.opponent_name||'Opponent')}</option>`).join('');if(current&&[...scope.options].some(o=>o.value===`game:${current}`))scope.value=`game:${current}`}
async function useProfile(){const p=profileFor($('#pcPlayer').value);actionPhoto=p?.action_photo_data?await loadImage(p.action_photo_data):null;headshot=p?.headshot_data?await loadImage(p.headshot_data):(actionPhoto||null);actionCrop={scale:1,x:0,y:0,...(p?.action_photo_crop||{})};headCrop={scale:1,x:0,y:0,...(p?.headshot_crop||{})};$('#pcPosition').value=[p?.primary_position,p?.secondary_position].filter(Boolean).join(' • ')}
function loadImage(src){return new Promise(res=>{if(!src)return res(null);const i=new Image();i.crossOrigin='anonymous';i.onload=()=>res(i);i.onerror=()=>res(null);i.src=src})}function fileImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>loadImage(r.result).then(res);r.onerror=rej;r.readAsDataURL(file)})}
function raw(p){return p?.event_data?.raw||p?.event_data||{}}function has(r,x){return Array.isArray(r.extras)&&r.extras.includes(x)}function selectedGames(){const v=$('#pcScope').value;if(v==='season')return gameOptions();const id=v.split(':')[1];return gameOptions().filter(g=>String(g.id)===id)}function selectedPlays(){const ids=new Set(selectedGames().map(g=>g.id));return (viewer?.plays||[]).filter(p=>ids.has(p.game_id))}
function calcStats(playerId){let att=0,cmp=0,passY=0,passTd=0,int=0,rush=0,rushY=0,rushTd=0,tkl=0,tfl=0,sacks=0,defInt=0;for(const p of selectedPlays()){const r=raw(p),type=String(r.type||p.play_type||''),yards=Number(r.yards??p.yards??0),sub=String(r.sub||p.subtype||'');if(type==='Pass'&&String(r.player)===String(playerId)){att++;if(sub==='Complete'){cmp++;passY+=yards;if(has(r,'TD'))passTd++}if(sub==='Intercepted')int++}if(type==='Rush'&&String(r.player)===String(playerId)){rush++;rushY+=yards;if(has(r,'TD'))rushTd++}if(type==='Defense'){const val=Number((r.defCredits||{})[playerId]||0);if(val){tkl+=val;if(r.tackleKind==='TFL')tfl+=val;if(r.tackleKind==='Sack')sacks+=val}if(String(r.interceptionPlayerId)===String(playerId))defInt++}}const rows=[];if(att){rows.push(['PASSING',`${cmp}/${att}`],['PASS YDS',passY],['PASS TD',passTd])}if(rush){rows.push(['RUSHES',rush],['RUSH YDS',rushY],['RUSH TD',rushTd])}if(tkl)rows.push(['TACKLES',Number.isInteger(tkl)?tkl:tkl.toFixed(1)]);if(tfl)rows.push(['TFL',Number.isInteger(tfl)?tfl:tfl.toFixed(1)]);if(sacks)rows.push(['SACKS',Number.isInteger(sacks)?sacks:sacks.toFixed(1)]);if(defInt)rows.push(['INT',defInt]);const totalY=passY+rushY,totalTd=passTd+rushTd;if(totalY)rows.push(['TOTAL YDS',totalY]);if(totalTd)rows.push(['TOTAL TD',totalTd]);return rows.slice(0,10)}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function cover(ctx,img,x,y,w,h,crop){if(!img)return;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const base=Math.max(w/img.width,h/img.height),s=base*Number(crop?.scale||1),dw=img.width*s,dh=img.height*s,dx=(w-dw)/2+Number(crop?.x||0)*w*.32,dy=(h-dh)/2+Number(crop?.y||0)*h*.32;ctx.drawImage(img,x+dx,y+dy,dw,dh);ctx.restore()}function contain(ctx,img,x,y,w,h){if(!img)return;const s=Math.min(w/img.width,h/img.height),dw=img.width*s,dh=img.height*s;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function fit(ctx,text,max,base,min=20){let size=base;while(size>min){ctx.font=`900 ${size}px Arial Black,Impact,sans-serif`;if(ctx.measureText(text).width<=max)break;size-=2}return size}function slant(ctx,x,y,w,h,fill,cut=38){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y);ctx.lineTo(x+w-cut,y+h);ctx.lineTo(x,y+h);ctx.closePath();ctx.fillStyle=fill;ctx.fill()}function outlined(ctx,text,x,y,size,fill,stroke='#111',line=8,italic=false){ctx.save();ctx.font=`${italic?'italic ':''}900 ${size}px Arial Black,Impact,sans-serif`;ctx.lineJoin='round';ctx.lineWidth=line;ctx.strokeStyle=stroke;ctx.strokeText(text,x,y);ctx.fillStyle=fill;ctx.fillText(text,x,y);ctx.restore()}
function seed(i){const x=Math.sin(i*927.17)*43758.5453;return x-Math.floor(x)}function distress(ctx,x,y,w,h,dark,light){ctx.save();rounded(ctx,x,y,w,h,28);ctx.clip();for(let i=0;i<420;i++){ctx.globalAlpha=.025+seed(i+9)*.075;ctx.fillStyle=i%4?dark:light;ctx.beginPath();ctx.arc(x+seed(i)*w,y+seed(i+311)*h,.5+seed(i+711)*3,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.globalAlpha=1}
function badge(ctx,x,y,w,h,accent,ink,cream,text){ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(-.15);ctx.fillStyle=cream;ctx.strokeStyle=accent;ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle=ink;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=ink;ctx.textAlign='center';ctx.font='900 22px Arial Black,Impact,sans-serif';ctx.fillText(text==='SEASON'?'SEASON':'WEEK',0,-8);ctx.font='900 49px Arial Black,Impact,sans-serif';ctx.fillText(text==='SEASON'?'STD':text,0,42);ctx.restore();ctx.textAlign='left'}
function drawLogoMedallion(ctx,img,x,y,size,accent,ink,cream){ctx.save();ctx.beginPath();ctx.arc(x,y,size/2,0,Math.PI*2);ctx.fillStyle=cream;ctx.fill();ctx.lineWidth=8;ctx.strokeStyle=ink;ctx.stroke();ctx.beginPath();ctx.arc(x,y,size/2-8,0,Math.PI*2);ctx.clip();if(img)contain(ctx,img,x-size*.36,y-size*.36,size*.72,size*.72);else{ctx.fillStyle=accent;ctx.font=`900 ${size*.34}px Arial Black,Impact,sans-serif`;ctx.textAlign='center';ctx.fillText('TEAM',x,y+size*.11)}ctx.restore();ctx.textAlign='left'}
function drawBrand(ctx,x,y,w,h,accent,ink,cream){ctx.save();ctx.translate(x,y);ctx.fillStyle=ink;ctx.font='900 30px Arial Black,Impact,sans-serif';ctx.fillText('BLEACHER',0,30);ctx.font='900 44px Arial Black,Impact,sans-serif';ctx.fillText('STATS',45,78);ctx.fillStyle=accent;ctx.fillRect(45,87,w-55,28);ctx.fillStyle=ink;ctx.font='900 13px Arial Black,Impact,sans-serif';ctx.fillText('GRIDIRON EDITION',62,108);ctx.restore()}
async function build(){const canvas=$('#pcCanvas');if(!canvas||!viewer)return;const ctx=canvas.getContext('2d'),W=1080,H=2520,X=40,CW=1000,CH=1200,FY=30,BY=1290,cream='#f2ead8';const p=sortedPlayers().find(x=>String(x.id)===$('#pcPlayer').value)||sortedPlayers()[0];if(!p)return;
 const primary=viewer.team?.primary||'#111111',accent=viewer.team?.accent||'#f15a2a';const ink=primary.toLowerCase()==='#f28c28'?accent:primary,orange=ink===primary?accent:primary;const logo=await loadImage(viewer.team?.logo||'');const name=String(p.name||'PLAYER').toUpperCase(),num=String(p.jersey||'—'),positions=($('#pcPosition').value.trim()||'PLAYER').toUpperCase(),team=String(viewer.team?.name||'TEAM').toUpperCase(),games=selectedGames(),season=$('#pcScope').value==='season',g=games[0],week=season?'SEASON':String(g?.week_number||'—'),opp=season?'SEASON TO DATE':String(g?.opponent_name||'OPPONENT').toUpperCase(),ourScore=season?'':Number(g?.team_score||0),oppScore=season?'':Number(g?.opponent_score||0),rows=calcStats(p.id);
 ctx.clearRect(0,0,W,H);ctx.fillStyle='#282828';ctx.fillRect(0,0,W,H);
 // FRONT — faithful vintage layout
 ctx.save();rounded(ctx,X,FY,CW,CH,32);ctx.clip();ctx.fillStyle=cream;ctx.fillRect(X,FY,CW,CH);ctx.fillStyle=orange;ctx.fillRect(X+24,FY+24,CW-48,14);const px=X+68,py=FY+55,pw=CW-112,ph=CH-124;ctx.fillStyle='#ccc4b4';ctx.fillRect(px,py,pw,ph);if(actionPhoto)cover(ctx,actionPhoto,px,py,pw,ph,actionCrop);
 slant(ctx,X+20,FY+37,375,128,ink,58);ctx.fillStyle=orange;ctx.fillRect(X+25,FY+151,308,10);outlined(ctx,name,X+52,FY+121,fit(ctx,name,285,72,40),'#fff',ink,7,true);ctx.fillStyle=orange;ctx.beginPath();ctx.moveTo(X+350,FY+37);ctx.lineTo(X+391,FY+37);ctx.lineTo(X+330,FY+165);ctx.lineTo(X+291,FY+165);ctx.closePath();ctx.fill();
 slant(ctx,X+22,FY+298,260,165,ink,38);ctx.fillStyle=orange;ctx.fillRect(X+29,FY+309,214,12);outlined(ctx,`#${num}`,X+48,FY+419,86,orange,'#fff',11,true);ctx.strokeStyle=ink;ctx.lineWidth=5;ctx.strokeText(`#${num}`,X+48,FY+419);slant(ctx,X+22,FY+474,260,92,ink,34);outlined(ctx,positions,X+47,FY+536,fit(ctx,positions,190,39,22),'#fff',ink,5,false);badge(ctx,X+742,FY+49,214,132,orange,ink,cream,week);
 ctx.save();ctx.translate(X+920,FY+510);ctx.rotate(-.56);for(let i=0;i<5;i++){ctx.fillStyle=i%2?ink:orange;ctx.fillRect(0,i*43,63,25)}ctx.restore();drawLogoMedallion(ctx,logo,X+105,FY+1090,126,orange,ink,cream);slant(ctx,X+210,FY+1080,700,96,ink,-38);outlined(ctx,team,X+252,FY+1148,fit(ctx,team,600,50,28),'#fff',ink,5,true);ctx.fillStyle=orange;ctx.fillRect(X+232,FY+1163,620,10);distress(ctx,X,FY,CW,CH,ink,cream);ctx.restore();ctx.strokeStyle='#a79880';ctx.lineWidth=6;rounded(ctx,X,FY,CW,CH,32);ctx.stroke();
 // BACK — same visual hierarchy as approved reference
 ctx.save();rounded(ctx,X,BY,CW,CH,32);ctx.clip();ctx.fillStyle=cream;ctx.fillRect(X,BY,CW,CH);ctx.fillStyle=orange;ctx.fillRect(X+24,BY+24,CW-48,13);const hx=X+58,hy=BY+55,hw=300,hh=302;ctx.fillStyle=ink;ctx.fillRect(hx-8,hy-8,hw+16,hh+16);if(headshot)cover(ctx,headshot,hx,hy,hw,hh,headCrop);else if(actionPhoto)cover(ctx,actionPhoto,hx,hy,hw,hh,headCrop);
 const rx=X+390,rw=590;ctx.fillStyle=orange;ctx.fillRect(rx,hy,rw,116);outlined(ctx,name,rx+20,hy+84,fit(ctx,name,360,78,42),ink,orange,3,true);outlined(ctx,`#${num}`,X+856,hy+84,62,ink,orange,3,true);ctx.fillStyle=ink;ctx.fillRect(rx,hy+122,rw,66);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,positions,500,36,22)}px Arial Black,Impact,sans-serif`;ctx.fillText(positions,rx+20,hy+168);ctx.fillStyle=orange;ctx.fillRect(rx,hy+196,rw,66);ctx.fillStyle=ink;ctx.font=`900 ${fit(ctx,team,500,35,21)}px Arial Black,Impact,sans-serif`;ctx.fillText(team,rx+20,hy+241);
 const sy=BY+390;if(season){ctx.fillStyle=orange;ctx.fillRect(X+58,sy,CW-116,62);ctx.fillStyle=ink;ctx.font='900 31px Arial Black,Impact,sans-serif';ctx.fillText('SEASON TO DATE',X+78,sy+43)}else{ctx.fillStyle=orange;ctx.fillRect(X+58,sy,CW-116,60);ctx.fillStyle=ink;ctx.font=`900 ${fit(ctx,team,700,33,22)}px Arial Black,Impact,sans-serif`;ctx.fillText(team,X+78,sy+41);ctx.textAlign='right';ctx.fillText(String(ourScore),X+946,sy+41);ctx.textAlign='left';ctx.fillStyle=ink;ctx.fillRect(X+58,sy+64,CW-116,60);ctx.fillStyle='#fff';ctx.font=`900 ${fit(ctx,opp,700,31,20)}px Arial Black,Impact,sans-serif`;ctx.fillText(opp,X+78,sy+105);ctx.textAlign='right';ctx.fillText(String(oppScore),X+946,sy+105);ctx.textAlign='left'}
 const tx=X+86,ty=BY+535,tw=CW-172,rh=46,shown=rows.length?rows:[['PLAYER STATS','—']];ctx.fillStyle=cream;ctx.fillRect(tx,ty,tw,rh*shown.length);ctx.strokeStyle=ink;ctx.lineWidth=3;ctx.strokeRect(tx,ty,tw,rh*shown.length);shown.forEach(([k,v],i)=>{const yy=ty+i*rh;if(i){ctx.beginPath();ctx.moveTo(tx,yy);ctx.lineTo(tx+tw,yy);ctx.stroke()}ctx.fillStyle=ink;ctx.font='900 22px Arial Black,Impact,sans-serif';ctx.fillText(String(k),tx+18,yy+32);ctx.textAlign='right';ctx.font='900 24px Arial Black,Impact,sans-serif';ctx.fillText(String(v),tx+tw-18,yy+32);ctx.textAlign='left'});
 const footerY=BY+980;drawBrand(ctx,X+70,footerY,280,130,orange,ink,cream);ctx.fillStyle=ink;ctx.font='900 17px Arial Black,Impact,sans-serif';ctx.fillText(season?'PLAYER CARD • SEASON':'PLAYER CARD • WEEK '+week,X+405,footerY+28);ctx.fillStyle=orange;ctx.fillRect(X+405,footerY+42,230,8);ctx.font='italic 700 23px "Comic Sans MS","Marker Felt",cursive';ctx.fillText('SOME KIDS',X+405,footerY+82);ctx.fillText('PLAY THE GAME.',X+405,footerY+108);ctx.fillText('SOME DADS',X+405,footerY+134);ctx.fillText('KEEP THE STATS.',X+405,footerY+160);drawLogoMedallion(ctx,logo,X+890,footerY+76,120,orange,ink,cream);ctx.font='900 15px Arial Black,Impact,sans-serif';ctx.textAlign='center';ctx.fillStyle=ink;ctx.fillText(team,X+890,footerY+164);ctx.textAlign='left';distress(ctx,X,BY,CW,CH,ink,cream);ctx.restore();ctx.strokeStyle='#a79880';ctx.lineWidth=6;rounded(ctx,X,BY,CW,CH,32);ctx.stroke();
 await new Promise(r=>canvas.toBlob(b=>{lastBlob=b;lastName=`${String(p.name||'player').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${season?'season':`week-${week}`}-card.png`;r()},'image/png',.96));$('#pcShare').disabled=!lastBlob;$('#pcSave').disabled=!lastBlob}
async function share(){if(!lastBlob)return;const f=new File([lastBlob],lastName,{type:'image/png'});try{if(navigator.canShare?.({files:[f]})){await navigator.share({files:[f]});return}}catch(e){if(e?.name==='AbortError')return}save()}function save(){if(!lastBlob)return;const u=URL.createObjectURL(lastBlob),a=document.createElement('a');a.href=u;a.download=lastName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();