(()=>{
const URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const token=new URLSearchParams(location.search).get('token')||'';
const qkey=`sidelineSnapQueue:${token}`;
const skey=`sidelineSnapSelection:${token}`;
const gkey=`sidelineSnapGame:${token}`;
let game=null,players=[],selected=new Set(),counts={},syncing=false,linkValid=true,offlineShellReady=false;
const $=s=>document.querySelector(s);
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function queue(){try{return JSON.parse(localStorage.getItem(qkey)||'[]')}catch{return[]}}
function saveQueue(v){localStorage.setItem(qkey,JSON.stringify(v))}
function saveSelection(){localStorage.setItem(skey,JSON.stringify([...selected]))}
function loadSelection(){try{return new Set(JSON.parse(localStorage.getItem(skey)||'[]'))}catch{return new Set()}}
function loadGameCache(){try{const d=JSON.parse(localStorage.getItem(gkey)||'null');if(!d)return null;const expires=Date.parse(d.expiresAt||'');if(Number.isFinite(expires)&&expires<=Date.now()){localStorage.removeItem(gkey);return null}return d}catch{return null}}
function saveGameCache(){if(!game)return;try{localStorage.setItem(gkey,JSON.stringify({...game,players,playerSnapCounts:counts,savedAt:new Date().toISOString()}))}catch(e){console.warn('Could not save offline game',e)}}
async function rpc(name,body){let r;try{r=await fetch(`${URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)})}catch(e){e.networkError=true;throw e}const text=await r.text();if(!r.ok){const e=new Error((()=>{try{return JSON.parse(text).message||text}catch{return text}})());e.status=r.status;throw e}return text?JSON.parse(text):null}
function msg(text,err=false){const m=$('#message');m.textContent=text;m.classList.remove('hidden','err');if(err)m.classList.add('err')}
function clearMsg(){const m=$('#message');m.textContent='';m.classList.add('hidden');m.classList.remove('err')}
function status(){const pending=queue().length;$('#syncStatus').textContent=navigator.onLine===false?'Offline — recording locally':pending?`${pending} snap${pending===1?'':'s'} waiting to sync`:'Synced';$('#syncDetail').textContent=`Participation only — game stats cannot be edited here. ${offlineShellReady&&game?'Offline ready.':'Preparing offline access…'}`}
function minimum(){const n=Number(game?.team?.snapMinimum);return Number.isInteger(n)&&n>=1&&n<=100?n:10}
function render(){const min=minimum();document.documentElement.style.setProperty('--p',game?.team?.primary||'#177b46');document.documentElement.style.setProperty('--a',game?.team?.accent||'#f0b33b');$('#teamName').textContent=game?`${game.team.name} vs ${game.game.opponent}`:'Snap Tracker';$('#gameMeta').textContent=game?`Week ${game.game.week||'?'} • Q${game.game.quarter||1} • ${game.game.teamScore}-${game.game.opponentScore}`:'Loading…';$('#snapCount').textContent=game?.snapCount||0;$('#minimumLabel').textContent=`${min}-Snap Minimum`;$('#playersBelowMinimum').textContent=players.filter(p=>Number(counts[p.id]||0)<min).length;$('#totalPlayerSnaps').textContent=`${Object.values(counts).reduce((a,n)=>a+Number(n||0),0)} player-snaps`;$('#players').innerHTML=players.map(p=>{const count=Number(counts[p.id]||0),done=count>=min,pct=Math.min(100,(count/min)*100);return `<label class="player ${selected.has(p.id)?'in':''} ${done?'complete':'needs'}"><input type="checkbox" data-id="${p.id}" ${selected.has(p.id)?'checked':''}><div class="player-main"><div class="player-name"><span class="num">#${p.jersey}</span><span class="name">${escapeHtml(p.name)}</span></div></div><div class="progress"><div class="progress-top"><span class="progress-count">${count} / ${min}</span><span class="progress-status ${done?'done':''}">${done?'MET':`NEEDS ${min-count}`}</span></div><div class="bar"><div class="bar-fill ${done?'done':''}" style="width:${pct}%"></div></div></div></label>`}).join('');document.querySelectorAll('.player input').forEach(ch=>ch.addEventListener('change',()=>{ch.checked?selected.add(ch.dataset.id):selected.delete(ch.dataset.id);saveSelection();renderSelectionOnly()}));renderSelectionOnly();status()}
function renderSelectionOnly(){document.querySelectorAll('.player').forEach(el=>{const ch=el.querySelector('input');el.classList.toggle('in',ch.checked)});$('#onFieldCount').textContent=`${selected.size} on field`;$('#recordSnap').disabled=!selected.size||!linkValid}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function applyGame(d){game=d;players=d.players||[];counts=d.playerSnapCounts||{};linkValid=true;const prior=loadSelection();selected=new Set([...prior].filter(id=>players.some(p=>p.id===id)));if(!selected.size)players.forEach(p=>selected.add(p.id));saveSelection();saveGameCache();render()}
async function refresh(){if(!token){linkValid=false;msg('This snap tracker link is missing its game token.',true);return}const cached=loadGameCache();if(cached){applyGame(cached);msg('Saved game loaded — checking for updates…')}try{const d=await rpc('get_snap_tracker_game',{p_token:token});applyGame(d);clearMsg();await flush()}catch(e){if(cached&&(navigator.onLine===false||e.networkError)){applyGame(cached);msg('Offline copy loaded — recorded snaps will sync when service returns.');status();return}linkValid=false;msg(e.message||'Could not load this game.',true);renderSelectionOnly();status()}}
async function flush(){if(syncing||navigator.onLine===false||!token||!linkValid)return;let items=queue();if(!items.length){status();return}syncing=true;try{while(items.length){const item=items[0];await rpc('submit_snap_tracker_event',{p_token:token,p_client_event_id:item.id,p_player_ids:item.playerIds,p_quarter:item.quarter,p_client_created_at:item.createdAt});items.shift();saveQueue(items)}await refreshCounts()}catch(e){console.warn(e);if(e.status){linkValid=false;msg(e.message||'This link can no longer sync.',true)}status()}finally{syncing=false;renderSelectionOnly();status()}}
async function refreshCounts(){try{const d=await rpc('get_snap_tracker_game',{p_token:token});applyGame(d);clearMsg()}catch(e){console.warn(e)}}
$('#checkAll').addEventListener('click',()=>{players.forEach(p=>selected.add(p.id));saveSelection();render()});
$('#recordSnap').addEventListener('click',async()=>{if(!selected.size||!linkValid)return;const item={id:uuid(),playerIds:[...selected],quarter:game?.game?.quarter||null,createdAt:new Date().toISOString()};const items=queue();items.push(item);saveQueue(items);game.snapCount=(game.snapCount||0)+1;item.playerIds.forEach(id=>counts[id]=(counts[id]||0)+1);saveGameCache();render();$('#recordSnap').textContent='Recorded ✓';setTimeout(()=>$('#recordSnap').textContent='Record Snap',650);await flush()});
window.addEventListener('online',()=>{linkValid=true;flush()});setInterval(async()=>{if(navigator.onLine!==false){if(queue().length)await flush();else await refreshCounts()}else status()},10000);
if(navigator.serviceWorker?.ready)navigator.serviceWorker.ready.then(()=>{offlineShellReady=true;status()}).catch(()=>{});
refresh();
})();
