-- Gridiron hardening migration. Designed to be additive/idempotent.
create table if not exists public.team_voice_corrections (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  heard_text text not null,
  resolved_value jsonb not null,
  use_count integer not null default 1,
  updated_at timestamptz not null default now(),
  unique(team_id, heard_text)
);

create table if not exists public.viewer_events (
  id bigint generated by default as identity primary key,
  team_id uuid references public.teams(id) on delete cascade,
  game_id uuid references public.games(id) on delete cascade,
  session_id text not null,
  event_type text not null check (event_type in ('open','game_view','refresh')),
  created_at timestamptz not null default now()
);
create index if not exists viewer_events_team_created_idx on public.viewer_events(team_id,created_at desc);
create index if not exists viewer_events_game_created_idx on public.viewer_events(game_id,created_at desc);

-- Prevent duplicate non-archived games for the same team/season/week/opponent/type.
-- Keep archived history from blocking a replacement game.
create unique index if not exists games_active_identity_unique
on public.games(team_id,season_id,week,lower(trim(opponent_name)),game_type)
where status <> 'archived';

alter table public.team_voice_corrections enable row level security;
alter table public.viewer_events enable row level security;

-- Authenticated team members can read learned corrections. Writes should be performed
-- by the existing authenticated statkeeper path / service layer after membership checks.
drop policy if exists team_voice_corrections_member_read on public.team_voice_corrections;
create policy team_voice_corrections_member_read on public.team_voice_corrections for select to authenticated
using (exists (select 1 from public.team_members tm where tm.team_id=team_voice_corrections.team_id and tm.user_id=auth.uid()));

-- Anonymous viewer telemetry: insert-only. No public select/update/delete access.
drop policy if exists viewer_events_anon_insert on public.viewer_events;
create policy viewer_events_anon_insert on public.viewer_events for insert to anon, authenticated with check (session_id <> '' and event_type in ('open','game_view','refresh'));
