(function(root,factory){
  const field=typeof module==="object"&&module.exports?require("./field-position.js"):root.SidelineFieldPosition;
  const api=factory(field);
  if(typeof module==="object"&&module.exports)module.exports=api;
  else root.SidelineVoice=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(field){
  const SMALL=["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"];
  const TENS_WORDS=["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"];
  function spellNumber(n){const x=Number(n);if(!Number.isInteger(x)||x<0||x>99)return null;if(x<20)return SMALL[x];const tens=TENS_WORDS[Math.floor(x/10)],ones=x%10;return ones?`${tens} ${SMALL[ones]}`:tens}
  const NUMBER_WORDS=Object.freeze(Object.fromEntries(Array.from({length:100},(_,n)=>[n,spellNumber(n)])));
  const WORD_NUMBERS=Object.freeze(Object.fromEntries(Object.entries(NUMBER_WORDS).map(([n,word])=>[word,Number(n)])));
  const NUMBER_HOMOPHONES={oh:0,o:0,won:1,to:2,too:2,for:4,ate:8,fourty:40};
  function normalize(v){return String(v||"").toLowerCase().replace(/[–—-]/g," ").replace(/[^a-z0-9#' ]+/g," ").replace(/\s+/g," ").trim()}
  function spokenNumber(v,allowHomophones=false){let s=normalize(v);if(/^\d+$/.test(s)){const n=Number(s);return n<=99?n:null}if(s in WORD_NUMBERS)return WORD_NUMBERS[s];if(allowHomophones){const parts=s.split(" ").map(w=>w in NUMBER_HOMOPHONES?spellNumber(NUMBER_HOMOPHONES[w]):w);s=parts.join(" ");if(s in WORD_NUMBERS)return WORD_NUMBERS[s]}return null}
  const NUMBER_PATTERN=[...Object.keys(WORD_NUMBERS),...Object.keys(NUMBER_HOMOPHONES)].sort((a,b)=>b.length-a.length).map(x=>x.replace(/ /g,"\\s+")).join("|");
  const FIELD_NUMBER_PATTERN="(?:\\d+|(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)(?:\\s+(?:one|two|three|four|five|six|seven|eight|nine))?)";
  function canonicalizeJerseyReferences(v){let clean=normalize(v);clean=clean.replace(new RegExp(`\\b(number|jersey)\\s+(?:#\\s*)?(${NUMBER_PATTERN}|\\d{1,2})\\b`,"g"),(all,label,value)=>{const n=spokenNumber(value,true);return n===null?all:`${label} ${n}`});clean=clean.replace(new RegExp(`#\\s*(${NUMBER_PATTERN}|\\d{1,2})\\b`,"g"),(all,value)=>{const n=spokenNumber(value,true);return n===null?all:`#${n}`});return clean}
  function applyCorrections(v,corrections){let clean=normalize(v);for(const [heard,intended] of Object.entries(corrections||{}).sort((a,b)=>b[0].length-a[0].length)){const from=normalize(heard),to=normalize(intended);if(!from||!to)continue;clean=clean.replace(new RegExp(`\\b${from.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}\\b`,"g"),to)}return clean}
  function distance(a,b){const x=normalize(a),y=normalize(b),dp=Array.from({length:x.length+1},(_,i)=>[i]);for(let j=1;j<=y.length;j++)dp[0][j]=j;for(let i=1;i<=x.length;i++)for(let j=1;j<=y.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(x[i-1]===y[j-1]?0:1));return dp[x.length][y.length]}
  function nameAliases(roster){const counts={};for(const p of roster||[])for(const token of normalize(p.name).split(" ").filter(w=>w.length>=3))counts[token]=(counts[token]||0)+1;const map=new Map();for(const p of roster||[]){const full=normalize(p.name),aliases=[];if(full)aliases.push(full);for(const token of full.split(" "))if(token.length>=3&&counts[token]===1)aliases.push(token);map.set(p.id,[...new Set(aliases)].sort((a,b)=>b.length-a.length))}return map}
  function playerMentions(text,roster){const clean=canonicalizeJerseyReferences(text),found=[],aliases=nameAliases(roster);for(const p of roster||[]){const jersey=String(p.jersey??"").trim();let at=-1;for(const alias of aliases.get(p.id)||[]){const i=` ${clean} `.indexOf(` ${alias} `);if(i>=0&&(at<0||i<at))at=i}if(jersey){const m=new RegExp(`(?:#\\s*|(?:number|jersey)\\s+)${jersey}(?=\\s|$)`).exec(clean);if(m&&(at<0||m.index<at))at=m.index}if(at<0){const words=clean.split(" ");for(const alias of aliases.get(p.id)||[]){if(alias.includes(" ")||alias.length<3)continue;for(let i=0;i<words.length;i++)if(distance(words[i],alias)<=1){at=i;break}if(at>=0)break}}if(at>=0)found.push({player:p,index:at})}return found.sort((a,b)=>a.index-b.index).filter((x,i,a)=>a.findIndex(q=>q.player.id===x.player.id)===i)}
  function mentionAfter(text,mentions,cue,maxDistance=55){const m=cue.exec(text);if(!m)return null;const from=m.index+m[0].length;return mentions.find(x=>x.index>=from&&x.index-from<=maxDistance)?.player||null}
  function mentionBefore(text,mentions,cue,maxDistance=55){const m=cue.exec(text);if(!m)return null;return [...mentions].reverse().find(x=>x.index<m.index&&m.index-x.index<=maxDistance)?.player||null}
  function mentionsAfter(text,mentions,cue,stopCue,maxDistance=110){const m=cue.exec(text);if(!m)return [];const from=m.index+m[0].length,tail=text.slice(from),stop=stopCue?.exec(tail),to=stop?from+stop.index:from+maxDistance;return mentions.filter(x=>x.index>=from&&x.index<=to&&x.index-from<=maxDistance).map(x=>x.player)}
  function normalizeFootballSpeech(v){let clean=normalize(v);clean=clean.replace(/\bbrush(?=\s+(?:the|to|up|outside|inside|left|right|middle))\b/g,"rush");clean=clean.replace(/\b(?:fourth|force)\s+fumble\b/g,"forced fumble");clean=clean.replace(/\bbattered\s+down\b/g,"batted down");clean=clean.replace(/\bpacifier\s+exception\b/g,"pass was intercepted");clean=clean.replace(/\bpass\s+(?:was\s+)?exception\b/g,"pass was intercepted");return clean}
  function isPunt(text){return /\b(?:punt|punts|punted|punting)\b/.test(normalize(text))}
  function isInterception(text){const clean=normalizeFootballSpeech(text);return /\b(?:intercepted|interception|pick\s+six|picked(?:\s+it)?\s+off|i\s*n\s*t)\b/.test(clean)||/\bpicked\b(?!\s+up)/.test(clean)}
  function isDefensiveReturnTouchdown(text){const clean=normalize(text);return isInterception(clean)&&/\b(?:pick\s+six|touchdown|to\s+the\s+house|took\s+it\s+home|ran\s+it\s+back\s+for\s+(?:a\s+)?touchdown)\b/.test(clean)}
  function defensiveRoles(text,mentions){
    const clean=canonicalizeJerseyReferences(normalizeFootballSpeech(text)),tackleCue=/\b(?:tackled|stopped|sacked|tackle\s+(?:made\s+)?by|gang\s+tackled\s+by)\b/,tackleStop=/\b(?:but|and\s+(?:forced|there\s+was|recovered)|forced|fumble|recovered|recovery|returned|return|at\s+(?:our|their|the|midfield))\b/,recoveryCue=/\b(?:fumble\s+)?(?:recovery|recovered)\s+by\b/,forceCue=/\b(?:forced|forces|forcing)\s+(?:the\s+)?fumble\b|\bforced\s+fumble\b/,forceByCue=/\b(?:forced\s+(?:the\s+)?fumble|forced\s+fumble|fumble\s+forced)\s+by\b/,fumbleCue=/\bfumbl(?:e|ed|ing)\b/,intCue=/\b(?:intercepted|interception|pick\s+six|picked(?:\s+it)?\s+off|picked(?!\s+up)|i\s*n\s*t)\b/,intByCue=/\b(?:intercepted|interception|pick\s+six|picked(?:\s+it)?\s+off|picked(?!\s+up)|i\s*n\s*t)\s+by\b/,pdCue=/\b(?:batted\s+down|knocked\s+down|tipped|deflected|broke\s+up(?:\s+the\s+pass)?|pass\s+breakup|p\s*b\s*u|pass\s+defended)\b/,pdByCue=/\b(?:batted\s+down|knocked\s+down|tipped|deflected|broke\s+up(?:\s+the\s+pass)?|pass\s+breakup|p\s*b\s*u|pass\s+defended)(?:\s+the\s+pass)?\s+by\b/;
    const explicitTacklers=mentionsAfter(clean,mentions,tackleCue,tackleStop),recovery=mentionAfter(clean,mentions,recoveryCue),interceptor=isInterception(clean)?mentionAfter(clean,mentions,intByCue)||mentionBefore(clean,mentions,intCue)||mentionAfter(clean,mentions,intCue,100):null,passDefender=pdCue.test(clean)?mentionAfter(clean,mentions,pdByCue)||mentionAfter(clean,mentions,pdCue)||mentionBefore(clean,mentions,pdCue):null,hasForced=forceCue.test(clean),tackler=explicitTacklers[0]||null,inferForced=hasForced||(fumbleCue.test(clean)&&!!tackler&&!!recovery),forced=mentionAfter(clean,mentions,forceByCue)||tackler||(hasForced?mentionBefore(clean,mentions,forceCue):null),excluded=new Set([recovery?.id,interceptor?.id,passDefender?.id].filter(Boolean));
    const tacklerIds=explicitTacklers.length?[...new Set(explicitTacklers.map(x=>x.id))]:passDefender||interceptor?[]:mentions.map(x=>x.player.id).filter(id=>!excluded.has(id));
    return {tacklerIds,forcedFumblePlayerId:inferForced?forced?.id||null:null,fumbleRecoveryPlayerId:recovery?.id||null,interceptionPlayerId:interceptor?.id||null,passDefendedPlayerId:passDefender?.id||null}
  }
  function sideAliases(team,opp){const out={our:"ours",ours:"ours",own:"ours",are:"ours",their:"opp",theirs:"opp",there:"opp","they're":"opp",opponent:"opp"};for(const word of normalize(team).split(" "))if(word.length>2)out[word]="ours";for(const word of normalize(opp).split(" "))if(word.length>2)out[word]="opp";return out}
  function inferBareSpot(yard,context){const y=Number(yard);if(!Number.isFinite(y)||y<1||y>49)return null;const a=y,b=100-y,current=field.validSpot(context.ballSpot);if(current===null)return null;const da=Math.abs(a-current),db=Math.abs(b-current);if(da===db)return null;return da<db?a:b}
  function parsePositions(text,context){const clean=normalize(text),aliases=sideAliases(context.teamName,context.opponentName),words=Object.keys(aliases).sort((a,b)=>b.length-a.length).join("|");const hits=[];let m;const re=new RegExp(`\\b(${words})\\s+(?:yard\\s+line\\s+)?(${FIELD_NUMBER_PATTERN})\\b`,"g");while((m=re.exec(clean))){const yard=spokenNumber(m[2]);if(yard!==null&&yard<=49)hits.push({spot:field.spotFromSide(aliases[m[1]],yard,context.possession),index:m.index,explicitSide:true})}const mid=/\b(?:(?:at|to|on|from|starting at|started at)\s+(?:the\s+)?(?:50|fifty)(?:\s+yard\s+line)?|(?:the\s+)?(?:50|fifty)\s+yard\s+line|midfield)\b/g;while((m=mid.exec(clean)))hits.push({spot:50,index:m.index,explicitSide:true});const bare=new RegExp(`\\b(?:at|to|on|down at|tackled at|stopped at)\\s+(?:about\\s+|around\\s+|the\\s+)?(${FIELD_NUMBER_PATTERN})(?:\\s+yard\\s+line)?\\b`,"g");while((m=bare.exec(clean))){if(hits.some(h=>Math.abs(h.index-m.index)<10))continue;const yard=spokenNumber(m[1]);const spot=inferBareSpot(yard,context);if(spot!==null)hits.push({spot,index:m.index,explicitSide:false})}return hits.sort((a,b)=>a.index-b.index).filter((x,i,a)=>!i||x.index!==a[i-1].index)}
  function extractYards(text){const clean=normalize(text),num=`(\\d+|(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)(?:\\s+(?:one|two|three|four|five|six|seven|eight|nine))?)`;let m=new RegExp(`(loss\\s+of|minus|negative)?\\s*${num}\\s*(?:yard|yards|yd|yds)\\b(?:\\s+(loss|lost))?`).exec(clean);if(!m)m=new RegExp(`\\b(loss\\s+of|lost|minus|negative|gain(?:ed)?|gained|picked\\s+up|for)\\s+${num}\\b`).exec(clean);if(!m)return null;const n=spokenNumber(m[2]);return /loss|lost|minus|negative/.test(`${m[1]||""} ${m[3]||""}`)?-Math.abs(n):n}
  function extractReturnYards(text){const clean=normalize(text),num=`(\\d+|(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)(?:\\s+(?:one|two|three|four|five|six|seven|eight|nine))?)`,approx=`(?:about\\s+|around\\s+|roughly\\s+|approximately\\s+)?`;let m=new RegExp(`\\b(?:for\\s+(?:a\\s+)?)?return(?:ed)?(?:\\s+(?:it|the\\s+ball))?(?:\\s+of|\\s+for)?\\s+${approx}${num}\\s*(?:yard|yards|yd|yds)\\b`).exec(clean),yards=m?spokenNumber(m[1]):null;if(!m){m=new RegExp(`\\b(?:for\\s+(?:a\\s+)?)?${approx}${num}\\s*(?:yard|yards|yd|yds)\\s+return\\b`).exec(clean);yards=m?spokenNumber(m[1]):null}if(!m){m=new RegExp(`\\b(?:ran|run|took|carried)\\s+(?:it|the\\s+ball)\\s+back(?:\\s+for)?\\s+${approx}${num}\\s*(?:yard|yards|yd|yds)\\b`).exec(clean);yards=m?spokenNumber(m[1]):null}if(!m){m=new RegExp(`\\badvanced\\s+(?:it|the\\s+ball)?\\s*${approx}${num}\\s*(?:yard|yards|yd|yds)\\b`).exec(clean);yards=m?spokenNumber(m[1]):null}return m?{yards,phrase:m[0]}:null}
  function extractPuntYards(text){const clean=normalize(text),num=`(\\d+|(?:one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty)(?:\\s+(?:one|two|three|four|five|six|seven|eight|nine))?)`,patterns=[`\\b(?:punt|punts|punted|punting)(?:\\s+(?:the\\s+ball|it))?(?:\\s+(?:for|of))?\\s+(?:about\\s+|around\\s+)?${num}\\s*(?:yard|yards|yd|yds)\\b`,`\\b${num}\\s*(?:yard|yards|yd|yds)\\s+punt\\b`];for(const pattern of patterns){const m=new RegExp(pattern).exec(clean);if(m)return {yards:spokenNumber(m[1]),phrase:m[0]}}return null}
  function puntPlayer(text,mentions,side){const clean=canonicalizeJerseyReferences(text),puntCue=/\b(?:punt|punts|punted|punting)\b/,returnCue=/\b(?:return|returned|returning|fielded|received|ran\s+it\s+back)\b/;if(side==="punter")return mentionAfter(clean,mentions,/\b(?:punt|punts|punted|punting)(?:\s+(?:the\s+ball|it))?\s+by\b/)||mentionBefore(clean,mentions,puntCue)||mentionAfter(clean,mentions,puntCue,30);return mentionAfter(clean,mentions,/\b(?:return|returned|returning|fielded|received)(?:\s+(?:the\s+punt|it))?\s+by\b/)||mentionBefore(clean,mentions,returnCue)||mentionAfter(clean,mentions,returnCue)||((mentions||[]).length===1?mentions[0].player:null)}
  function findPlayCall(text){
    const clean=normalize(text),number=`(${NUMBER_PATTERN}|\\d{1,2})`,patterns=[
      `\\b(?:(?:the\\s+)?coach\\s+)?(?:we\\s+)?(?:called|calls|call|calling)\\s+(?:the\\s+)?play(?:\\s+call)?(?:\\s+(?:number|#))?\\s*${number}\\b`,
      `\\b(?:the\\s+)?play\\s+call(?:ed)?(?:\\s+(?:was|is))?(?:\\s+(?:number|#))?\\s*${number}\\b`,
      `\\b(?:the\\s+)?play(?:\\s+called)?(?:\\s+(?:was|is))?\\s+(?:number|#)\\s*${number}\\b`,
      `\\b(?:the\\s+)?play\\s+(?:number\\s+)?${number}\\s+(?:was\\s+called|was|is|and|then|with)\\b`,
      `\\b(?:the\\s+)?play\\s+(?:number\\s+)?${number}\\s+called\\b`,
      `\\b(?:that|it|this)\\s+(?:was|is)\\s+(?:called\\s+)?play(?:\\s+(?:number|#))?\\s*${number}\\b`,
      `\\b(?:we\\s+)?(?:ran|run|used|selected)\\s+(?:the\\s+)?play(?:\\s+(?:number|#))?\\s*${number}\\b`
    ];
    const matches=[];
    for(const pattern of patterns){const m=new RegExp(pattern).exec(clean);if(!m)continue;const n=spokenNumber(m[1],true);if(n!==null)matches.push({number:String(n),index:m.index,end:m.index+m[0].length})}
    return matches.sort((a,b)=>a.index-b.index||(b.end-b.index)-(a.end-a.index))[0]||null
  }
  function extractPlayCall(text){const match=findPlayCall(text);return match?{number:match.number}:null}
  function withoutPlayCall(text,match){const clean=normalize(text);if(!match)return clean;return normalize(`${clean.slice(0,match.index)} ${clean.slice(match.end)}`)}
  function fail(message,transcript,missing,partial){return {ok:false,error:message,transcript:String(transcript||""),missing:missing||null,partial:partial||null}}
  function isSack(text){return /\bsack(?:ed|s)?\b/.test(text)}
  function inferPlayType(clean,mentions,isDefense){const passCue=/\b(pass|passes|passed|throw|throws|threw|complete|completed|completion|incomplete|caught|catch|targeted|intended)\b/.test(clean)||isSack(clean)||isInterception(clean);const runCue=/\b(run|runs|ran|rush|rushes|rushed|carry|carries|carried|keeper|kept|scramble|scrambled|handoff|hand off)\b/.test(clean);if(passCue&&!runCue)return "pass";if(runCue&&!passCue)return "run";if(isDefense&&(isSack(clean)||isInterception(clean)))return "pass";if(!isDefense&&mentions.length>=2&&/\b(to|for)\b/.test(clean))return "pass";if(!isDefense&&mentions.length===1&&/\b(tackled|stopped|down at|up the middle|around the end|sweep|toss)\b/.test(clean))return "run";return null}
  function interpretVoiceCommand(transcript,roster,context){
    const ctx=context||{},clean=normalizeFootballSpeech(applyCorrections(transcript,ctx.voiceCorrections)),playCallMatch=findPlayCall(clean),playCall=playCallMatch?{number:playCallMatch.number}:null,playText=withoutPlayCall(clean,playCallMatch),mentions=playerMentions(playText,roster),positions=parsePositions(playText,ctx);
    if(!clean)return fail("Say or type a play first.",transcript);
    const isDefense=ctx.possession==="opp",puntPlay=isPunt(playText),inferredType=inferPlayType(playText,mentions,isDefense),isPass=inferredType==="pass",isRun=inferredType==="run",roles=isDefense?defensiveRoles(playText,mentions):null,returnInfo=(isDefense||puntPlay)?extractReturnYards(playText):null,puntInfo=puntPlay?extractPuntYards(playText):null,defensiveReturnTD=isDefense&&isDefensiveReturnTouchdown(playText);
    let start=positions.length>1?positions[0].spot:null,end=positions.length>1?positions[positions.length-1].spot:(positions.length===1?positions[0].spot:null);
    if(positions.length===1&&/\b(?:from|starting(?: at)?|started(?: at)?)\s*$/.test(playText.slice(0,positions[0].index))){start=end;end=null}
    const spokenStart=start;
    if(start===null&&field.validSpot(ctx.ballSpot)!==null)start=Number(ctx.ballSpot);
    if(defensiveReturnTD)end=100;else if(/\b(touchdown|end zone|td)\b/.test(playText))end=field.spotFromSide("endzone",0,ctx.possession);
    const directYards=extractYards(returnInfo?playText.replace(returnInfo.phrase," "):playText);
    let yards=start!==null&&end!==null?field.yardsBetween(start,end,ctx.possession):directYards;
    if(isDefense&&!puntPlay&&returnInfo&&start!==null&&end!==null){const returnEndedAt=/\breturn(?:ed)?\s+(?:ended\s+)?(?:at|to)\b/.test(playText);if(returnEndedAt){const recoverySpot=field.advanceSpot(end,-returnInfo.yards,"ours");yards=field.yardsBetween(start,recoverySpot,"opp")}else{const recoverySpot=end;yards=field.yardsBetween(start,recoverySpot,"opp");end=field.advanceSpot(recoverySpot,returnInfo.yards,"ours")}}
    const partial={startSpot:start,endSpot:end,playType:isRun?"Rush":isPass?"Pass":null,playerIds:mentions.map(x=>x.player.id),playCall,punt:puntPlay,puntYards:puntInfo?.yards??null,interception:isInterception(playText),tacklerIds:roles?.tacklerIds||[],forcedFumblePlayerId:roles?.forcedFumblePlayerId||null,fumbleRecoveryPlayerId:roles?.fumbleRecoveryPlayerId||null,interceptionPlayerId:roles?.interceptionPlayerId||null,passDefendedPlayerId:roles?.passDefendedPlayerId||null,defensiveTouchdownPlayerId:defensiveReturnTD?roles?.interceptionPlayerId||null:null,returnYards:returnInfo?.yards??0};
    const conflict=spokenStart!==null&&field.validSpot(ctx.ballSpot)!==null&&Number(spokenStart)!==Number(ctx.ballSpot)?{spoken:Number(spokenStart),current:Number(ctx.ballSpot)}:null;
    const decorate=result=>{if(playCall)result.flow.playCall=playCall;const locations=start!==null?`${field.label(start,ctx.teamName,ctx.opponentName)}${end!==null?` → ${field.label(end,ctx.teamName,ctx.opponentName)}`:""}`:"";if(locations)result.summary+=` • ${locations}`;if(playCall)result.summary+=` • Called play ${playCall.number}`;if(conflict)result.conflict=conflict;return result};
    if(puntPlay){
      if(end===null)return fail("I kept the punt details. Where did the return or punt end?",transcript,"endSpot",partial);
      const noReturn=/\b(?:fair\s+(?:catch|caught)|downed|not\s+returned|no\s+return|out\s+of\s+bounds|touchback)\b/.test(playText);
      if(isDefense){
        if(noReturn){const puntYards=start!==null?field.yardsBetween(start,end,"opp"):0,flow={type:"Punt",sub:"Opponent Punt",opponentPunt:true,player:null,yards:Number(puntYards||0),startSpot:start,endSpot:end,extras:[],puntReturned:false,opponentReturnYards:0};return decorate({ok:true,flow,summary:`Opponent Punt — no return`,transcript:String(transcript),inferred:{playType:true}})}
        const returner=puntPlayer(playText,mentions,"returner");
        if(!returner)return fail("I kept the opponent punt. Who returned it?",transcript,"returner",partial);
        if(!returnInfo)return fail("I kept the returner and ending spot. How many return yards?",transcript,"returnYards",partial);
        const catchSpot=field.advanceSpot(end,-returnInfo.yards,"ours"),flow={type:"Special",sub:"Punt Return",opponentPunt:true,player:returner.id,yards:Number(returnInfo.yards),startSpot:catchSpot,endSpot:end,extras:[]};
        return {ok:true,flow,summary:`Opponent Punt — #${returner.jersey} ${returner.name} — ${returnInfo.yards}-yard return • Ball at ${field.label(end,ctx.teamName,ctx.opponentName)}`,transcript:String(transcript),inferred:{playType:true}}
      }
      const punter=puntPlayer(playText,mentions,"punter");
      if(!punter)return fail("I kept our punt. Who punted it?",transcript,"punter",partial);
      let puntYards=puntInfo?.yards??null;
      if(puntYards===null&&start!==null){const landingSpot=returnInfo?field.advanceSpot(end,returnInfo.yards,"ours"):end;puntYards=field.yardsBetween(start,landingSpot,"ours")}
      if(puntYards===null)return fail("I kept our punt. How far was the punt?",transcript,"puntYards",partial);
      const flow={type:"Punt",sub:"Punt",player:punter.id,yards:Number(puntYards),startSpot:start,endSpot:end,extras:[],puntReturned:!!returnInfo,opponentReturnYards:Number(returnInfo?.yards||0)};
      return decorate({ok:true,flow,summary:`Punt — #${punter.jersey} ${punter.name} — ${puntYards} yards${returnInfo?` — returned ${returnInfo.yards} yards`:""}`,transcript:String(transcript),inferred:{playType:true}})
    }
    if(!isPass&&!isRun)return fail("I kept what I heard. Just tell me whether it was a run or pass.",transcript,"playType",partial);
    if(start===null)return fail("What was the starting field position?",transcript,"startSpot",partial);
    if((isRun||/\b(complete|completed|completion|caught|tackled)\b/.test(playText)||isSack(playText)||isInterception(playText))&&end===null&&yards===null)return fail(roles?.fumbleRecoveryPlayerId?"I kept the tackle, fumble, recovery, and return. Where was the receiver tackled and the fumble recovered?":isInterception(playText)?"I kept the interception and return. Where was the pass intercepted?":"I kept the play details. Just tell me where the play ended.",transcript,"endSpot",partial);
    const extras=[];if(/\b(touchdown|end zone|td)\b/.test(playText)&&!defensiveReturnTD)extras.push("TD");if(!isDefense&&/\bfumbl(?:e|ed|ing)\b/.test(playText))extras.push("Fumble");
    if(isDefense){
      let sub=isRun?"Opponent Run":isSack(playText)?"Sack":/\bincomplete\b/.test(playText)?"Incomplete Pass":isInterception(playText)?"INT":"Complete Pass";
      if(sub==="Incomplete Pass"||sub==="INT")yards=0;
      const tacklers=roles.tacklerIds;
      if(!["Incomplete Pass","INT"].includes(sub)&&!tacklers.length)return fail("I kept the play. Just tell me who made the tackle.",transcript,"tackler",partial);
      if(sub==="INT"&&!roles.interceptionPlayerId)return fail("I kept the interception. Who picked it off?",transcript,"interceptor",partial);
      const flow={type:"Defense",sub,yards:Number(yards||0),tacklerIds:tacklers,startSpot:start,endSpot:end,extras,forcedFumblePlayerId:roles.forcedFumblePlayerId,fumbleRecoveryPlayerId:roles.fumbleRecoveryPlayerId,interceptionPlayerId:roles.interceptionPlayerId,passDefendedPlayerId:roles.passDefendedPlayerId,defensiveTouchdownPlayerId:defensiveReturnTD?roles.interceptionPlayerId:null,returnYards:returnInfo?.yards??0};
      const playerLabel=id=>{const p=(roster||[]).find(x=>x.id===id);return p?`#${p.jersey} ${p.name}`:""},who=tacklers.map(playerLabel).filter(Boolean).join(" + "),events=[];
      if(flow.forcedFumblePlayerId)events.push(`FF ${playerLabel(flow.forcedFumblePlayerId)}`);
      if(flow.fumbleRecoveryPlayerId)events.push(`FR ${playerLabel(flow.fumbleRecoveryPlayerId)}`);
      if(flow.interceptionPlayerId)events.push(`INT ${playerLabel(flow.interceptionPlayerId)}`);
      if(flow.passDefendedPlayerId)events.push(`PD ${playerLabel(flow.passDefendedPlayerId)}`);
      if(returnInfo)events.push(`${returnInfo.yards}-yard return`);
      if(flow.defensiveTouchdownPlayerId)events.push(`TD ${playerLabel(flow.defensiveTouchdownPlayerId)}`);
      return decorate({ok:true,flow,summary:`${sub} — ${Number(yards||0)} yards${who?` — tackle ${who}`:""}${events.length?` — ${events.join(" • ")}`:""}`,transcript:String(transcript),inferred:{playType:!/(pass|run|rush|carry)/.test(playText)}})
    }
    if(isRun){if(!mentions.length)return fail("I kept the rush. Just tell me who carried the ball.",transcript,"runner",partial);const p=mentions[0].player;return decorate({ok:true,flow:{type:"Rush",player:p.id,yards:Number(yards||0),startSpot:start,endSpot:end,extras},summary:`Rush — #${p.jersey} ${p.name} — ${Number(yards||0)} yards`,transcript:String(transcript),inferred:{playType:!/(run|rush|carry)/.test(playText)}})}
    let sub=/\b(intercepted|interception|picked)\b/.test(playText)?"Intercepted":/\bincomplete\b/.test(playText)?"Incomplete":/\b(complete|completed|completion|caught|catch)\b/.test(playText)?"Complete":null;
    if(!sub&&/\b(to|for)\b/.test(playText)&&mentions.length>=2&&end!==null)sub="Complete";
    if(!sub)return fail("I kept the pass details. Just tell me: complete, incomplete, or intercepted?",transcript,"passResult",partial);
    if(mentions.length<2)return fail("I kept the pass result. Just tell me who threw it and the intended receiver.",transcript,"players",partial);
    const qb=mentions[0].player,receiver=mentions[1].player,flow={type:"Pass",sub,player:qb.id,player2:receiver.id,yards:sub==="Complete"?Number(yards||0):0,startSpot:start,endSpot:sub==="Complete"?end:start,extras};
    return decorate({ok:true,flow,summary:`Pass — #${qb.jersey} ${qb.name} to #${receiver.jersey} ${receiver.name} — ${sub}${sub==="Complete"?` for ${flow.yards} yards`:""}`,transcript:String(transcript),inferred:{playType:!/(pass|throw|threw)/.test(playText),passResult:sub==="Complete"&&!/(complete|caught|catch)/.test(playText)}})
  }
  return {NUMBER_WORDS,normalize,normalizeFootballSpeech,spokenNumber,canonicalizeJerseyReferences,applyCorrections,distance,playerMentions,parsePositions,extractYards,extractReturnYards,extractPuntYards,extractPlayCall,inferPlayType,interpretVoiceCommand};
});
