const assert=require('node:assert/strict');const fs=require('node:fs');const Access=require('../commercial-access.js');
const now=Date.parse('2026-09-11T12:00:00Z');
assert.equal(Access.resolve({tier:'trial',trial_used:true,trial_started_at:'2026-09-10T12:00:00Z',trial_ends_at:'2026-09-17T12:00:00Z'},now).coachAccess,true);
assert.equal(Access.resolve({tier:'trial',trial_used:true,trial_ends_at:'2026-09-08T12:00:00Z'},now).active,false);
assert.equal(Access.resolve({tier:'statkeeper',paid_access_starts_at:'2026-08-01T00:00:00Z',paid_access_ends_at:'2027-01-01T00:00:00Z'},now).recordAccess,true);
assert.equal(Access.resolve({tier:'free',access_source:'founder_comp',complimentary:true},now).coachAccess,true);
const checkout=fs.readFileSync('supabase/functions/create-stripe-checkout/index.ts','utf8'),status=fs.readFileSync('supabase/functions/checkout-status/index.ts','utf8'),webhook=fs.readFileSync('supabase/functions/stripe-webhook/index.ts','utf8'),app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('index.html','utf8'),sql=fs.readFileSync('supabase-commercial-access.sql','utf8');
assert.match(checkout,/price_1UEMQ23e6AZi8Uuzv3iUo0uL/);assert.match(checkout,/team_pro_upgrade/);assert.match(checkout,/Only this team's statkeeper/);assert.doesNotMatch(checkout,/sk_test_/);
assert.match(checkout,/sessionLinkError/);assert.match(checkout,/checkout\/sessions\/\$\{encodeURIComponent\(session\.id\)\}\/expire/,'an unlinked Stripe session must be expired before checkout is shown');
assert.match(webhook,/verifyStripeSignature/);assert.match(webhook,/Checkout price verification failed/);assert.match(webhook,/provider_event_id/);assert.doesNotMatch(webhook,/whsec_/);
assert.match(webhook,/priorEvent\?\.processed/,'only processed duplicate events may be acknowledged');assert.match(webhook,/Retrying previously unprocessed Stripe event/,'failed webhook deliveries must be retryable');assert.match(webhook,/requireSuccess\(historyError/,'critical entitlement writes must be checked');
assert.match(status,/purchaser_user_id",user\.id/,'checkout status must be scoped to the signed-in purchaser');assert.match(status,/Stripe could not verify this checkout/);assert.doesNotMatch(status,/\.upsert\(|\.insert\(|\.update\(/,'checkout status must remain read-only');
assert.match(app,/SB\.functions\.invoke\("create-stripe-checkout"/);assert.match(app,/handleCheckoutReturn/);
assert.match(app,/SB\.functions\.invoke\("checkout-status"/,'checkout return must verify the Stripe session');
assert.match(app,/Authorization:`Bearer \$\{session\.access_token\}`/,'checkout must explicitly send the signed-in user JWT');
assert.match(app,/connectTeamToCloud\(\{silent:true\}\)/,'saving a new signed-in team must connect it automatically');
assert.doesNotMatch(app,/openPlans\(true\)/,'successful team creation must not reopen the purchase-choice screen');
assert.match(app,/redirectUrl\.searchParams\.set\("accountConfirmed","1"\)/,'new accounts must return to the confirmation landing page');
assert.match(html,/id="accountConfirmationPage"/,'the email confirmation return needs a dedicated success page');
assert.match(html,/data-signup-plan="statkeeper"/);assert.match(html,/data-signup-plan="team_pro"/);
assert.match(html,/No card and no automatic charge/,'trial terms must be explicit during signup');
assert.doesNotMatch(html,/id="(?:backupDataBtn|restoreDataBtn|exportRosterBtn|importRosterBtn|exportExcelBtn|exportRawBtn|analyticsExportCard)"/,'customer export and import controls must be removed');
assert.match(html,/id="ownerBackupDataBtn"/);assert.match(html,/id="ownerRestoreDataBtn"/);assert.doesNotMatch(html,/xlsx\.full\.min\.js/,'the unused spreadsheet export dependency must be removed');
assert.match(sql,/insert into public\.profiles\(id\)/,'manual Auth confirmation must not prevent trial creation');
assert.match(sql,/now\(\)\+interval '7 days'/,'new eligible teams must receive seven trial days');
assert.match(sql,/te\.complimentary=true/,'complimentary teams must retain statkeeping access');
assert.match(sql,/te\.access_source in \('founder_comp','internal_test'\)/,'founder and internal-test teams must retain statkeeping access');
assert.match(sql,/te\.tier in \('statkeeper','coach','team_pro'\)/,'Team Pro must be recognized as a paid statkeeping tier');
console.log('commercial access checks passed');
