const assert=require('node:assert/strict');const fs=require('node:fs');const Access=require('../commercial-access.js');
const now=Date.parse('2026-09-11T12:00:00Z');
assert.equal(Access.resolve({tier:'trial',trial_used:true,trial_started_at:'2026-09-10T12:00:00Z',trial_ends_at:'2026-09-17T12:00:00Z'},now).coachAccess,true);
assert.equal(Access.resolve({tier:'trial',trial_used:true,trial_ends_at:'2026-09-08T12:00:00Z'},now).active,false);
assert.equal(Access.resolve({tier:'statkeeper',paid_access_starts_at:'2026-08-01T00:00:00Z',paid_access_ends_at:'2027-01-01T00:00:00Z'},now).recordAccess,true);
assert.equal(Access.resolve({tier:'free',access_source:'founder_comp',complimentary:true},now).coachAccess,true);
const checkout=fs.readFileSync('supabase/functions/create-stripe-checkout/index.ts','utf8'),webhook=fs.readFileSync('supabase/functions/stripe-webhook/index.ts','utf8'),app=fs.readFileSync('app.js','utf8');
assert.match(checkout,/price_1UEMQ23e6AZi8Uuzv3iUo0uL/);assert.match(checkout,/team_pro_upgrade/);assert.match(checkout,/Only this team's statkeeper/);assert.doesNotMatch(checkout,/sk_test_/);
assert.match(webhook,/verifyStripeSignature/);assert.match(webhook,/Checkout price verification failed/);assert.match(webhook,/provider_event_id/);assert.doesNotMatch(webhook,/whsec_/);
assert.match(app,/SB\.functions\.invoke\("create-stripe-checkout"/);assert.match(app,/handleCheckoutReturn/);
console.log('commercial access checks passed');
