const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console,Date};ctx.globalThis=ctx;vm.createContext(ctx);
for(const f of ['field-orientation.js','cloud-conflict.js','game-lifecycle.js','voice-workflow.js','edit-play-model.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const F=ctx.SidelineFieldOrientation,C=ctx.SidelineCloudConflict,G=ctx.SidelineGameLifecycle,V=ctx.SidelineVoiceWorkflow,E=ctx.SidelineEditPlay;
assert.equal(F.ourAttackDirection(1),'right');assert.equal(F.ourAttackDirection(2),'left');assert.equal(F.visualPercent(25,2),75);assert.equal(F.canonicalPercent(75,2),25);
assert.equal(C.canWrite({revision:2},{revision:3}).ok,false);assert.equal(C.canWrite({revision:4},{revision:3}).ok,true);assert.equal(C.nextRevision({revision:4},{revision:7}),8);assert.equal(C.prepareWrite({revision:2},{revision:3}).ok,false);assert.equal(C.prepareWrite({revision:4},{revision:3}).value.revision,5);
const a={team_id:'t',season_id:'s',week:4,opponent_name:'Raiders',game_type:'regular',status:'live'};assert.ok(G.findDuplicate({...a,opponent_name:' raiders '},[a]));assert.equal(G.normalizeStatus('complete'),'final');assert.equal(G.canTransition('live','final'),true);assert.equal(G.canTransition('final','scheduled'),false);
let p=V.merge({type:'Run',yards:5},{playerNumber:4});assert.equal(p.yards,5);assert.equal(V.next(p),null);p=V.applyAnswer(V.merge({type:'Run',yards:5},{}),'player',{playerId:'abe'});assert.equal(V.next(p),null);
assert.equal(E.phase({type:'Punt'}),'special');assert.ok(E.fields({type:'Punt'}).includes('punterId'));assert.ok(E.fields({type:'Defense'}).includes('forcedFumblePlayerId'));assert.ok(E.fields({type:'Pass'}).includes('receiverId'));
const app=fs.readFileSync('app.js','utf8');
assert.ok(app.includes('id="editFGDistance"'),'field goal Edit Play integration missing');
assert.ok(app.includes('id="editKickoffResult"'),'kickoff Edit Play integration missing');
assert.ok(app.includes('id="editTryType"'),'try Edit Play integration missing');
assert.ok(app.includes('id="editStartSpot"')&&app.includes('id="editEndSpot"'),'field spot Edit Play integration missing');
assert.ok(app.includes('renderVoiceMissingFollowup(result,transcript)'),'voice missing-info integration missing');
assert.ok(app.includes('Final confirmation: this historical game cannot be restored'),'final-game deletion safeguard missing');
console.log('Gridiron enhancement regression tests passed');
