const assert = require('node:assert/strict');
const fs = require('node:fs');

const app = fs.readFileSync('app.js', 'utf8');
const sw = fs.readFileSync('service-worker.js', 'utf8');
const sql = fs.readFileSync('supabase-live-stats.sql', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const styles = fs.readFileSync('styles.css', 'utf8');
const snapTracker = fs.readFileSync('snap-tracker.html', 'utf8');

assert.match(app, /function scheduleCloudSync\(delay=350\)/, 'completed local changes should be queued quickly');
assert.match(app, /if\(cloudSyncRunning\)\{cloudSyncRequested=true;return\}/, 'a change during an active sync must request a follow-up pass');
assert.match(app, /if\(runAgain\)scheduleCloudSync\(100\)/, 'the queued follow-up pass must run after the active sync finishes');
assert.match(app, /resolveCloudDeviceRole\(\)\.then\(role=>/, 'an apparent viewer with a local change must recheck its real membership');
assert.match(app, /persist\(\{skipCloud:true\}\);await resolveCloudDeviceRole\(\)/, 'every cloud load must restore the signed-in account role');
assert.match(app, /scheduleCloudSync\(0\);return toast\("Sync retry started"\)/, 'Retry Sync must preserve and upload pending statkeeper data');
assert.match(app, /table:'games',filter:`season_id=eq\.\$\{S\.cloud\.seasonId\}`/, 'game events must be scoped to the selected season');
assert.match(app, /table:'play_credits'/, 'player-credit changes must trigger viewer refreshes');
assert.match(app, /table:'snap_participants'/, 'snap-participant changes must trigger viewer refreshes');
assert.match(app, /await publishCloudGame\(cloudGameId\)/, 'a completed game sync must emit its publish marker');
assert.ok(app.indexOf('await syncOnePlay') < app.indexOf('await publishCloudGame(cloudGameId)'), 'publish marker must follow play sync');
assert.match(app, /if\(!isCloudStatkeeper\(\)\)\{[\s\S]*if\(role==="statkeeper"\)scheduleCloudSync\(delay\)/, 'only a verified statkeeper may continue to a write');
assert.match(app, /"Live updates on"/, 'viewers should see a live-connection indicator');
assert.match(app, /cloudAutoRefreshRunning=false/, 'automatic viewer reloads must use an explicitly declared lock');
assert.match(app, /cloudRealtimeRefreshQueued=true/, 'realtime events must remain queued while another viewer refresh is running');
assert.match(app, /scheduleCloudRealtimeReconnect/, 'a failed realtime channel must schedule a reconnect');
assert.match(app, /setInterval\(checkLiveGameRevisions,3000\)/, 'visible viewers should check game revisions every three seconds');
assert.match(app, /\.select\("id,revision"\)/, 'the frequent viewer check must fetch only lightweight revision markers');
assert.match(app, /document\.visibilityState==="hidden"/, 'the frequent viewer check must pause while the page is hidden');
assert.match(app, /cloudRevision:Number\(g\.revision\|\|1\)/, 'cloud-loaded games must retain the revision used for redraw checks');
assert.match(app, /else setTimeout\(checkLiveGameRevisions,100\)/, 'viewers must check immediately after reconnecting or returning to the page');
assert.match(sql, /security invoker/, 'publish RPC must preserve RLS authorization');
assert.match(app, /if\(teamExists\(\)&&isCloudViewer\(\)&&name!=="stats"\)/, 'viewer navigation must be restricted to Stats');
assert.match(app, /selectedStatsGameId=selectedStatsGameId\|\|preferredViewerGame\(\)\?\.id/, 'viewer entry must prefer a live game');
assert.match(app, /find\(g=>g\.status==="live"\)\|\|latestGame\(\)/, 'viewer fallback must use the newest completed game when none are live');
assert.match(app, /if\(!isCloudViewer\(\)&&currentGame\(\)\)selectedStatsGameId=currentGame\(\)\.id/, 'a statkeeper active game must not override a viewer game selection');
assert.match(app, /bottomNav"\)\.classList\.toggle\("hidden",!teamExists\(\)\|\|viewer\|\|coach\)/, 'viewer and coach accounts must not see statkeeper navigation tabs');
assert.match(app, /analyticsExportCard"\)\?\.classList\.toggle\("hidden",viewer\|\|coach\)/, 'viewer and coach raw analytics exports must be hidden');
assert.match(app, /function renderViewerGameSummary\(\)/, 'viewer Game Center must render its scoreboard');
assert.match(html, /id="viewerGameSummary"/, 'Stats must contain the viewer scoreboard destination');
assert.match(html, /id="shareStatsBtn"/, 'Stats sharing must remain available');
assert.match(sw, /v4-5-19-stripe-sandbox/, 'service worker cache must be bumped');
assert.match(styles, /nav\{[^}]*background:var\(--p\)/, 'the statkeeper bottom navigation must use the team primary color');
assert.match(styles, /nav button\.active\{[^}]*var\(--nav-active\)/, 'the active statkeeper tab must use the team accent treatment');
assert.match(app, /#bottomNav \[data-go\][\s\S]*classList\.toggle\("active"/, 'the current statkeeper tab must receive an active state');
assert.match(snapTracker, /\.actions\{[^}]*background:var\(--p\)[^}]*border-top:3px solid var\(--a\)/, 'the shared Snap Tracker action row must use team colors');
assert.match(snapTracker, /border-bottom:7px solid #65b946/, 'the shared Snap Tracker brand header must retain the company green');
assert.match(app, /Resume the game vs \$\{g\.opponent\} and mark it Live\?/, 'opening a final game must offer to resume it live');
assert.match(app, /Finalize the game vs \$\{g\.opponent\}\?/, 'finalizing a game must require confirmation');
assert.match(app, /async function syncDeletedCloudGames\(\)/, 'deleted local games must be reconciled to Supabase');
assert.match(app, /update\(\{status:"archived"\}\)/, 'cloud game deletion must use the recoverable archived status');
assert.match(app, /\.neq\("status","archived"\)/, 'archived games must be excluded from cloud loads and viewer checks');
assert.match(app, /function finishDefenseAtEndSpot\(\)/, 'manual defense must defer field position until the final step');
assert.match(app, /ensureDriveStart\(\(\)=>showDefenseTacklers\(\)\)/, 'manual defense must collect tacklers before the ending spot');
assert.match(app, /voiceRecognition\.continuous=true/, 'voice listening must tolerate pauses');
assert.match(app, /Stop & Transcribe/, 'voice recording must use an explicit stop action');
assert.match(app, /function teamPlaybook\(\)/, 'team playbook data must remain optional');
assert.match(app, /S\.flow\.playCall=selectedPlayCallSnapshot\(\)/, 'offensive entry must snapshot the selected play call');
assert.match(app, /playbook:teamPlaybook\(\)/, 'the reusable playbook must sync with the team');
assert.match(app, /p_event_data:\{local_id:p\.id,local_index:index,raw:/, 'the play-call snapshot must sync inside the raw play event');
assert.match(html, /id="playbookCard"/, 'the roster screen must expose playbook management');
assert.match(html, /id="nextPlayCallSelect"/, 'offensive entry must expose an optional play-call selector');
assert.match(html, /id="gamePlanCard"/, 'active games must expose weekly game-plan management');
assert.match(app, /game_plan:normalizeGamePlan\(g\)/, 'weekly game plans must sync with each cloud game');
assert.match(app, /gamePlan:planFromNewGameSource\(\)/, 'new games must receive the selected weekly plan');
assert.match(app, /play\.active=play\.active===false/, 'master plays must archive and restore without deletion');

console.log('live cloud sync checks passed');
