// Lightweight in-product Bleacher Butt Stats hub. Keeps edition data separate while
// giving one signed-in identity a clear place to understand and manage its products.
export function installBleacherAccountHub({sb,readLocal}){
 const style=document.createElement('style');style.textContent=`#bbsHubBtn{position:fixed;right:12px;top:12px;z-index:85;height:36px;padding:0 12px;border:1px solid #506058;border-radius:9px;background:#0b120f;color:#fff;font:900 10px/1 Inter,-apple-system,sans-serif;letter-spacing:.04em;box-shadow:0 4px 14px #0008}#bbsHub{position:fixed;inset:0;z-index:100020;display:none;background:#020504e8;padding:16px;overflow:auto;font-family:Inter,-apple-system,sans-serif}#bbsHub.open{display:block}.bbs-card{width:min(600px,100%);margin:18px auto;background:#fff;color:#10231a;border-radius:22px;padding:22px;box-shadow:0 25px 90px #000c}.bbs-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.bbs-brand{font-weight:950;font-size:20px}.bbs-brand small{display:block;margin-top:3px;color:#697870;font-size:9px;letter-spacing:.15em}.bbs-close{border:0;background:#eef2ef;border-radius:9px;width:36px;height:36px;font-size:19px}.bbs-email{margin:5px 0 18px;color:#6d7973;font-size:12px}.bbs-product{border:1px solid #d8e1dc;border-radius:15px;padding:15px;margin:10px 0;background:#f8faf9}.bbs-product.active{border-color:#8bc9a2;background:#f4fbf6}.bbs-row{display:flex;justify-content:space-between;gap:10px;align-items:center}.bbs-product b{font-size:15px}.bbs-product small{display:block;margin-top:3px;color:#748079;font-size:10px}.bbs-status{padding:5px 8px;border-radius:99px;background:#e7f7ec;color:#247644;font-size:9px;font-weight:950}.bbs-status.add{background:#eef1ef;color:#67736c}.bbs-team{margin-top:10px;padding-top:10px;border-top:1px solid #dfe6e2;font-size:12px}.bbs-team strong{display:block}.bbs-action{width:100%;margin-top:10px;padding:11px;border:0;border-radius:9px;background:#101713;color:#fff;font-weight:900}.bbs-action.secondary{background:#edf1ef;color:#18241e}.bbs-note{margin:15px 0 0;padding:11px;border-radius:10px;background:#f3f6f4;color:#6d7973;font-size:10px;line-height:1.45}.bbs-signout{width:100%;margin-top:14px;padding:11px;border:1px solid #e0caca;border-radius:9px;background:#fff7f7;color:#9c3030;font-weight:850}@media(max-width:600px){#bbsHubBtn{top:8px;right:8px;height:32px;padding:0 9px}.bbs-card{margin:4px auto;padding:18px}}`;document.head.appendChild(style);
 const btn=document.createElement('button');btn.id='bbsHubBtn';btn.type='button';btn.textContent='BLEACHER BUTT STATS';document.body.appendChild(btn);
 const hub=document.createElement('div');hub.id='bbsHub';document.body.appendChild(hub);
 async function render(){const session=(await sb.auth.getSession()).data?.session;const s=readLocal();hub.innerHTML=`<div class="bbs-card"><div class="bbs-head"><div class="bbs-brand">BLEACHER BUTT STATS<small>MY ACCOUNT</small></div><button class="bbs-close" aria-label="Close">×</button></div><div class="bbs-email">${escapeHtml(session?.user?.email||'')}</div><div class="bbs-product active"><div class="bbs-row"><div><b>🏀 Hardcourt Edition</b><small>Basketball</small></div><span class="bbs-status">ACTIVE</span></div><div class="bbs-team"><strong>${escapeHtml(s.team||'Hardcourt team')}</strong>${escapeHtml(s.grade||'')}</div><button class="bbs-action" data-close>Return to Hardcourt</button></div><div class="bbs-product"><div class="bbs-row"><div><b>🏈 Gridiron Edition</b><small>Football</small></div><span class="bbs-status add">SEPARATE EDITION</span></div><div class="bbs-team">Gridiron uses this same Bleacher Butt Stats identity. Football teams and data remain separate from Hardcourt.</div></div><div class="bbs-note">One login, separate sport workspaces. Adding or using another edition never merges football and basketball rosters, games or stats.</div><button class="bbs-signout" id="bbsSignOut">Sign Out of Bleacher Butt Stats</button></div>`;hub.querySelector('.bbs-close').onclick=close;hub.querySelector('[data-close]').onclick=close;hub.querySelector('#bbsSignOut').onclick=async()=>{await sb.auth.signOut();location.reload()}}
 function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function close(){hub.classList.remove('open')}btn.onclick=async()=>{await render();hub.classList.add('open')};hub.onclick=e=>{if(e.target===hub)close()};return {open:async()=>{await render();hub.classList.add('open')},close};
}
