// Hardcourt account gate + cloud persistence bootstrap.
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const AUTH_KEY='sb-eyuvgzhkhcpwtcbmsvct-hardcourt-auth-token';
const STATE_KEY='hardcourt-alpha',ACTIVE_TEAM_KEY='hardcourt-active-team-id';
const authOptions={auth:{storageKey:AUTH_KEY,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}};
const nativeSet=localStorage.setItem.bind(localStorage);let bootstrapClient=null,bootstrapping=true,persistTimer=null,lastProfileSig='',lastRosterSig='',persisting=false,persistAgain=false,accountPromise=null,cloudContexts=[],accountStatus=null;
function readLocal(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'null')||{}}catch{return {}}}function writeLocal(s){nativeSet(STATE_KEY,JSON.stringify(s))}
function clearLiveGameState(local){return{...local,events:[],minutes:{},period:1,clockMs:480000,running:false,fast:false,lastTick:null,opponent:'Opponent',opponentScore:0,teamScore:0,pendingShot:null,pendingAction:null}}
function blankNewAccountState(local={}){const keep={clientId:local.clientId};localStorage.removeItem('hardcourt-games');localStorage.removeItem(ACTIVE_TEAM_KEY);return{...keep,roster:[],active:[],events:[],minutes:{},team:'',grade:'',division:'',teamLogo:'',primary:'#111111',accent:'#39a852',period:1,clockMs:480000,running:false,fast:false,offenseRight:true,lastTick:null,statsScope:'game',chartMode:'shots',hardcourtNeedsTeamSetup:true}}
function pickContext(rows){if(!Array.isArray(rows)||!rows.length)return null;const remembered=localStorage.getItem(ACTIVE_TEAM_KEY);return rows.find(r=>String(r.teamId)===String(remembered))||rows[0]}
function mergeContext(local,ctx){const sameTeam=String(local.cloudTeamId||'')===String(ctx.teamId||''),base=sameTeam?local:clearLiveGameState(local),prior=sameTeam&&Array.isArray(local.roster)?local.roster:[],byCloud=new Map(prior.filter(p=>p.cloudId).map(p=>[String(p.cloudId),p]));const roster=(ctx.players||[]).map((p,i)=>{const old=byCloud.get(String(p.id))||prior.find(x=>String(x.num)===String(p.jersey)&&String(x.name||'').toLowerCase()===String(p.name||'').toLowerCase());return{id:old?.id||`p${i}`,num:p.jersey??'',name:p.name||'Player',headshot:old?.headshot||'',cloudId:p.id}});const next={...base,cloudTeamId:ctx.teamId,cloudSeasonId:ctx.seasonId,team:ctx.teamName==='My Team'?'':(ctx.teamName||''),grade:ctx.grade==='5th Grade'?'':(ctx.grade||''),primary:ctx.primary||'#111111',accent:ctx.accent||'#39a852',teamLogo:ctx.logo||'',hardcourtNeedsTeamSetup:ctx.teamName==='My Team',roster,active:roster.slice(0,5).map(p=>p.id)};nativeSet(ACTIVE_TEAM_KEY,String(ctx.teamId));return next}
function applySyncedRoster(local,rows){const synced=Array.isArray(rows)?rows:[];local.roster=(local.roster||[]).map(p=>{const row=synced.find(r=>(p.cloudId&&String(r.id)===String(p.cloudId))||(String(r.jersey)===String(p.num)&&String(r.name||'').toLowerCase()===String(p.name||'').toLowerCase()));return row?{...p,cloudId:row.id}:p});return local}
async function loadContexts(sb){const got=await sb.rpc('get_hardcourt_cloud_context');if(got.error)throw got.error;cloudContexts=Array.isArray(got.data)?got.data:[];accountStatus?.refresh?.();return cloudContexts}
async function ensureAccountContextInner(sb,user){if(!user)return false;let local=readLocal(),contexts;try{contexts=await loadContexts(sb)}catch(e){console.warn('Hardcourt account restore',e.message);return false}let ctx=pickContext(contexts);if(!ctx){local=blankNewAccountState(local);writeLocal(local);const made=await sb.rpc('create_hardcourt_team',{p_name:'My Team',p_grade:'',p_primary:'#111111',p_accent:'#39a852'});if(made.error){try{ctx=pickContext(await loadContexts(sb))}catch{}if(!ctx){console.warn('Hardcourt account create',made.error.message);return false}}else{try{ctx=pickContext(await loadContexts(sb))}catch{return false}}}if(!ctx)return false;local=mergeContext(local,ctx);writeLocal(local);return true}
async function ensureAccountContext(sb,user){if(accountPromise)return accountPromise;accountPromise=ensureAccountContextInner(sb,user);try{return await accountPromise}finally{accountPromise=null}}
async function switchHardcourtTeam(teamId){if(!bootstrapClient)return false;try{await persistSnapshot();const rows=await loadContexts(bootstrapClient),ctx=rows.find(r=>String(r.teamId)===String(teamId));if(!ctx)return false;lastProfileSig='';lastRosterSig='';writeLocal(mergeContext(readLocal(),ctx));location.reload();return true}catch(e){console.warn('Hardcourt team switch',e.message);return false}}
async function createAnotherHardcourtTeam(){if(!bootstrapClient)return false;await persistSnapshot();const made=await bootstrapClient.rpc('create_hardcourt_team',{p_name:'My Team',p_grade:'',p_primary:'#111111',p_accent:'#39a852'});if(made.error){console.warn('Hardcourt team create',made.error.message);return false}try{const rows=await loadContexts(bootstrapClient),ctx=[...rows].reverse().find(r=>r.teamName==='My Team')||rows[rows.length-1];if(!ctx)return false;lastProfileSig='';lastRosterSig='';let local=mergeContext(readLocal(),ctx);local.hardcourtNeedsTeamSetup=true;writeLocal(local);location.reload();return true}catch(e){console.warn('Hardcourt team create',e.message);return false}}
async function persistSnapshot(){if(persisting){persistAgain=true;return}persisting=true;try{if(!bootstrapClient||!navigator.onLine)return;const session=(await bootstrapClient.auth.getSession()).data?.session;if(!session?.user)return;let s=readLocal();if(!s.cloudTeamId||!s.cloudSeasonId)return;const profileSig=JSON.stringify([s.cloudTeamId,s.team,s.grade,s.primary,s.accent,s.teamLogo||'']);if(profileSig!==lastProfileSig&&s.team){const r=await bootstrapClient.rpc('update_hardcourt_team_profile',{p_team_id:s.cloudTeamId,p_name:s.team,p_grade:s.grade||'',p_primary:s.primary||'#111111',p_accent:s.accent||'#39a852',p_logo_data:s.teamLogo||null});if(r.error)console.warn('Hardcourt team profile sync',r.error.message);else lastProfileSig=profileSig}const roster=Array.isArray(s.roster)?s.roster:[],rosterSig=JSON.stringify([s.cloudSeasonId,...roster.map(p=>[p.cloudId||'',String(p.num||''),p.name||''])]);if(rosterSig!==lastRosterSig){const r=await bootstrapClient.rpc('sync_hardcourt_roster',{p_season_id:s.cloudSeasonId,p_players:roster.map(p=>({cloudId:p.cloudId||null,jersey:String(p.num||''),name:String(p.name||'Player')}))});if(r.error)console.warn('Hardcourt roster persistence',r.error.message);else{s=applySyncedRoster(s,r.data);writeLocal(s);lastRosterSig=JSON.stringify([s.cloudSeasonId,...(s.roster||[]).map(p=>[p.cloudId||'',String(p.num||''),p.name||''])])}}}finally{persisting=false;accountStatus?.refresh?.();if(persistAgain){persistAgain=false;schedulePersist()}}}
function schedulePersist(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>persistSnapshot().catch(e=>console.warn('Hardcourt persistence',e)),500)}localStorage.setItem=function(key,value){nativeSet(key,value);if(!bootstrapping&&key===STATE_KEY)schedulePersist()};
if(window.supabase?.createClient){bootstrapClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,authOptions);let session=(await bootstrapClient.auth.getSession()).data?.session;if(!session?.user){const {runHardcourtAccountGate}=await import('./account-gate.js');await runHardcourtAccountGate(bootstrapClient);session=(await bootstrapClient.auth.getSession()).data?.session}if(session?.user){await ensureAccountContext(bootstrapClient,session.user);if(readLocal().hardcourtNeedsTeamSetup){const {runHardcourtOnboarding}=await import('./onboarding.js');await runHardcourtOnboarding(bootstrapClient,{readLocal,writeLocal});try{await loadContexts(bootstrapClient)}catch{}}}}
bootstrapping=false;await import('./legacy-app.js');
if(bootstrapClient){const session=(await bootstrapClient.auth.getSession()).data?.session;if(session?.user){try{await loadContexts(bootstrapClient)}catch{}const {installBleacherAccountHub}=await import('./account-hub.js');installBleacherAccountHub({sb:bootstrapClient,readLocal,getHardcourtTeams:()=>cloudContexts,switchHardcourtTeam,createAnotherHardcourtTeam});const {installAccountStatus}=await import('./account-status.js');accountStatus=installAccountStatus({sb:bootstrapClient,readLocal,getHardcourtTeams:()=>cloudContexts});const {installHardcourtRuntimeBridge}=await import('./runtime-bridge.js');installHardcourtRuntimeBridge()}bootstrapClient.auth.onAuthStateChange(async(event)=>{if(event==='SIGNED_OUT')location.reload()})}
window.addEventListener('online',()=>{persistSnapshot().catch(()=>{});setTimeout(()=>loadContexts(bootstrapClient).catch(()=>{}),700)});document.addEventListener('visibilitychange',()=>{if(document.hidden)persistSnapshot().catch(()=>{});else if(bootstrapClient)loadContexts(bootstrapClient).catch(()=>{})});window.addEventListener('pagehide',()=>{clearTimeout(persistTimer);persistSnapshot().catch(()=>{})});
