// Hardcourt persistent-account helpers.
// Kept separate from the game engine so account/team UX can evolve without destabilizing live stat entry.
const BBS_PREF='bbs-account-preferences';
function readBbs(){try{return JSON.parse(localStorage.getItem(BBS_PREF)||'{}')}catch{return{}}}
function writeBbs(patch){try{localStorage.setItem(BBS_PREF,JSON.stringify({...readBbs(),...patch,updatedAt:Date.now()}))}catch{}}
const clean=v=>String(v??'').trim(),validTeam=t=>!!(t?.teamId||t?.team_id)&&clean(t?.teamName||t?.team_name).toLowerCase()!=='my team';
export async function loadHardcourtTeams(sb){const {data,error}=await sb.rpc('get_hardcourt_cloud_context');if(error)throw error;return(Array.isArray(data)?data:[]).filter(validTeam)}
export async function createHardcourtTeam(sb,profile){const name=clean(profile?.name);if(!name||name.toLowerCase()==='my team')throw new Error('Enter a team name before creating the team.');const {data,error}=await sb.rpc('create_hardcourt_team',{p_name:name,p_grade:clean(profile?.grade),p_primary:profile?.primary||'#111111',p_accent:profile?.accent||'#39a852'});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.team_id||!row?.season_id)throw new Error('The team was not created correctly. Please try again.');return row}
export function rememberHardcourtTeam(teamId){if(!teamId)return;localStorage.setItem('hardcourt-active-team-id',String(teamId));writeBbs({lastHardcourtTeam:String(teamId),lastEdition:'hardcourt'})}
export function preferredHardcourtTeam(contexts){const valid=(contexts||[]).filter(validTeam);if(!valid.length)return null;const bbs=readBbs(),remembered=bbs.lastHardcourtTeam||localStorage.getItem('hardcourt-active-team-id');return valid.find(x=>String(x.teamId||x.team_id)===String(remembered))||valid[0]}
export async function persistHardcourtRoster(sb,seasonId,roster){if(!seasonId)throw new Error('No active Hardcourt season is available.');const players=(roster||[]).map(p=>({cloudId:p.cloudId||null,jersey:clean(p.num),name:clean(p.name)})).filter(p=>p.name||p.jersey);if(players.some(p=>!p.name))throw new Error('Each roster entry needs a player name.');const nums=players.map(p=>p.jersey.toLowerCase()).filter(Boolean),dupe=nums.find((n,i)=>nums.indexOf(n)!==i);if(dupe)throw new Error(`Jersey number ${dupe} is entered more than once.`);const {data,error}=await sb.rpc('sync_hardcourt_roster',{p_season_id:seasonId,p_players:players});if(error)throw error;return Array.isArray(data)?data:[]}
export function applyCloudRoster(rows,existing=[]){const safe=(rows||[]).filter(r=>r&&(r.id||r.cloudId)&&clean(r.name)),priorByCloud=new Map(existing.filter(p=>p.cloudId).map(p=>[String(p.cloudId),p]));return safe.map((r,i)=>{const id=String(r.id||r.cloudId),old=priorByCloud.get(id)||existing.find(p=>String(p.num)===String(r.jersey??r.jersey_number??'')&&clean(p.name).toLowerCase()===clean(r.name).toLowerCase());return{id:old?.id||`p${i}`,num:r.jersey??r.jersey_number??'',name:clean(r.name),headshot:old?.headshot||'',cloudId:r.id||r.cloudId}})}
