// Offers recovery only when the current game is empty and a recent local checkpoint has real stat data.
export function installHardcourtRecoveryUi({readLocal=()=>({})}={}){
 const RECOVERY='hardcourt-recovery-games',STATE='hardcourt-alpha',DISMISSED='hardcourt-recovery-dismissed',TTL=1000*60*60*24*7;
 const parse=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'')||f}catch{return f}},validEvents=x=>Array.isArray(x)?x.filter(e=>e&&typeof e==='object'):[],teamId=x=>String(x?.cloudTeamId||x?.teamId||'local');
 document.getElementById('hcRecovery')?.remove();const current=readLocal()||{};if(validEvents(current.events).length||current.running)return;
 const dismissed=parse(DISMISSED,[]),dismissKey=x=>`${String(x.teamId||'local')}::${String(x.gameId||'')}`,now=Date.now(),activeTeam=teamId(current),activeSeason=String(current.cloudSeasonId||'');let rows=parse(RECOVERY,[]).filter(x=>x&&validEvents(x.events).length&&Number(x.savedAt)>0&&now-Number(x.savedAt)<TTL&&!dismissed.includes(dismissKey(x))&&!dismissed.includes(x.gameId)&&String(x.teamId||'local')===activeTeam&&(!activeSeason||!x.seasonId||String(x.seasonId)===activeSeason));if(!rows.length)return;
 const currentId=String(current.gameId||''),differentGame=rows.filter(x=>String(x.gameId||'')!==currentId),pool=differentGame.length?differentGame:rows;const snap=pool.sort((a,b)=>Number(b.savedAt||0)-Number(a.savedAt||0))[0],events=validEvents(snap.events);if(!events.length)return;
 const style=document.createElement('style');style.textContent=`#hcRecovery{position:fixed;inset:0;z-index:100020;display:grid;place-items:center;padding:18px;background:#000b;font-family:Inter,-apple-system,sans-serif}#hcRecovery>div{width:min(430px,100%);padding:20px;border:1px solid #3e5549;border-radius:18px;background:#0b120f;color:#fff;box-shadow:0 24px 80px #000c}#hcRecovery h2{margin:0 0 7px;font-size:20px}#hcRecovery p{margin:0 0 14px;color:#b4c1ba;font-size:12px;line-height:1.45}.hc-rec-meta{padding:11px;border-radius:10px;background:#111d17;color:#d8e4dc;font-size:11px}.hc-rec-note{margin-top:10px;color:#87978e;font-size:10px;line-height:1.4}.hc-rec-actions{display:flex;gap:8px;margin-top:14px}.hc-rec-actions button{flex:1;padding:11px;border-radius:9px;font-weight:900}.hc-rec-actions button:disabled{opacity:.55}.hc-rec-restore{border:0;background:#38b96a;color:#041108}.hc-rec-dismiss{border:1px solid #43534b;background:#18211d;color:#fff}@media(max-width:520px){#hcRecovery{padding:10px}#hcRecovery>div{padding:17px}.hc-rec-actions{flex-direction:column-reverse}.hc-rec-actions button{min-height:44px}}`;document.head.appendChild(style);
 const root=document.createElement('div');root.id='hcRecovery';const when=new Date(Number(snap.savedAt)).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}),clock=Math.max(0,Number(snap.clockMs||0)),mins=Math.floor(clock/60000),secs=String(Math.floor(clock%60000/1000)).padStart(2,'0');root.innerHTML=`<div role="dialog" aria-modal="true" aria-labelledby="hcRecoveryTitle"><h2 id="hcRecoveryTitle">Resume interrupted game?</h2><p>Hardcourt found a recent checkpoint for this team while the current game is empty.</p><div class="hc-rec-meta"><strong>${escapeHtml(snap.team||current.team||'Your Team')} vs ${escapeHtml(snap.opponent||'Opponent')}</strong><br>${events.length} recorded event${events.length===1?'':'s'} · Period ${Math.max(1,Number(snap.period||1))} · ${mins}:${secs} remaining<br>Saved ${escapeHtml(when)}</div><div class="hc-rec-note">Resume restores this local checkpoint with the clock stopped. Start Fresh hides this checkpoint on this device without deleting it.</div><div class="hc-rec-actions"><button class="hc-rec-dismiss" type="button">Start Fresh</button><button class="hc-rec-restore" type="button">Resume Game</button></div></div>`;document.body.appendChild(root);root.querySelector('.hc-rec-restore')?.focus();let busy=false;
 const dismiss=()=>{if(busy)return;const d=parse(DISMISSED,[]),key=dismissKey(snap);localStorage.setItem(DISMISSED,JSON.stringify([...new Set([...d,key])].slice(-30)));root.remove()};root.querySelector('.hc-rec-dismiss').onclick=dismiss;
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();dismiss()}});
 root.querySelector('.hc-rec-restore').onclick=e=>{if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);e.currentTarget.textContent='RESTORING…';const s=readLocal()||{};if(validEvents(s.events).length||s.running||teamId(s)!==activeTeam||(activeSeason&&String(s.cloudSeasonId||'')!==activeSeason)){root.remove();return}const next={...s,gameId:snap.gameId||s.gameId,cloudGameId:snap.cloudGameId||null,opponent:snap.opponent||s.opponent||'Opponent',period:Math.max(1,Number(snap.period||1)),clockMs:Math.max(0,Number(snap.clockMs||0)),events,minutes:snap.minutes&&typeof snap.minutes==='object'&&!Array.isArray(snap.minutes)?snap.minutes:{},teamScore:Math.max(0,Number(snap.teamScore||0)),opponentScore:Math.max(0,Number(snap.opponentScore||0)),running:false,lastTick:null,pendingShot:null,pendingAction:null,selectedPlayer:null,selectedAction:null,shotAssistPending:null,reboundPending:null};localStorage.setItem(STATE,JSON.stringify(next));location.reload()};
 function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
}
