// Final compatibility bridge between the mature stat runtime and the BBS account shell.
// Legacy account/auth/demo controls are retired here; live stat entry remains untouched.
export function installHardcourtRuntimeBridge({readLocal=()=>({})}={}){
 const STATE='hardcourt-alpha',DEMO_KEYS=['hardcourt-demo','hardcourt-sample-team','hardcourt-preloaded-team'];
 const openShared=()=>{if(typeof window.openBleacherButtAccount==='function'){window.openBleacherButtAccount();return true}return false};
 const demoNames=new Set(['Mason Reed','Liam Carter','Noah Brooks','Ethan Hayes','Caleb Turner','Owen Parker','Jack Bennett','Luke Foster','Henry Collins','Wyatt Cooper','Abe','Max','Cole','Sam','Jack','Ben','Luke','Noah','Eli','Ryan']);
 const hasGameData=s=>Array.isArray(s?.events)&&s.events.length>0;
 const hasCloudIdentity=s=>!!(s?.cloudTeamId&&s?.cloudSeasonId);
 function safeWrite(before,next){if(hasGameData(before)||JSON.stringify(before)===JSON.stringify(next))return false;try{localStorage.setItem(STATE,JSON.stringify(next));return true}catch{return false}}
 function migratePrototypeState(){const s=readLocal();if(!s||hasGameData(s)||hasCloudIdentity(s))return;let next={...s},changed=false;const team=String(next.team||'').trim(),opp=String(next.opponent||next.opp||'').trim();if(/^(Erie Elite|Longmont|Home Team|My Team)$/i.test(team)){next.team='';changed=true}if(/^(Longmont|Away Team)$/i.test(opp)){next.opponent='Opponent';if('opp'in next)next.opp='Opponent';changed=true}const r=Array.isArray(next.roster)?next.roster:[],looksDemo=r.length>=5&&r.every((p,i)=>!p?.cloudId&&(demoNames.has(String(p?.name||''))||String(p?.name||'')===`Player ${i+1}`));if(looksDemo){next.roster=[];next.active=[];changed=true}if(changed)safeWrite(s,next);for(const key of DEMO_KEYS)try{localStorage.removeItem(key)}catch{}}
 function retireLegacyUi(){for(const id of ['cloudStatus','liveCloudStatus'])document.getElementById(id)?.remove();document.querySelectorAll('[data-demo],[data-sample]').forEach(x=>x.remove());const account=document.getElementById('accountBtn');if(account){account.textContent='⚙ Bleacher Butt Stats';account.setAttribute('aria-label','Open Bleacher Butt Stats account and teams')}const settings=document.getElementById('settingsAccount');if(settings){settings.textContent='Bleacher Butt Stats Account';settings.setAttribute('aria-label','Open Bleacher Butt Stats account and teams')}document.querySelectorAll('[data-account-action],button[data-auth]').forEach(b=>{if(b.id==='bbsHubBtn')return;const t=(b.textContent||'').trim();if(/Sign In|Create Account|Account|Sign Out/i.test(t)){b.textContent='Bleacher Butt Stats Account';b.setAttribute('aria-label','Open Bleacher Butt Stats account and teams')}})}
 migratePrototypeState();retireLegacyUi();
 document.addEventListener('click',e=>{const target=e.target?.closest?.('#accountBtn,#settingsAccount,[data-account-action],button[data-auth]');if(!target||target.id==='bbsHubBtn')return;if(openShared()){e.preventDefault();e.stopImmediatePropagation()}},true);
 let destroyed=false,queued=false;const relevant=n=>n?.nodeType===1&&(n.matches?.('#accountBtn,#settingsAccount,[data-demo],[data-sample],[data-account-action],button[data-auth],#cloudStatus,#liveCloudStatus')||n.querySelector?.('#accountBtn,#settingsAccount,[data-demo],[data-sample],[data-account-action],button[data-auth],#cloudStatus,#liveCloudStatus'));const schedule=()=>{if(queued||destroyed)return;queued=true;(globalThis.requestAnimationFrame||setTimeout)(()=>{queued=false;if(!destroyed)retireLegacyUi()})};const observer=new MutationObserver(records=>{if(records.some(r=>r.type==='characterData'?!!r.parentElement?.closest?.('#accountBtn,#settingsAccount,[data-account-action],button[data-auth]'):[...r.addedNodes].some(relevant)))schedule()});observer.observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('storage',e=>{if(e.key===STATE){migratePrototypeState();schedule()}});window.addEventListener('pageshow',()=>{destroyed=false;migratePrototypeState();retireLegacyUi()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){destroyed=false;migratePrototypeState();retireLegacyUi()}});window.addEventListener('pagehide',()=>{destroyed=true;queued=false});return{destroy(){destroyed=true;observer.disconnect()}};
}
