// Compatibility bridge while the mature game runtime is progressively separated from its old account UI.
// Keeps proven stat entry intact while removing prototype account/demo behavior from the user experience.
export function installHardcourtRuntimeBridge({readLocal=()=>({})}={}){
 const STATE='hardcourt-alpha';const openShared=()=>{if(typeof window.openBleacherButtAccount==='function'){window.openBleacherButtAccount();return true}return false};
 const demoNames=new Set(['Mason Reed','Liam Carter','Noah Brooks','Ethan Hayes','Caleb Turner','Owen Parker','Jack Bennett','Luke Foster','Henry Collins','Wyatt Cooper','Abe','Max','Cole','Sam','Jack','Ben','Luke','Noah','Eli','Ryan']);
 const hasRealIdentity=s=>!!(s?.cloudTeamId||s?.cloudSeasonId||String(s?.team||'').trim()&&!/^(Erie Elite|Longmont|Home Team|My Team)$/i.test(String(s?.team||'').trim()));
 const hasGameData=s=>Array.isArray(s?.events)&&s.events.length>0;
 function safeWrite(before,next){if(hasGameData(before))return false;if(JSON.stringify(before)===JSON.stringify(next))return false;try{localStorage.setItem(STATE,JSON.stringify(next));return true}catch{return false}}
 function scrubPrototypeRoster(){const s=readLocal();if(!s||hasGameData(s)||hasRealIdentity(s))return;const r=Array.isArray(s.roster)?s.roster:[];const looksDemo=r.length>=5&&r.every((p,i)=>!p?.cloudId&&(demoNames.has(String(p?.name||''))||String(p?.name||'')===`Player ${i+1}`));if(looksDemo)safeWrite(s,{...s,roster:[],active:[]})}
 function scrubPrototypeGameLabels(){const s=readLocal();if(!s||hasGameData(s)||hasRealIdentity(s))return;const patches={};if(/^(Erie Elite|Longmont|Home Team|My Team)$/i.test(String(s.team||'').trim()))patches.team='';if(/^(Longmont|Away Team)$/i.test(String(s.opponent||'').trim()))patches.opponent='Opponent';if(Object.keys(patches).length)safeWrite(s,{...s,...patches})}
 function scrubPrototypeStorage(){const s=readLocal();if(!s||hasGameData(s)||hasRealIdentity(s))return;for(const key of ['hardcourt-demo','hardcourt-sample-team','hardcourt-preloaded-team'])try{localStorage.removeItem(key)}catch{}}
 function scrub(){scrubPrototypeRoster();scrubPrototypeGameLabels();scrubPrototypeStorage()}
 scrub();
 document.addEventListener('click',e=>{const target=e.target?.closest?.('#accountBtn,#settingsAccount');if(!target)return;if(openShared()){e.preventDefault();e.stopImmediatePropagation()}},true);
 let normalizing=false,destroyed=false,queued=false,lastFingerprint='';const fingerprint=()=>{const a=document.getElementById('accountBtn'),s=document.getElementById('settingsAccount'),cloud=document.getElementById('cloudStatus'),live=document.getElementById('liveCloudStatus');return[a?.textContent||'',s?.textContent||'',cloud?.style?.display||'',live?.style?.display||'',document.querySelectorAll('[data-demo],[data-sample]').length].join('|')};const normalize=(force=false)=>{if(normalizing||destroyed)return;const fp=fingerprint();if(!force&&fp===lastFingerprint)return;normalizing=true;try{const account=document.getElementById('accountBtn');if(account){account.textContent='⚙ Bleacher Butt Stats';account.setAttribute('aria-label','Open Bleacher Butt Stats account and teams')}const settings=document.getElementById('settingsAccount');if(settings)settings.textContent='Bleacher Butt Stats Account';for(const id of ['cloudStatus','liveCloudStatus']){const cloud=document.getElementById(id);if(cloud)cloud.style.display='none'}document.querySelectorAll('[data-demo],[data-sample]').forEach(x=>x.style.display='none');const candidates=document.querySelectorAll('#accountBtn,#settingsAccount,[data-account-action],button[data-auth]');candidates.forEach(b=>{const t=(b.textContent||'').trim();if(/Sign In\s*\/\s*Create Account/i.test(t)||(/^Account$/i.test(t)&&b.id!=='bbsHubBtn'))b.textContent='Bleacher Butt Stats Account'})}finally{normalizing=false;lastFingerprint=fingerprint()}};
 normalize(true);const scheduleNormalize=(delayFrame=true)=>{if(queued||destroyed)return;queued=true;const run=()=>{queued=false;normalize()};if(delayFrame&&typeof requestAnimationFrame==='function')requestAnimationFrame(run);else setTimeout(run,0)};const observer=new MutationObserver(records=>{if(destroyed)return;const relevant=records.some(r=>{if(r.type==='characterData')return r.parentElement?.closest?.('#accountBtn,#settingsAccount,[data-account-action],button[data-auth]');return[...r.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('#accountBtn,#settingsAccount,[data-demo],[data-sample],[data-account-action],button[data-auth],#cloudStatus,#liveCloudStatus')||n.querySelector?.('#accountBtn,#settingsAccount,[data-demo],[data-sample],[data-account-action],button[data-auth],#cloudStatus,#liveCloudStatus')))});if(relevant)scheduleNormalize()});observer.observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('storage',e=>{if(e.key===STATE){scrub();scheduleNormalize(false)}});window.addEventListener('pageshow',()=>{destroyed=false;scrub();normalize(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden){destroyed=false;scrub();normalize(true)}});window.addEventListener('pagehide',()=>{destroyed=true;queued=false});return{destroy(){destroyed=true;observer.disconnect()}};
}
