// Bleacher Butt Stats umbrella launcher. One identity -> editions -> teams -> games.
const KEY='bbs-umbrella-choice';
export function installBleacherUmbrella({sb,hardcourtContexts=()=>[],onHardcourt=()=>{}}={}){
 const qs=new URLSearchParams(location.search);const force=qs.get('umbrella')==='1';
 const style=document.createElement('style');style.textContent=`#bbsUmbrella{position:fixed;inset:0;z-index:100100;display:none;overflow:auto;padding:18px;background:radial-gradient(circle at 50% 0,#183229,#07110d 42%,#020403);font-family:Inter,-apple-system,sans-serif}#bbsUmbrella.open{display:block}.bbs-u-shell{width:min(760px,100%);margin:18px auto;color:#fff}.bbs-u-logo{text-align:center;margin-bottom:18px}.bbs-u-logo .mark{width:58px;height:58px;margin:auto;border:2px solid #70d996;border-radius:50%;display:grid;place-items:center;font-size:27px;font-weight:950}.bbs-u-logo h1{margin:9px 0 4px;font-size:28px;letter-spacing:.04em}.bbs-u-logo p{margin:0;color:#aebdb5;font-size:12px}.bbs-u-card{background:#fff;color:#10231a;border-radius:22px;padding:22px;box-shadow:0 24px 80px #0009}.bbs-u-card h2{margin:0 0 4px;font-size:22px}.bbs-u-sub{margin:0 0 16px;color:#718078;font-size:12px}.bbs-u-editions{display:grid;grid-template-columns:1fr 1fr;gap:12px}.bbs-u-edition{padding:18px;border:2px solid #dce5e0;border-radius:16px;background:#f8faf9;text-align:left;color:#10231a}.bbs-u-edition.available{border-color:#84c99d;background:#f3fbf5}.bbs-u-edition .icon{font-size:30px}.bbs-u-edition b{display:block;margin-top:8px;font-size:17px}.bbs-u-edition small{display:block;margin-top:3px;color:#738079;font-size:10px}.bbs-u-edition .state{display:inline-block;margin-top:12px;padding:5px 8px;border-radius:99px;background:#e6f7ec;color:#247644;font-size:9px;font-weight:950}.bbs-u-edition.add .state{background:#eef1ef;color:#66736c}.bbs-u-edition button{width:100%;margin-top:13px;padding:11px;border:0;border-radius:9px;background:#101713;color:#fff;font-weight:900}.bbs-u-foot{margin-top:14px;text-align:center;color:#829089;font-size:10px}.bbs-u-close{display:block;margin:12px auto 0;border:0;background:transparent;color:#c6d1cb;text-decoration:underline}@media(max-width:600px){#bbsUmbrella{padding:10px}.bbs-u-shell{margin:4px auto}.bbs-u-logo h1{font-size:23px}.bbs-u-card{padding:17px}.bbs-u-editions{grid-template-columns:1fr}.bbs-u-edition{padding:15px}}`;document.head.appendChild(style);
 const root=document.createElement('div');root.id='bbsUmbrella';document.body.appendChild(root);let session=null;
 async function render(){session=(await sb.auth.getSession()).data?.session;const hc=hardcourtContexts().filter(x=>x?.teamId),hasHC=hc.some(x=>x.teamName&&x.teamName!=='My Team');const gridironHint=!!session?.user?.user_metadata?.gridiron_access;root.innerHTML=`<div class="bbs-u-shell"><div class="bbs-u-logo"><div class="mark">B</div><h1>BLEACHER BUTT STATS</h1><p>Choose your sport.</p></div><div class="bbs-u-card"><h2>${hasHC||gridironHint?'Where are we headed?':'Choose your first edition'}</h2><p class="bbs-u-sub">One Bleacher Butt Stats account can use one sport or several. Each edition keeps its own teams, games and stats.</p><div class="bbs-u-editions"><div class="bbs-u-edition ${gridironHint?'available':'add'}"><div class="icon">🏈</div><b>Gridiron Edition</b><small>Football</small><span class="state">${gridironHint?'YOUR EDITION':'AVAILABLE TO ADD'}</span><button type="button" id="bbsOpenGridiron">${gridironHint?'Open Gridiron':'Explore Gridiron'}</button></div><div class="bbs-u-edition ${hasHC?'available':'add'}"><div class="icon">🏀</div><b>Hardcourt Edition</b><small>Basketball</small><span class="state">${hasHC?'YOUR EDITION':'AVAILABLE TO ADD'}</span><button type="button" id="bbsOpenHardcourt">${hasHC?'Open Hardcourt':'Add Hardcourt'}</button></div></div><div class="bbs-u-foot">Signed in as ${esc(session?.user?.email||'Bleacher Butt Stats member')}</div><button class="bbs-u-close" type="button">Stay in current edition</button></div></div>`;root.querySelector('#bbsOpenHardcourt').onclick=()=>{localStorage.setItem(KEY,'hardcourt');close();onHardcourt({hasAccess:hasHC})};root.querySelector('#bbsOpenGridiron').onclick=()=>{localStorage.setItem(KEY,'gridiron');location.href='../?from=bleacher-butt-stats'};root.querySelector('.bbs-u-close').onclick=close}
 function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 async function open(){await render();root.classList.add('open')}function close(){root.classList.remove('open')}
 window.openBleacherUmbrella=open;
 if(force)open();return{open,close};
}
