import{isThreePoint,rimZone,createEvent,derive}from"./engine.js";
const $=id=>document.getElementById(id),defaults=Array.from({length:10},(_,i)=>({id:"p"+i,num:[2,5,11,14,22,3,7,10,20,24][i],name:["Abe","Max","Cole","Sam","Jack","Ben","Luke","Noah","Eli","Ryan"][i],headshot:""}));
let stored;try{stored=JSON.parse(localStorage.getItem("hardcourt-alpha")||"null")}catch{stored=null}
let roster=(stored?.roster||defaults).map((p,i)=>({...defaults[i],...p})),state=stored||{events:[],active:roster.slice(0,5).map(x=>x.id),period:1,clockMs:480000,running:false,fast:false,offenseRight:true,minutes:{},lastTick:null,statsScope:"game",chartMode:"shots"};state.teamId??=globalThis.crypto?.randomUUID?.()||"team-"+Date.now();state.gameId??=globalThis.crypto?.randomUUID?.()||"game-"+Date.now();state.clientId??=localStorage.getItem("hardcourt-client-id")||globalThis.crypto?.randomUUID?.()||"local";localStorage.setItem("hardcourt-client-id",state.clientId);let timer;
function save(){localStorage.setItem("hardcourt-alpha",JSON.stringify({...state,running:false,lastTick:null,roster}))}
function initials(s){return String(s||"?").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function imgOrInitial(src,label){return src?'<img src="'+src+'" alt="">':initials(label)}
function fileData(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function setupRoster(){$("setupRoster").innerHTML=roster.map(p=>'<label class="roster-edit"><input type="checkbox" data-start="'+p.id+'" '+(state.active.includes(p.id)?"checked":"")+'><input data-num="'+p.id+'" value="'+p.num+'" aria-label="Jersey number"><input data-name="'+p.id+'" value="'+p.name+'" aria-label="Player name"><input type="file" accept="image/*" data-photo="'+p.id+'" aria-label="Headshot for '+p.name+'"></label>').join("");document.querySelectorAll("[data-photo]").forEach(x=>x.onchange=()=>fileData(x.files[0],d=>{roster.find(p=>p.id===x.dataset.photo).headshot=d;save()}))}
setupRoster();
["teamLogo","oppLogo"].forEach(id=>$(id).onchange=()=>fileData($(id).files[0],d=>{state[id]=d;save()}));
$("startGame").onclick=()=>{document.querySelectorAll("[data-name]").forEach(x=>roster.find(p=>p.id===x.dataset.name).name=x.value.trim()||"Player");document.querySelectorAll("[data-num]").forEach(x=>roster.find(p=>p.id===x.dataset.num).num=x.value);const a=[...document.querySelectorAll("[data-start]:checked")].map(x=>x.dataset.start);if(a.length!==5){$("setupError").textContent="Select exactly five starters.";return}Object.assign(state,{active:a,clockMs:+$("periodMinutes").value*60000,periodMinutes:+$("periodMinutes").value,periods:+$("periodMode").value,team:$("teamName").value,grade:$("gradeLevel").value,division:$("division").value,opp:$("oppName").value,primary:$("primaryColor").value,accent:$("accentColor").value,offenseRight:$("startDirection").value==="right"});startUI();save()};
function productHeaders(){document.querySelectorAll(".product-header").forEach(h=>h.innerHTML='<div class="header-team"><span class="score-logo">'+imgOrInitial(state.teamLogo,state.team)+'</span><b>'+state.team+'</b><small>'+[state.grade,state.division].filter(Boolean).join(" · ")+'</small></div>')}
function startUI(){$("setup").classList.add("hidden");$("shell").classList.remove("hidden");document.documentElement.style.setProperty("--primary",state.primary||"#111");document.documentElement.style.setProperty("--accent",state.accent||"#39a852");$("homeLabel").textContent=[state.team,state.grade].filter(Boolean).join(" · ");$("awayLabel").textContent=state.opp||"Opponent";$("homeLogo").innerHTML=imgOrInitial(state.teamLogo,state.team);$("awayLogo").innerHTML=imgOrInitial(state.oppLogo,state.opp);$("ourGroupLabel").textContent=(state.team||"Our Team").toUpperCase();$("oppGroupLabel").textContent=(state.opp||"Opponent").toUpperCase();$("activeTeamLabel").textContent=(state.team||"TEAM")+" · ON COURT";productHeaders();populateShotFilters();applyDirection();render()}if(state.team)startUI();
function fmt(ms){let s=Math.max(0,Math.ceil(ms/1000));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function accrue(){if(!state.running||!state.lastTick)return;const now=Date.now(),d=Math.min(now-state.lastTick,state.clockMs);state.lastTick=now;state.clockMs=Math.max(0,state.clockMs-d);state.active.forEach(id=>state.minutes[id]=(state.minutes[id]||0)+d);if(state.clockMs<=0){state.running=false;state.lastTick=null;clearInterval(timer)}}
function startClock(){if(!state.running&&state.clockMs>0){state.running=true;state.lastTick=Date.now();timer=setInterval(()=>{accrue();render()},250);render()}}function stopClock(){if(state.running){accrue();state.running=false;state.lastTick=null;clearInterval(timer);save();render()}}$("startClock").onclick=startClock;$("stopClock").onclick=stopClock;
function render(){const d=derive(state.events,roster);renderSecondary(d);$("homeScore").textContent=d.us;$("awayScore").textContent=d.them;$("clock").textContent=fmt(state.clockMs);$("periodLabel").textContent=(state.periods===2?"H":"Q")+state.period;$("fastBtn").classList.toggle("armed",state.fast);$("startClock").classList.toggle("clock-active",state.running);$("stopClock").classList.toggle("clock-active",!state.running);$("nextPeriod").classList.toggle("period-ready",state.clockMs<=0);$("activeFive").innerHTML=state.active.map(id=>{const p=roster.find(x=>x.id===id),s=d.players[id];return'<button class="player-tile">#'+p.num+" "+p.name+"<small>"+s.pts+" pts · "+fmt(state.minutes[id]||0)+"</small></button>"}).join("");save()}
$("fastBtn").onclick=()=>{state.fast=!state.fast;render()};$("undoBtn").onclick=()=>{state.events.pop();render()};
const court=$("court");court.onclick=e=>{if(e.target.closest(".overlay,.controls,.offense-tools,.game-manage"))return;const r=court.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if((state.offenseRight&&x<.5)||(!state.offenseRight&&x>.5))return;shotPopup(x,y,e.clientX-r.left,e.clientY-r.top)};
function clearPendingShot(){$("shotPrompt").classList.add("hidden");document.querySelector(".shot-marker")?.remove()}
function shotPopup(x,y,left,top){clearPendingShot();const three=isThreePoint(x,y,state.offenseRight),o=$("shotPrompt"),m=document.createElement("i");m.className="shot-marker";m.style.left=x*100+"%";m.style.top=y*100+"%";court.appendChild(m);const ow=Math.min(300,court.clientWidth-16);o.style.width=ow+"px";o.style.left=Math.max(8,Math.min(left-ow/2,court.clientWidth-ow-8))+"px";o.style.top=Math.max(8,Math.min(top-110,court.clientHeight-230))+"px";o.classList.remove("hidden");o.innerHTML='<div class="shot-head"><b>'+(three?"3PT":"2PT")+' attempt</b><button class="shot-close">×</button></div><div class="shot-grid">'+state.active.map(id=>{const p=roster.find(x=>x.id===id);return'<button data-shot="'+id+'" data-made="1">#'+p.num+" "+p.name+' · MAKE</button><button data-shot="'+id+'" data-made="0">#'+p.num+" "+p.name+" · MISS</button>"}).join("")+"</div>";o.querySelector(".shot-close").onclick=e=>{e.stopPropagation();clearPendingShot()};o.querySelectorAll("[data-shot]").forEach(b=>b.onclick=()=>{const made=b.dataset.made==="1";state.events.push(createEvent("shot",{playerId:b.dataset.shot,made,three,x,y,rimZone:rimZone(x,y,state.offenseRight),fastBreak:state.fast,lineup:[...state.active]},state));state.fast=false;clearPendingShot();render();made?promptAssist(b.dataset.shot):promptMissRebound()})}
function modal(title,choices,cb){openModal(title,'<div class="choices">'+choices.map(x=>'<button class="choice" data-choice="'+x.value+'">'+x.label+"</button>").join("")+"</div>");document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{closeModal();cb(b.dataset.choice)})}
function openModal(t,b){$("modalTitle").textContent=t;$("modalBody").innerHTML=b;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}$("modalClose").onclick=closeModal;
function choosePlayer(title,type){modal(title,state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:"#"+p.num+" "+p.name,value:id}}),id=>{state.events.push(createEvent(type,{playerId:id,lineup:[...state.active]},state));render()})}
$("turnoverBtn").onclick=()=>choosePlayer("Turnover","turnover");$("stealBtn").onclick=()=>choosePlayer("Steal","steal");$("reboundBtn").onclick=()=>choosePlayer("Rebound","rebound");$("blockBtn").onclick=()=>choosePlayer("Block","block");$("foulBtn").onclick=foulFlow;
function foulFlow(){modal("Foul by",[{label:state.team,value:"us"},{label:state.opp,value:"opp"}],side=>{if(side==="us")modal("Who committed the foul?",state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:"#"+p.num+" "+p.name,value:id}}),id=>{state.events.push(createEvent("foul",{playerId:id,lineup:[...state.active]},state));foulSituation("opp")});else{state.events.push(createEvent("foul",{team:"opponent",lineup:[...state.active]},state));foulSituation("us")}})}
function foulSituation(side){modal("Foul situation",[{label:"Non-shooting · no free throws",value:"none"},{label:"Shooting foul · 2 shots",value:"2"},{label:"Shooting foul · 3 shots",value:"3"},{label:"And-one · 1 shot",value:"1"},{label:"Bonus · 1-and-1",value:"11"},{label:"Double bonus · 2 shots",value:"2b"},{label:"Technical · 2 shots",value:"2t"}],kind=>{if(kind==="none"){render();return}const n=kind==="3"?3:kind==="1"?1:2;if(side==="us")modal("Free-throw shooter",state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:"#"+p.num+" "+p.name,value:id}}),id=>freeThrowBoard("us",id,n,kind==="11"));else freeThrowBoard("opp",null,n,kind==="11")})}
function freeThrowBoard(side,playerId,total,oneAndOne=false){const who=side==="us"?roster.find(p=>p.id===playerId)?.name:state.opp,results=Array(total).fill(null);openModal(who+" · Free Throws","");const draw=()=>{const secondLocked=oneAndOne&&results[0]!=="make";$("modalBody").innerHTML='<div class="ft-board">'+results.map((v,i)=>'<div class="ft-row"><b>FT '+(i+1)+'</b><button class="ft-choice make '+(v==="make"?"selected":"")+'" data-ft="'+i+'" data-v="make" '+(i===1&&secondLocked?"disabled":"")+'>MAKE</button><button class="ft-choice miss '+(v==="miss"?"selected":"")+'" data-ft="'+i+'" data-v="miss" '+(i===1&&secondLocked?"disabled":"")+'>MISS</button></div>').join("")+'<button id="recordFT" class="primary ft-submit" '+((oneAndOne&&results[0]==="miss")||results.every(Boolean)?"":"disabled")+'>GOOD TO GO</button></div>';document.querySelectorAll("[data-ft]").forEach(b=>b.onclick=()=>{results[+b.dataset.ft]=b.dataset.v;if(oneAndOne&&+b.dataset.ft===0&&b.dataset.v==="miss")results[1]=null;draw()});$("recordFT").onclick=()=>{closeModal();const actual=oneAndOne&&results[0]==="miss"?results.slice(0,1):results;actual.forEach(v=>{const made=v==="make";if(side==="us")state.events.push(createEvent("free_throw",{playerId,made,lineup:[...state.active]},state));else if(made)state.events.push(createEvent("opp_score",{points:1,freeThrow:true,lineup:[...state.active]},state))});render();if(actual.at(-1)==="miss")promptMissRebound()}};draw()}
function promptAssist(shooter){const opts=state.active.filter(x=>x!==shooter).map(id=>({label:roster.find(p=>p.id===id).name,value:id}));opts.push({label:"None",value:"none"});modal("Assist?",opts,id=>{if(id!=="none")state.events.push(createEvent("assist",{playerId:id},state));render()})}
function promptMissRebound(){const opts=state.active.map(id=>({label:roster.find(p=>p.id===id).name,value:id}));opts.push({label:"Opponent",value:"opp"},{label:"Team / Dead Ball",value:"team"},{label:"None",value:"none"});modal("Rebound?",opts,id=>{if(id==="opp")state.events.push(createEvent("opp_rebound",{team:"opponent",lineup:[...state.active]},state));else if(id==="team")state.events.push(createEvent("team_rebound",{team:"us"},state));else if(id!=="none")state.events.push(createEvent("rebound",{playerId:id,lineup:[...state.active]},state));render()})}
document.addEventListener("click",e=>{if(e.target.id==="oppReb"){state.events.push(createEvent("opp_rebound",{team:"opponent",lineup:[...state.active]},state));render()}if(e.target.id==="opp2"||e.target.id==="opp3"){state.events.push(createEvent("opp_score",{points:e.target.id==="opp3"?3:2,lineup:[...state.active]},state));render()}if(e.target.id==="nextPeriod"&&state.period<state.periods){stopClock();state.period++;state.clockMs=(state.periodMinutes||8)*60000;if((state.periods===4&&state.period===3)||(state.periods===2&&state.period===2))state.offenseRight=!state.offenseRight;applyDirection();render()}});
$("timeoutBtn").onclick=stopClock;$("flipDirection").onclick=()=>{state.offenseRight=!state.offenseRight;clearPendingShot();applyDirection();render()};
$("subBtn").onclick=()=>{accrue();let draft=[...state.active],selected=null;openModal("Substitution","");const draw=()=>{const cp=draft.map(id=>roster.find(p=>p.id===id)),bench=roster.filter(p=>!draft.includes(p.id));$("modalBody").innerHTML='<div class="sub-board"><p>Tap a player on court, then the bench player coming in.</p><div class="sub-court"><h3>ON COURT · 5</h3><div class="sub-five">'+cp.map(p=>'<button class="sub-player '+(selected===p.id?"selected":"")+'" data-court-player="'+p.id+'">#'+p.num+"<br>"+p.name+"</button>").join("")+'</div></div><h3>BENCH</h3><div class="sub-bench-grid">'+bench.map(p=>'<button class="sub-player" data-bench-player="'+p.id+'">#'+p.num+"<br>"+p.name+"</button>").join("")+'</div><div class="sub-actions"><button id="resetSub" class="choice">Reset</button><button id="confirmLineup" class="primary">Confirm Substitution</button></div></div>';document.querySelectorAll("[data-court-player]").forEach(b=>b.onclick=()=>{selected=b.dataset.courtPlayer;draw()});document.querySelectorAll("[data-bench-player]").forEach(b=>b.onclick=()=>{if(!selected)return;draft=draft.map(id=>id===selected?b.dataset.benchPlayer:id);selected=null;draw()});$("resetSub").onclick=()=>{draft=[...state.active];selected=null;draw()};$("confirmLineup").onclick=()=>{state.active=[...draft];state.events.push(createEvent("lineup",{players:[...draft]},state));if(state.running)state.lastTick=Date.now();closeModal();render()}};draw()};
function renderSecondary(d){if(!$("statsBody"))return;$("rosterCards").innerHTML=roster.map(p=>'<div class="card"><span class="avatar">'+imgOrInitial(p.headshot,p.name)+'</span><div><b>#'+p.num+" "+p.name+"</b><br><small>"+(state.active.includes(p.id)?"On court":"Bench")+"</small></div></div>").join("");const elapsed=Math.max(0,((state.period-1)*(state.periodMinutes||8)*60000)+((state.periodMinutes||8)*60000-state.clockMs)),expected=elapsed*5,used=Object.values(state.minutes).reduce((a,b)=>a+b,0),bad=Math.abs(used-expected)>=1500;$("timeCheck").classList.toggle("hidden",!bad);$("timeCheck").textContent=bad?"⚠ Playing-time totals are out of sync with elapsed game time.":"";$("timeTable").innerHTML=roster.slice().sort((a,b)=>(state.minutes[b.id]||0)-(state.minutes[a.id]||0)).map(p=>{const m=state.minutes[p.id]||0,pct=elapsed?Math.min(100,Math.round(m/elapsed*100)):0;return'<div class="time-row"><b>#'+p.num+" "+p.name+"</b><span>"+fmt(m)+"</span><span>"+pct+'%</span><span class="time-bar"><i style="width:'+pct+'%"></i></span></div>'}).join("");$("statsBody").innerHTML=roster.map(p=>{const s=d.players[p.id];return'<tr><th data-player="'+p.id+'">#'+p.num+" "+p.name+"</th><td>"+fmt(state.minutes[p.id]||0)+"</td><td>"+s.pts+"</td><td>"+s.fgm+"/"+s.fga+"</td><td>"+s.threeM+"/"+s.threeA+"</td><td>"+s.ftM+"/"+s.ftA+"</td><td>"+s.reb+"</td><td>"+s.ast+"</td><td>"+s.stl+"</td><td>"+s.blk+"</td><td>"+s.to+"</td><td>"+s.pf+"</td><td>"+(s.plusMinus>0?"+":"")+s.plusMinus+"</td></tr>"}).join("");document.querySelectorAll("[data-player]").forEach(x=>x.onclick=()=>openPlayer(x.dataset.player,d));$("fastSummary").textContent=state.events.filter(e=>e.type==="shot"&&e.payload.fastBreak).length+" tagged fast-break attempts";renderShotAnalytics()}
function openPlayer(id,d){const p=roster.find(x=>x.id===id),s=d.players[id],shots=state.events.filter(e=>e.type==="shot"&&e.payload.playerId===id),m=shots.filter(e=>e.payload.made).length;$("playerDetail").innerHTML='<div class="player-hero"><span class="avatar">'+imgOrInitial(p.headshot,p.name)+'</span><div><h2>#'+p.num+" "+p.name+'</h2><p>'+scopeLabel()+'</p></div></div><div class="player-kpis">'+[["PTS",s.pts],["MIN",fmt(state.minutes[id]||0)],["REB",s.reb],["AST",s.ast],["FG",s.fgm+"/"+s.fga],["3PT",s.threeM+"/"+s.threeA],["FT",s.ftM+"/"+s.ftA],["+/-",(s.plusMinus>0?"+":"")+s.plusMinus]].map(x=>'<div class="kpi"><small>'+x[0]+'</small><b>'+x[1]+"</b></div>").join("")+'</div><h3>Shooting</h3><p>'+m+"/"+shots.length+" · "+(shots.length?Math.round(m/shots.length*100):0)+"%</p>";showView("playerView",null)}
$("backStats").onclick=()=>showView("statsView","stats");
function scopeLabel(){return({game:"Game",regular:"Regular Season",playoffs:"Playoffs",season:"Season Total"})[state.statsScope||"game"]}
$("statsScope").onclick=e=>{const b=e.target.closest("[data-scope]");if(!b)return;state.statsScope=b.dataset.scope;document.querySelectorAll("#statsScope button").forEach(x=>x.classList.toggle("active",x===b));render()};
function applyDirection(){document.querySelector(".half.left").classList.toggle("offense",!state.offenseRight);document.querySelector(".half.right").classList.toggle("offense",state.offenseRight);$("teamControls").classList.toggle("controls-right",!state.offenseRight);$("offenseTools").classList.toggle("offense-left",!state.offenseRight);$("gameManage").classList.toggle("manage-left",!state.offenseRight)}
function showView(id,tab){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(id).classList.remove("hidden");if(tab){document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.tab===tab))}document.body.classList.toggle("needs-portrait",id!=="gameView");render()}
document.querySelectorAll("nav [data-tab]").forEach(b=>b.onclick=()=>showView({game:"gameView",roster:"rosterView",time:"timeView",stats:"statsView",analytics:"analyticsView"}[b.dataset.tab],b.dataset.tab));
function populateShotFilters(){const s=$("shotPlayerFilter");s.innerHTML='<option value="team">Whole Team</option>'+roster.map(p=>'<option value="'+p.id+'">#'+p.num+" "+p.name+"</option>").join("");const per=$("shotPeriodFilter"),prefix=state.periods===2?"H":"Q";per.innerHTML='<option value="all">All</option>'+Array.from({length:state.periods||4},(_,i)=>'<option value="'+(i+1)+'">'+prefix+(i+1)+"</option>").join("");["shotPlayerFilter","shotTimeFilter","shotPeriodFilter","shotTypeFilter"].forEach(id=>$(id).onchange=renderShotAnalytics)}
function shotZone(e){let x=e.payload.x,y=e.payload.y;if(e.payload.rimZone)return e.payload.rimZone==="left_finish"?"Left Finish":e.payload.rimZone==="right_finish"?"Right Finish":"Center Rim";const bx=x>.5?1:0,dx=Math.abs(x-bx),dy=y-.5;if(!e.payload.three){if(dx<.28&&Math.abs(dy)<.22)return dy<-.07?"Left Paint":dy>.07?"Right Paint":"Center Paint";if(Math.abs(dy)>.25)return dy<0?"Left Baseline":"Right Baseline";return dy<-.08?"Left Wing Mid":dy>.08?"Right Wing Mid":"Top Midrange"}if(Math.abs(dy)>.36)return dy<0?"Left Corner 3":"Right Corner 3";return dy<-.13?"Left Wing 3":dy>.13?"Right Wing 3":"Top 3"}
function filteredShots(){let a=state.events.filter(e=>e.type==="shot"),pf=$("shotPlayerFilter")?.value||"team",tf=$("shotTimeFilter")?.value||"game",per=$("shotPeriodFilter")?.value||"all",sf=$("shotTypeFilter")?.value||"all";if(pf!=="team")a=a.filter(e=>e.payload.playerId===pf);if(tf!=="game"){const half=state.periods===2?1:2;a=a.filter(e=>tf==="first"?e.period<=half:e.period>half)}if(per!=="all")a=a.filter(e=>String(e.period)===per);if(sf!=="all")a=a.filter(e=>sf==="3"?e.payload.three:!e.payload.three);return a}
const zoneRects={"Left Corner 3":[0,0,.18,.18],"Left Wing 3":[.12,.18,.23,.27],"Top 3":[.28,.36,.18,.28],"Right Wing 3":[.65,.18,.23,.27],"Right Corner 3":[.82,0,.18,.18],"Left Baseline":[0,.72,.22,.28],"Right Baseline":[.78,.72,.22,.28],"Left Paint":[0,.27,.18,.16],"Center Paint":[0,.43,.18,.14],"Right Paint":[0,.57,.18,.16],"Left Finish":[.02,.35,.12,.12],"Center Rim":[.02,.44,.12,.12],"Right Finish":[.02,.53,.12,.12]};
function courtLines(){return '<div class="court-lines"><i class="a-mid"></i><i class="a-center"></i><i class="a-paint l"></i><i class="a-paint r"></i><i class="a-ft l"></i><i class="a-ft r"></i><i class="a-arc l"></i><i class="a-arc r"></i><i class="a-rim l"></i><i class="a-rim r"></i></div><img class="analytics-brand" src="../brand-field.png" alt="">'}
function renderShotAnalytics(){if(!$("analyticsCourt"))return;const shots=filteredShots(),made=shots.filter(e=>e.payload.made),threes=shots.filter(e=>e.payload.three),tm=threes.filter(e=>e.payload.made),twos=shots.filter(e=>!e.payload.three),twoM=twos.filter(e=>e.payload.made);$("shootingSummary").textContent="FG "+made.length+"/"+shots.length+" · "+(shots.length?Math.round(made.length/shots.length*100):0)+"% | 3PT "+tm.length+"/"+threes.length+" · "+(threes.length?Math.round(tm.length/threes.length*100):0)+"% | 2PT "+twoM.length+"/"+twos.length+" · "+(twos.length?Math.round(twoM.length/twos.length*100):0)+"%";const zones={};shots.forEach(e=>{const z=shotZone(e);zones[z]??={a:0,m:0,pts:0};zones[z].a++;if(e.payload.made){zones[z].m++;zones[z].pts+=e.payload.three?3:2}});let heat="";if(state.chartMode!=="shots")heat=Object.entries(zones).map(([z,v])=>{const r=zoneRects[z];if(!r)return"";const pct=v.m/v.a,confidence=Math.min(1,v.a/4),score=.5+(pct-.5)*confidence,cls=score<.28?"cold3":score<.4?"cold2":score<.48?"cold1":score<.55?"neutral":score<.67?"hot1":score<.78?"hot2":"hot3";return'<i class="heat-zone '+cls+'" style="left:'+r[0]*100+'%;top:'+r[1]*100+'%;width:'+r[2]*100+'%;height:'+r[3]*100+'%"></i>'}).join("");const dots=state.chartMode==="heat"?"":shots.map(e=>'<i class="shot-dot '+(e.payload.made?"make":"miss")+'" style="left:'+e.payload.x*100+'%;top:'+e.payload.y*100+'%"></i>').join("");$("analyticsCourt").innerHTML=heat+courtLines()+dots;$("zoneTable").innerHTML=Object.entries(zones).sort((a,b)=>b[1].a-a[1].a).map(([z,v])=>'<div class="zone-cell"><b>'+z+"</b><span>"+v.m+"/"+v.a+" · "+Math.round(v.m/v.a*100)+'%</span><small>'+(v.pts/v.a).toFixed(2)+" pts/shot · "+Math.round(v.a/shots.length*100)+"% of shots</small></div>").join("")||'<div class="zone-cell">No shots for these filters yet.</div>'}
$("chartMode").onclick=e=>{const b=e.target.closest("[data-chart]");if(!b)return;state.chartMode=b.dataset.chart;document.querySelectorAll("#chartMode button").forEach(x=>x.classList.toggle("active",x===b));renderShotAnalytics();save()};
window.addEventListener("pagehide",()=>{accrue();save()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running){stopClock()}});applyDirection();render();