import{isThreePoint,rimZone,createEvent,derive}from"./engine.js";
const $=id=>document.getElementById(id), defaults=Array.from({length:10},(_,i)=>({id:"p"+i,num:[2,5,11,14,22,3,7,10,20,24][i],name:["Abe","Max","Cole","Sam","Jack","Ben","Luke","Noah","Eli","Ryan"][i]}));
let stored=JSON.parse(localStorage.getItem("hardcourt-alpha")||"null"),roster=stored?.roster||defaults;
let state=stored||{events:[],active:roster.slice(0,5).map(x=>x.id),period:1,clockMs:480000,running:false,fast:false,offenseRight:true,minutes:{},lastTick:null}; let timer;
function save(){const safe={...state,running:false,lastTick:null,roster};localStorage.setItem("hardcourt-alpha",JSON.stringify(safe))}
window.addEventListener("pagehide",()=>{accrue();save()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running){accrue();state.running=false;clearInterval(timer);save();render()}});
function setupRoster(){$("setupRoster").innerHTML=roster.map(p=>`<label class="roster-edit"><input type="checkbox" data-start="${p.id}" ${state.active.includes(p.id)?"checked":""}><input data-num="${p.id}" value="${p.num}"><input data-name="${p.id}" value="${p.name}"></label>`).join("")} setupRoster();
$("startGame").onclick=()=>{document.querySelectorAll("[data-name]").forEach(x=>roster.find(p=>p.id===x.dataset.name).name=x.value);document.querySelectorAll("[data-num]").forEach(x=>roster.find(p=>p.id===x.dataset.num).num=x.value);const a=[...document.querySelectorAll("[data-start]:checked")].map(x=>x.dataset.start);if(a.length!==5){$("setupError").textContent="Select exactly five starters.";return}state.active=a;state.clockMs=+$("periodMinutes").value*60000;state.periodMinutes=+$("periodMinutes").value;state.periods=+$("periodMode").value;state.team=$("teamName").value;state.grade=$("gradeLevel").value;state.division=$("division").value;state.opp=$("oppName").value;state.primary=$("primaryColor").value;state.accent=$("accentColor").value;state.offenseRight=$("startDirection").value==="right";startUI();save()};
function startUI(){$("setup").classList.add("hidden");$("shell").classList.remove("hidden");document.documentElement.style.setProperty("--primary",state.primary||"#111");document.documentElement.style.setProperty("--accent",state.accent||"#39a852");$("homeLabel").textContent=[state.team,state.grade,state.division].filter(Boolean).join(" · ")||"Erie Elite";$("awayLabel").textContent=state.opp||"Opponent";$("ourGroupLabel").textContent=(state.team||"Our Team").toUpperCase();$("oppGroupLabel").textContent=(state.opp||"Opponent").toUpperCase();$("activeTeamLabel").textContent=(state.team||"TEAM")+" · ON COURT";populateShotFilters();applyDirection();render()} if(state.team)startUI();
function fmt(ms){let s=Math.max(0,Math.ceil(ms/1000));return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function accrue(){if(!state.running||!state.lastTick)return;const now=Date.now(),d=Math.min(now-state.lastTick,state.clockMs);state.lastTick=now;state.clockMs=Math.max(0,state.clockMs-d);for(const id of state.active)state.minutes[id]=(state.minutes[id]||0)+d;if(state.clockMs<=0){state.running=false;state.lastTick=null;clearInterval(timer)}} function tick(){accrue();render()}
function startClock(){if(!state.running&&state.clockMs>0){state.running=true;state.lastTick=Date.now();timer=setInterval(tick,250);render()}} function stopClock(){if(state.running){accrue();state.running=false;state.lastTick=null;clearInterval(timer);save();render()}} $("startClock").onclick=startClock;$("stopClock").onclick=stopClock;
function render(){const d=derive(state.events,roster);renderSecondary(d);$("homeScore").textContent=d.us;$("awayScore").textContent=d.them;$("clock").textContent=fmt(state.clockMs);$("periodLabel").textContent=(state.periods===2?"H":"Q")+state.period;$("fastBtn").classList.toggle("armed",state.fast);$("startClock").classList.toggle("clock-active",state.running);$("stopClock").classList.toggle("clock-active",!state.running);$("nextPeriod").classList.toggle("period-ready",state.clockMs<=0);$("activeFive").innerHTML=state.active.map(id=>{const p=roster.find(x=>x.id===id),s=d.players[id];return`<button class="player-tile">#${p.num} ${p.name}<small>${s.pts} pts · ${fmt(state.minutes[id]||0)}</small></button>`}).join("");const last=state.events.at(-1);$("recent").textContent=last?`Last: ${last.type} — ${JSON.stringify(last.payload)}`:"Ready.";save()}
$("fastBtn").onclick=()=>{state.fast=!state.fast;render()};$("undoBtn").onclick=()=>{state.events.pop();render()};
const court=$("court");court.onclick=e=>{if(e.target.closest(".overlay,.controls,.offense-tools,.game-manage"))return;const r=court.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if((state.offenseRight&&x<.5)||(!state.offenseRight&&x>.5))return;shotPopup(x,y,e.clientX-r.left,e.clientY-r.top)};
function clearPendingShot(){const o=$("shotPrompt");o.classList.add("hidden");document.querySelector(".shot-marker")?.remove()}
function shotPopup(x,y,left,top){clearPendingShot();const three=isThreePoint(x,y,state.offenseRight),o=$("shotPrompt"),marker=document.createElement("i");marker.className="shot-marker";marker.style.left=(x*100)+"%";marker.style.top=(y*100)+"%";court.appendChild(marker);const ow=Math.min(290,court.clientWidth-16),oh=Math.min(225,court.clientHeight-16);o.style.width=ow+"px";o.style.left=Math.max(8,Math.min(left-ow/2,court.clientWidth-ow-8))+"px";o.style.top=Math.max(8,Math.min(top-oh/2,court.clientHeight-oh-8))+"px";o.classList.remove("hidden");o.innerHTML=`<div class="shot-head"><b>${three?"3PT":"2PT"} attempt</b><button class="shot-close" aria-label="Cancel shot">×</button></div><div class="shot-grid">${state.active.map(id=>{const p=roster.find(x=>x.id===id);return`<button data-shot="${id}" data-made="1">#${p.num} ${p.name} ✓</button><button data-shot="${id}" data-made="0">#${p.num} ${p.name} ×</button>`}).join("")}</div>`;o.querySelector(".shot-close").onclick=e=>{e.stopPropagation();clearPendingShot()};o.querySelectorAll("[data-shot]").forEach(b=>b.onclick=()=>{const made=b.dataset.made==="1";state.events.push(createEvent("shot",{playerId:b.dataset.shot,made,three,x,y,rimZone:rimZone(x,y,state.offenseRight),fastBreak:state.fast,lineup:[...state.active]},state));state.fast=false;clearPendingShot();render();if(made)promptAssist(b.dataset.shot);else promptMissRebound()})}
function choosePlayer(title,type){modal(title,state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:`#${p.num} ${p.name}`,value:id}}),id=>{state.events.push(createEvent(type,{playerId:id,lineup:[...state.active]},state));render()})}
$("turnoverBtn").onclick=()=>choosePlayer("Turnover","turnover");$("stealBtn").onclick=()=>choosePlayer("Steal","steal");$("reboundBtn").onclick=()=>choosePlayer("Rebound","rebound");$("blockBtn").onclick=()=>choosePlayer("Block","block");$("foulBtn").onclick=()=>foulFlow();
function foulFlow(){modal("Foul by",[{label:state.team||"Our team",value:"us"},{label:state.opp||"Opponent",value:"opp"}],side=>{if(side==="us"){modal("Who committed the foul?",state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:"#"+p.num+" "+p.name,value:id}}),id=>{state.events.push(createEvent("foul",{playerId:id,lineup:[...state.active]},state));foulSituation("opp")})}else{state.events.push(createEvent("foul",{team:"opponent",lineup:[...state.active]},state));foulSituation("us")}})}
function foulSituation(side){modal("Foul situation",[{label:"Non-shooting · no free throws",value:"none"},{label:"Shooting foul · 2 shots",value:"2"},{label:"Shooting foul · 3 shots",value:"3"},{label:"And-one · 1 shot",value:"1"},{label:"Bonus · 1-and-1",value:"11"},{label:"Double bonus · 2 shots",value:"2b"},{label:"Technical · 2 shots",value:"2t"}],kind=>{if(kind==="none"){render();return}const n=kind==="3"?3:kind==="1"?1:2;if(side==="us")modal("Free-throw shooter",state.active.map(id=>{const p=roster.find(x=>x.id===id);return{label:"#"+p.num+" "+p.name,value:id}}),id=>freeThrowSequence("us",id,n,kind==="11"));else freeThrowSequence("opp",null,n,kind==="11")})}
function freeThrowSequence(side,playerId,total,oneAndOne=false,attempt=1){const who=side==="us"?roster.find(p=>p.id===playerId)?.name:(state.opp||"Opponent");modal(who+" · Free throw "+attempt+" of "+total,[{label:"✓ Made",value:"make"},{label:"× Missed",value:"miss"}],result=>{const made=result==="make";if(side==="us")state.events.push(createEvent("free_throw",{playerId,made,lineup:[...state.active]},state));else if(made)state.events.push(createEvent("opp_score",{points:1,freeThrow:true,lineup:[...state.active]},state));render();if(oneAndOne&&attempt===1&&!made){promptMissRebound();return}if(attempt<total)freeThrowSequence(side,playerId,total,oneAndOne,attempt+1);else if(!made)promptMissRebound()})}
document.addEventListener("click",e=>{if(e.target.id==="oppReb"){state.events.push(createEvent("opp_rebound",{team:"opponent",lineup:[...state.active]},state));render()}if(e.target.id==="opp2"||e.target.id==="opp3"){state.events.push(createEvent("opp_score",{points:e.target.id==="opp3"?3:2,lineup:[...state.active]},state));closeModal();render()}if(e.target.id==="nextPeriod"){accrue();state.running=false;state.lastTick=null;clearInterval(timer);if(state.period<state.periods){state.period++;state.clockMs=(state.periodMinutes||8)*60000;if((state.periods===4&&state.period===3)||(state.periods===2&&state.period===2))state.offenseRight=!state.offenseRight;applyDirection();closeModal();render()}}});
$("timeoutBtn").addEventListener("click",()=>{accrue();state.running=false;state.lastTick=null;clearInterval(timer);render()});
$("flipDirection").onclick=()=>{state.offenseRight=!state.offenseRight;clearPendingShot();applyDirection();render()};
$("subBtn").onclick=()=>{accrue();let draft=[...state.active],selectedCourt=null;const draw=()=>{const cp=draft.map(id=>roster.find(p=>p.id===id)),bench=roster.filter(p=>!draft.includes(p.id));$("modalBody").innerHTML=`<div class="sub-board"><p class="sub-help">Tap a player on the court, then tap the bench player coming in.</p><div class="sub-court"><h3>ON COURT · 5</h3><div class="sub-five">${cp.map(p=>`<button class="sub-player ${selectedCourt===p.id?"selected":""}" data-court-player="${p.id}">#${p.num}<br>${p.name}</button>`).join("")}</div></div><div class="sub-bench"><h3>BENCH</h3><div class="sub-bench-grid">${bench.map(p=>`<button class="sub-player" data-bench-player="${p.id}">#${p.num}<br>${p.name}</button>`).join("")}</div></div><div class="sub-actions"><button id="resetSub" class="choice">Reset</button><button id="confirmLineup" class="primary">Confirm Substitution</button></div></div>`;document.querySelectorAll("[data-court-player]").forEach(b=>b.onclick=()=>{selectedCourt=b.dataset.courtPlayer;draw()});document.querySelectorAll("[data-bench-player]").forEach(b=>b.onclick=()=>{if(!selectedCourt)return;draft=draft.map(id=>id===selectedCourt?b.dataset.benchPlayer:id);selectedCourt=null;draw()});$("resetSub").onclick=()=>{draft=[...state.active];selectedCourt=null;draw()};$("confirmLineup").onclick=()=>{state.active=[...draft];if(state.running)state.lastTick=Date.now();closeModal();render()}};openModal("Substitution","");draw()};
function promptAssist(shooter){const opts=state.active.filter(x=>x!==shooter).map(id=>({label:roster.find(p=>p.id===id).name,value:id}));opts.push({label:"None",value:"none"});modal("Assist?",opts,id=>{if(id!=="none")state.events.push(createEvent("assist",{playerId:id},state));render()})}
function promptMissRebound(){const opts=state.active.map(id=>({label:roster.find(p=>p.id===id).name,value:id}));opts.push({label:"Opponent",value:"opp"},{label:"Team / Dead Ball",value:"team"},{label:"None",value:"none"});modal("Rebound?",opts,id=>{if(id==="opp")state.events.push(createEvent("opp_rebound",{team:"opponent",lineup:[...state.active]},state));else if(id==="team")state.events.push(createEvent("team_rebound",{team:"us"},state));else if(id!=="none")state.events.push(createEvent("rebound",{playerId:id,lineup:[...state.active]},state));render()})}
function renderSecondary(d){if(!$("statsBody"))return;$("rosterCards").innerHTML=roster.map(p=>`<div class="card">#${p.num} <b>${p.name}</b> ${state.active.includes(p.id)?"· On court":"· Bench"}</div>`).join("");const elapsed=Math.max(0,((state.period-1)*(state.periodMinutes||8)*60000)+((state.periodMinutes||8)*60000-state.clockMs)),expected=elapsed*5,used=Object.values(state.minutes).reduce((a,b)=>a+b,0),bad=Math.abs(used-expected)>=1500;$("timeCheck").classList.toggle("hidden",!bad);$("timeCheck").textContent=bad?"⚠ Playing-time totals are out of sync with elapsed game time.":"";$("timeTable").innerHTML=roster.slice().sort((a,b)=>(state.minutes[b.id]||0)-(state.minutes[a.id]||0)).map(p=>{const m=state.minutes[p.id]||0,pct=elapsed?Math.min(100,Math.round(m/elapsed*100)):0;return`<div class="time-row"><span class="time-name">#${p.num} ${p.name}</span><span class="time-min">${fmt(m)}</span><span class="time-pct">${pct}%</span><span class="time-bar"><i style="width:${pct}%"></i></span></div>`}).join("");$("statsBody").innerHTML=roster.map(p=>{const s=d.players[p.id],m=fmt(state.minutes[p.id]||0);return`<tr><th>#${p.num} ${p.name}</th><td>${m}</td><td>${s.pts}</td><td>${s.fgm}/${s.fga}</td><td>${s.threeM}/${s.threeA}</td><td>${s.ftM}/${s.ftA}</td><td>${s.reb}</td><td>${s.ast}</td><td>${s.stl}</td><td>${s.blk}</td><td>${s.to}</td><td>${s.pf}</td><td>${s.plusMinus>0?"+":""}${s.plusMinus}</td></tr>`}).join("");const shots=state.events.filter(e=>e.type==="shot"),made=shots.filter(e=>e.payload.made);$("shootingSummary").textContent=`${made.length}/${shots.length} field goals · ${shots.filter(e=>e.payload.rimZone).length} rim attempts`;$("fastSummary").textContent=`${shots.filter(e=>e.payload.fastBreak).length} tagged fast-break attempts`;renderShotAnalytics()}
function applyDirection(){document.querySelector(".half.left").classList.toggle("offense",!state.offenseRight);document.querySelector(".half.right").classList.toggle("offense",state.offenseRight);$("teamControls").classList.toggle("controls-right",!state.offenseRight);$("offenseTools").classList.toggle("offense-left",!state.offenseRight);$("gameManage").classList.toggle("manage-left",!state.offenseRight)}
document.querySelectorAll("nav [data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$({game:"gameView",roster:"rosterView",time:"timeView",stats:"statsView",analytics:"analyticsView"}[b.dataset.tab]).classList.remove("hidden");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
function modal(title,choices,cb){openModal(title,`<div class="choices">${choices.map(x=>`<button class="choice" data-choice="${x.value}">${x.label}</button>`).join("")}</div>`);document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{closeModal();cb(b.dataset.choice)})} function openModal(t,b){$("modalTitle").textContent=t;$("modalBody").innerHTML=b;$("modal").classList.remove("hidden")} function closeModal(){$("modal").classList.add("hidden")} $("modalClose").onclick=closeModal;
applyDirection();render();
function populateShotFilters(){const s=$("shotPlayerFilter");if(!s||s.dataset.ready)return;s.innerHTML='<option value="team">Whole Team</option>'+roster.map(p=>'<option value="'+p.id+'">#'+p.num+' '+p.name+'</option>').join('');s.dataset.ready="1";["shotPlayerFilter","shotTimeFilter","shotTypeFilter"].forEach(id=>$(id)?.addEventListener("change",renderShotAnalytics))}
function shotZone(e){let x=e.payload.x,y=e.payload.y;if(e.payload.rimZone)return e.payload.rimZone==="left_finish"?"Left Finish":e.payload.rimZone==="right_finish"?"Right Finish":"Center Rim";const bx=x>.5?1:0,dx=Math.abs(x-bx),dy=y-.5;if(!e.payload.three){if(dx<.28&&Math.abs(dy)<.22)return dy<-.07?"Left Paint":dy>.07?"Right Paint":"Center Paint";if(Math.abs(dy)>.25)return dy<0?"Left Baseline":"Right Baseline";return dy<-.08?"Left Wing Mid":dy>.08?"Right Wing Mid":"Top Midrange"}if(Math.abs(dy)>.36)return dy<0?"Left Corner 3":"Right Corner 3";return dy<-.13?"Left Wing 3":dy>.13?"Right Wing 3":"Top 3"}
function filteredShots(){let a=state.events.filter(e=>e.type==="shot"),pf=$("shotPlayerFilter")?.value||"team",tf=$("shotTimeFilter")?.value||"game",sf=$("shotTypeFilter")?.value||"all";if(pf!=="team")a=a.filter(e=>e.payload.playerId===pf);if(tf!=="game"){const half=state.periods===2?1:2;a=a.filter(e=>tf==="first"?e.period<=half:e.period>half)}if(sf!=="all")a=a.filter(e=>sf==="3"?e.payload.three:!e.payload.three);return a}
function renderShotAnalytics(){if(!$("analyticsCourt"))return;populateShotFilters();const shots=filteredShots(),made=shots.filter(e=>e.payload.made),threes=shots.filter(e=>e.payload.three),tm=threes.filter(e=>e.payload.made),twos=shots.filter(e=>!e.payload.three),twoM=twos.filter(e=>e.payload.made);$("shootingSummary").textContent="FG "+made.length+"/"+shots.length+" · "+(shots.length?Math.round(made.length/shots.length*100):0)+"% | 3PT "+tm.length+"/"+threes.length+" | 2PT "+twoM.length+"/"+twos.length;$("analyticsCourt").innerHTML=shots.map(e=>'<i class="shot-dot '+(e.payload.made?"make":"miss")+'" style="left:'+(e.payload.x*100)+'%;top:'+(e.payload.y*100)+'%">'+(e.payload.made?"✓":"×")+'</i>').join("");const zones={};shots.forEach(e=>{const z=shotZone(e);zones[z]??={a:0,m:0,pts:0};zones[z].a++;if(e.payload.made){zones[z].m++;zones[z].pts+=e.payload.three?3:2}});$("zoneTable").innerHTML=Object.entries(zones).sort((a,b)=>b[1].a-a[1].a).map(([z,v])=>'<div class="zone-cell"><b>'+z+'</b><span>'+v.m+'/'+v.a+' · '+(v.a?Math.round(v.m/v.a*100):0)+'%</span><small>'+(v.a?(v.pts/v.a).toFixed(2):"0.00")+' pts/shot · '+(shots.length?Math.round(v.a/shots.length*100):0)+'% of shots</small></div>').join("")||'<div class="zone-cell">No shots for these filters yet.</div>'}
