export function createHardcourtSharing({sb,getState,escapeHtml}){const state=()=>getState();
 async function invite(role,email=''){const s=state();const {data,error}=await sb.rpc('create_hardcourt_share_invite',{p_team_id:s.cloudTeamId,p_role:role,p_email:email||null,p_expires_days:role==='viewer'?3650:7});if(error)throw error;return String(data||'')}
 async function redeem(token){const {data,error}=await sb.rpc('redeem_hardcourt_share_invite',{p_token:token});if(error)throw error;return Array.isArray(data)?data[0]:data}
 async function members(){const s=state();const {data,error}=await sb.rpc('get_hardcourt_team_members',{p_team_id:s.cloudTeamId});if(error)throw error;return data||[]}
 async function remove(userId){const s=state();const {error}=await sb.rpc('remove_hardcourt_team_member',{p_team_id:s.cloudTeamId,p_user_id:userId});if(error)throw error;return true}
 function link(token){return location.origin+location.pathname+'?hardcourtInvite='+encodeURIComponent(token)}
 async function handleInviteFromUrl(){const u=new URL(location.href),token=u.searchParams.get('hardcourtInvite');if(!token)return null;const row=await redeem(token);u.searchParams.delete('hardcourtInvite');history.replaceState({},'',u);return row}
 async function open(){document.getElementById('hcSharing')?.remove();const root=document.createElement('div');root.id='hcSharing';root.innerHTML=`<style>#hcSharing{position:fixed;inset:0;z-index:100006;background:#07110def;padding:18px;overflow:auto;font-family:system-ui}.hc-share{width:min(620px,100%);margin:25px auto;background:#fff;color:#10231a;border-radius:20px;padding:20px}.hc-share section{padding:14px 0;border-bottom:1px solid #dde6e1}.hc-share input{width:100%;box-sizing:border-box;padding:10px;margin:8px 0}.hc-share button{padding:10px 12px;margin:4px;border:1px solid #ccd7d1;border-radius:9px;background:#fff}.hc-member{display:flex;justify-content:space-between;gap:10px;padding:8px 0}</style><div class="hc-share"><h2>Team & Sharing</h2><p>One team account, with controlled access for coaches, parents and game-day helpers.</p><section><b>Parent / Viewer Link</b><p>Reusable read-only team link for families.</p><button id="hcMakeViewer">Create Viewer Link</button><div id="hcViewerResult"></div></section><section><b>Coach Access</b><p>Team Pro supports up to 5 coach seats. Coach invitations are locked to an email.</p><input id="hcCoachEmail" type="email" placeholder="coach@example.com"><button id="hcMakeCoach">Invite Coach</button><div id="hcCoachResult"></div></section><section><b>Current Members</b><div id="hcMembers">Loading…</div></section><button id="hcShareClose">Close</button></div>`;document.body.appendChild(root);root.querySelector('#hcShareClose').onclick=()=>root.remove();const putLink=(host,token)=>{const url=link(token);host.innerHTML=`<input readonly value="${escapeHtml(url)}"><button data-copy>Copy Link</button>`;host.querySelector('[data-copy]').onclick=async e=>{await navigator.clipboard?.writeText(url);e.target.textContent='Copied'}};root.querySelector('#hcMakeViewer').onclick=async()=>{const h=root.querySelector('#hcViewerResult');try{putLink(h,await invite('viewer'))}catch(e){h.textContent=e.message}};root.querySelector('#hcMakeCoach').onclick=async()=>{const h=root.querySelector('#hcCoachResult');try{putLink(h,await invite('coach',root.querySelector('#hcCoachEmail').value.trim()))}catch(e){h.textContent=e.message}};try{const rows=await members();root.querySelector('#hcMembers').innerHTML=rows.length?rows.map(m=>`<div class="hc-member"><span><b>${escapeHtml(m.email)}</b><small> · ${escapeHtml(m.member_role)}</small></span><button data-remove="${escapeHtml(m.user_id)}">Remove</button></div>`).join(''):'<p>No additional members yet.</p>';root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this team member?'))return;await remove(b.dataset.remove);root.remove();open()})}catch(e){root.querySelector('#hcMembers').textContent=e.message}}
 return{invite,redeem,members,remove,handleInviteFromUrl,open}}
