(()=>{
const DATA_KEY='sidelineStatsData',PROFILE_KEY='sidelinePlayerCardProfiles';
const SUPABASE_URL='https://eyuvgzhkhcpwtcbmsvct.supabase.co',SUPABASE_KEY='sb_publishable_uMOkwO4jyHen4pz4zCkIuQ_Ss-wUf2l';
const $=s=>document.querySelector(s);let activeId=null,draft=null;
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function state(){try{return JSON.parse(localStorage.getItem(DATA_KEY)||'{}')}catch(_){return {}}}
function profiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch(_){return {}}}
function saveProfiles(v){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(v));return true}catch(_){alert('This device is out of storage for player photos. Try a smaller photo.');return false}}
function playerById(id){return (state().roster||[]).find(p=>String(p.id)===String(id))||null}
function defaultProfile(){return {primaryPosition:'',secondaryPosition:'',actionPhotoData:null,headshotData:null,actionCrop:{scale:1,x:0,y:0},headshotCrop:{scale:1,x:0,y:0},updatedAt:null}}
function getProfile(id){return {...defaultProfile(),...(profiles()[id]||{})}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addStyles(){const st=document.createElement('style');st.textContent=`
.pp-meta{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:5px}.pp-tag{font-size:11px;font-weight:900;padding:3px 7px;border-radius:999px;background:color-mix(in srgb,var(--p) 13%,white);border:1px solid color-mix(in srgb,var(--p) 30%,#ddd)}.pp-edit{border:0;border-radius:8px;padding:6px 9px;font-size:11px;font-weight:900;background:var(--p);color:var(--nav-text);cursor:pointer}.pp-modal{position:fixed;inset:0;background:#000a;z-index:12000;display:flex;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.pp-modal.hidden{display:none}.pp-card{width:min(680px,100%);background:#fff;border-radius:18px;padding:16px;color:#17202a}.pp-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.pp-head h2{margin:0}.pp-close{border:0;border-radius:50%;width:36px;height:36px;font-size:20px;font-weight:900}.pp-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.pp-field{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:850}.pp-field input{padding:10px;border:1px solid #d7dade;border-radius:10px}.pp-photo{margin-top:12px;border:1px solid #ddd;border-radius:14px;padding:12px}.pp-preview{width:100%;height:280px;background:#e8e4dc;border-radius:12px;overflow:hidden;position:relative;margin-top:8px;touch-action:none;user-select:none;cursor:grab;border:2px solid #17202a}.pp-preview:active{cursor:grabbing}.pp-preview canvas{position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none}.pp-preview-hint{position:absolute;left:50%;bottom:9px;transform:translateX(-50%);z-index:2;background:#111c;color:#fff;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:900;white-space:nowrap;pointer-events:none}.pp-photo-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:8px}.pp-reset,.pp-copy{border:0;border-radius:8px;padding:7px 9px;font-size:11px;font-weight:850}.pp-reset{background:#eceff1;color:#17202a}.pp-copy{background:#17202a;color:#fff}.pp-actions{display:flex;gap:8px;margin-top:14px}.pp-actions button{flex:1;border:0;border-radius:10px;padding:11px;font-weight:900}.pp-save{background:var(--p);color:var(--nav-text)}.pp-note{font-size:11px;color:#687078;margin-top:6px;line-height:1.4}@media(max-width:600px){.pp-grid{grid-template-columns:1fr}.pp-preview{height:250px}}
`;document.head.appendChild(st)}
function ensureModal(){if($('#playerProfileModal'))return;const m=document.createElement('div');m.id='playerProfileModal';m.className='pp-modal hidden';m.innerHTML=`<div class="pp-card"><div class="pp-head"><div><h2 id="ppTitle">Player Card Profile</h2><div class="pp-note">Set default positions and photos parents can use instantly.</div></div><button class="pp-close" id="ppClose">×</button></div><div class="pp-grid" style="margin-top:12px"><label class="pp-field">Primary position<input id="ppPrimary" maxlength="12" placeholder="QB"></label><label class="pp-field">Secondary position <span style="font-weight:500">(optional)</span><input id="ppSecondary" maxlength="12" placeholder="DE"></label></div><section class="pp-photo"><strong>Action photo</strong><input id="ppActionFile" type="file" accept="image/*" style="display:block;margin-top:7px"><div class="pp-preview" id="ppActionPreview"></div><div class="pp-photo-actions"><button class="pp-reset" id="ppActionReset" type="button">Reset crop</button><span class="pp-note" style="margin:0">Drag to position • pinch to zoom</span></div></section><section class="pp-photo"><strong>Headshot</strong><div class="pp-note">Use a separate headshot, or reuse the action photo and crop it differently.</div><input id="ppHeadFile" type="file" accept="image/*" style="display:block;margin-top:7px"><div class="pp-photo-actions"><button class="pp-copy" id="ppUseAction" type="button">Use action photo</button><button class="pp-reset" id="ppHeadReset" type="button">Reset crop</button></div><div class="pp-preview" id="ppHeadPreview"></div><div class="pp-note">Drag to position • pinch to zoom</div></section><div class="pp-actions"><button class="pp-save" id="ppSave">Save Player Profile</button></div></div>`;document.body.appendChild(m);
 $('#ppClose').onclick=()=>m.classList.add('hidden');m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')});$('#ppSave').onclick=save;
 $('#ppUseAction').onclick=()=>{if(draft?.actionPhotoData){draft.headshotData=draft.actionPhotoData;draft.headshotCrop={scale:1,x:0,y:0};renderPreviews()}};
 $('#ppActionReset').onclick=()=>{draft.actionCrop={scale:1,x:0,y:0};renderPreviews()};$('#ppHeadReset').onclick=()=>{draft.headshotCrop={scale:1,x:0,y:0};renderPreviews()};
 bindPhoto('#ppActionFile','actionPhotoData');bindPhoto('#ppHeadFile','headshotData');bindGesture($('#ppActionPreview'),'actionCrop');bindGesture($('#ppHeadPreview'),'headshotCrop');
 window.addEventListener('resize',()=>{if(draft)renderPreviews()});
}
function bindPhoto(sel,key){$(sel).addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;draft[key]=await compress(f);draft[key==='actionPhotoData'?'actionCrop':'headshotCrop']={scale:1,x:0,y:0};renderPreviews()})}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1600,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.86))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function drawPreview(el,data,crop){
 el.innerHTML=data?'<canvas></canvas><div class="pp-preview-hint">Drag • pinch to zoom</div>':'<div style="display:grid;place-items:center;height:100%;color:#777;font-weight:800">No photo yet</div>';if(!data)return;
 const cv=el.querySelector('canvas'),r=el.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);cv.width=Math.max(1,Math.round(r.width*dpr));cv.height=Math.max(1,Math.round(r.height*dpr));const ctx=cv.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#e8e4dc';ctx.fillRect(0,0,r.width,r.height);
 const im=new Image();im.onload=()=>{const base=Math.max(r.width/im.naturalWidth,r.height/im.naturalHeight),scale=base*Number(crop?.scale||1),dw=im.naturalWidth*scale,dh=im.naturalHeight*scale,dx=(r.width-dw)/2+Number(crop?.x||0)*r.width*.32,dy=(r.height-dh)/2+Number(crop?.y||0)*r.height*.32;ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#e8e4dc';ctx.fillRect(0,0,r.width,r.height);ctx.drawImage(im,dx,dy,dw,dh)};im.src=data;
}
function renderPreviews(){drawPreview($('#ppActionPreview'),draft.actionPhotoData,draft.actionCrop);drawPreview($('#ppHeadPreview'),draft.headshotData,draft.headshotCrop)}
function bindGesture(el,cropKey){const pts=new Map();let last=null,pinch=null;const crop=()=>draft?.[cropKey];const dist=()=>{const a=[...pts.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)};const center=()=>{const a=[...pts.values()];return a.length<2?null:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}};
 el.addEventListener('pointerdown',e=>{if(!crop())return;e.preventDefault();el.setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===1)last={x:e.clientX,y:e.clientY};else if(pts.size===2){pinch={distance:dist(),scale:Number(crop().scale||1),center:center()};last=null}});
 el.addEventListener('pointermove',e=>{if(!pts.has(e.pointerId)||!crop())return;e.preventDefault();pts.set(e.pointerId,{x:e.clientX,y:e.clientY});const r=el.getBoundingClientRect();if(pts.size>=2&&pinch){const d=dist(),ctr=center();if(pinch.distance>0)crop().scale=clamp(pinch.scale*(d/pinch.distance),1,4);if(ctr&&pinch.center){crop().x=clamp(Number(crop().x||0)+(ctr.x-pinch.center.x)/(Math.max(1,r.width)*.32),-2.5,2.5);crop().y=clamp(Number(crop().y||0)+(ctr.y-pinch.center.y)/(Math.max(1,r.height)*.32),-2.5,2.5);pinch.center=ctr}renderPreviews();return}if(pts.size===1&&last){crop().x=clamp(Number(crop().x||0)+(e.clientX-last.x)/(Math.max(1,r.width)*.32),-2.5,2.5);crop().y=clamp(Number(crop().y||0)+(e.clientY-last.y)/(Math.max(1,r.height)*.32),-2.5,2.5);last={x:e.clientX,y:e.clientY};renderPreviews()}});
 const end=e=>{pts.delete(e.pointerId);if(pts.size===1){const p=[...pts.values()][0];last={x:p.x,y:p.y};pinch=null}else if(!pts.size){last=null;pinch=null}};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('wheel',e=>{if(!crop())return;e.preventDefault();crop().scale=clamp(Number(crop().scale||1)*(e.deltaY<0?1.08:.92),1,4);renderPreviews()},{passive:false});
}
function open(id){const p=playerById(id);if(!p)return;activeId=id;draft=JSON.parse(JSON.stringify(getProfile(id)));$('#ppTitle').textContent=`#${p.jersey} ${p.name}`;$('#ppPrimary').value=draft.primaryPosition||'';$('#ppSecondary').value=draft.secondaryPosition||'';$('#playerProfileModal').classList.remove('hidden');setTimeout(renderPreviews,0)}
async function save(){if(!activeId)return;draft.primaryPosition=$('#ppPrimary').value.trim().toUpperCase();draft.secondaryPosition=$('#ppSecondary').value.trim().toUpperCase();draft.updatedAt=new Date().toISOString();const all=profiles();all[activeId]=draft;if(!saveProfiles(all))return;await syncCloud(activeId,draft);$('#playerProfileModal').classList.add('hidden');enhanceRoster()}
async function syncCloud(localId,p){try{const s=state(),cloudId=s.cloud?.playerIds?.[localId];if(!cloudId||!window.supabase?.createClient)return;const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session}}=await sb.auth.getSession();if(!session)return;const {error}=await sb.from('players').update({primary_position:p.primaryPosition||null,secondary_position:p.secondaryPosition||null,action_photo_data:p.actionPhotoData||null,headshot_data:p.headshotData||null,action_photo_crop:p.actionCrop||{scale:1,x:0,y:0},headshot_crop:p.headshotCrop||{scale:1,x:0,y:0}}).eq('id',cloudId);if(error)throw error}catch(e){console.warn('Player card profile cloud sync skipped',e);alert('Saved on this device. Cloud profile sync will retry when available.')}}
function enhanceRoster(){const s=state(),list=$('#rosterList');if(!list||!(s.roster||[]).length)return;const rows=[...list.querySelectorAll('.player')],sorted=[...(s.roster||[])].sort((a,b)=>Number(a.jersey)-Number(b.jersey));rows.forEach((row,i)=>{const p=sorted[i];if(!p)return;let meta=row.querySelector('.pp-meta');if(!meta){meta=document.createElement('div');meta.className='pp-meta';row.firstElementChild?.appendChild(meta)}const prof=getProfile(p.id),positions=[prof.primaryPosition,prof.secondaryPosition].filter(Boolean).join(' • ');meta.innerHTML=`${positions?`<span class="pp-tag">${esc(positions)}</span>`:''}${prof.actionPhotoData?'<span class="pp-tag">📷 Action</span>':''}${prof.headshotData?'<span class="pp-tag">🙂 Headshot</span>':''}<button class="pp-edit" type="button">Card Profile</button>`;meta.querySelector('.pp-edit').onclick=e=>{e.stopPropagation();open(p.id)}})}
function watch(){const list=$('#rosterList');if(!list)return;new MutationObserver(()=>setTimeout(enhanceRoster,0)).observe(list,{childList:true,subtree:true});enhanceRoster()}
function init(){addStyles();ensureModal();watch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
