(function(root){
const ACTION_MAX=1400,HEAD_MAX=800,QUALITY=.82,STATE_KEY="sidelineStatsData";
function blobToDataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(r.error||new Error("Could not read image"));r.readAsDataURL(blob)})}
function loadImage(source){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Could not decode image"));img.src=source})}
async function optimizeDataUrl(dataUrl,{maxDimension=ACTION_MAX,quality=QUALITY}={}){const img=await loadImage(dataUrl),iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,scale=Math.min(1,maxDimension/Math.max(iw,ih)),w=Math.max(1,Math.round(iw*scale)),h=Math.max(1,Math.round(ih*scale)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d",{alpha:false}).drawImage(img,0,0,w,h);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",quality));if(!blob)throw new Error("Could not optimize image");return {blob,dataUrl:await blobToDataUrl(blob),width:w,height:h,bytes:blob.size}}
async function optimizeFile(file,kind="action"){if(!file||!/^image\//.test(file.type||""))throw new Error("Choose an image file");return optimizeDataUrl(await blobToDataUrl(file),{maxDimension:kind==="headshot"?HEAD_MAX:ACTION_MAX})}
function isPlayerMediaInput(input){if(!(input instanceof HTMLInputElement)||input.type!=="file")return false;const marker=`${input.id||""} ${input.name||""} ${input.getAttribute("aria-label")||""} ${input.closest(".modal-card,.card,form,section")?.textContent||""}`.toLowerCase();return marker.includes("headshot")||marker.includes("action photo")||marker.includes("player profile")||marker.includes("player photo")}
function mediaKind(input){const marker=`${input.id||""} ${input.name||""} ${input.getAttribute("aria-label")||""} ${input.closest(".modal-card,.card,form,section")?.textContent||""}`.toLowerCase();return marker.includes("headshot")?"headshot":"action"}
document.addEventListener("change",async e=>{const input=e.target;if(!isPlayerMediaInput(input)||input.dataset.sidelineOptimized==="1")return;const file=input.files?.[0];if(!file||!/^image\//.test(file.type||"")||typeof DataTransfer==="undefined")return;e.preventDefault();e.stopImmediatePropagation();try{const optimized=await optimizeFile(file,mediaKind(input)),dt=new DataTransfer();dt.items.add(new File([optimized.blob],file.name.replace(/\.[^.]+$/,"")+".jpg",{type:"image/jpeg",lastModified:Date.now()}));input.files=dt.files;input.dataset.sidelineOptimized="1";input.dispatchEvent(new Event("change",{bubbles:true}));delete input.dataset.sidelineOptimized}catch(err){console.warn("Player photo optimization failed",err);input.dataset.sidelineOptimized="1";input.dispatchEvent(new Event("change",{bubbles:true}));delete input.dataset.sidelineOptimized}},true);
async function compactLocalPlayerPhotos(){let raw;try{raw=localStorage.getItem(STATE_KEY)}catch(_){return}if(!raw)return;let state;try{state=JSON.parse(raw)}catch(_){return}let changed=false;async function walk(node){if(!node||typeof node!=="object")return;for(const [k,v] of Object.entries(node)){if(typeof v==="string"&&v.startsWith("data:image/")&&/(action.*photo|headshot|player.*photo|photo.*data)/i.test(k)&&v.length>120000){try{const o=await optimizeDataUrl(v,{maxDimension:/headshot/i.test(k)?HEAD_MAX:ACTION_MAX});node[k]=o.dataUrl;changed=true}catch(_e){}}else if(v&&typeof v==="object")await walk(v)}}await walk(state);if(changed){try{localStorage.setItem(STATE_KEY,JSON.stringify(state))}catch(e){console.warn("Could not compact local player photos",e)}}}
root.SidelinePlayerMedia={ACTION_MAX,HEAD_MAX,QUALITY,optimizeFile,optimizeDataUrl};setTimeout(compactLocalPlayerPhotos,1200);
})(window);